var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>RendererContext Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1RendererContext.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>RendererContext Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">RendererContext Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__renderercontext_8h_source.html\">xsi_renderercontext.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>This object is provided as the context object in the Renderer callbacks for a Plugin-based <a href=\"#!/url=./files/cus_render.htm\">Custom Renderer</a> object. </p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PluginRegistrar.html#a295501439774aa8639ee071fcc8667e8\">PluginRegistrar::RegisterRenderer</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.0 </dd></dl>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"closed.png\" alt=\"+\"> Inheritance diagram for RendererContext:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"classXSI_1_1RendererContext.png\" usemap=\"#RendererContext_map\" alt=\"\">\n\
  <map id=\"RendererContext_map\" name=\"RendererContext_map\">\n\
<area href=\"classXSI_1_1Context.html\" title=\"This is a general, flexible Context object that is used for callbacks. Instances of this object are u...\" alt=\"Context\" shape=\"rect\" coords=\"0,56,107,80\">\n\
<area href=\"classXSI_1_1CBase.html\" title=\"CBase is the base class of all API classes and provides access to Softimage objects through generic C...\" alt=\"CBase\" shape=\"rect\" coords=\"0,0,107,24\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a2b3fe19679f40604eea9482972d032b8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a2b3fe19679f40604eea9482972d032b8\">RendererContext</a> ()</td></tr>\n\
<tr class=\"separator:a2b3fe19679f40604eea9482972d032b8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af3bf89ea3be1635d753c3354af387ee1\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#af3bf89ea3be1635d753c3354af387ee1\">~RendererContext</a> ()</td></tr>\n\
<tr class=\"separator:af3bf89ea3be1635d753c3354af387ee1\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a898b09a15e7d31d10dbbc21465eb37d0\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a898b09a15e7d31d10dbbc21465eb37d0\">RendererContext</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a898b09a15e7d31d10dbbc21465eb37d0\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a889da6592fa9b7f7bb7819fa00491146\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a889da6592fa9b7f7bb7819fa00491146\">RendererContext</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a889da6592fa9b7f7bb7819fa00491146\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7abac6b21f22e3d268d8b32f0640d5b9\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a7abac6b21f22e3d268d8b32f0640d5b9\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a7abac6b21f22e3d268d8b32f0640d5b9\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2a297b245b3e9f43bdb64b057a77ed0c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a2a297b245b3e9f43bdb64b057a77ed0c\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a2a297b245b3e9f43bdb64b057a77ed0c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab214e0f52e1d704d9541de66b95030fc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">CTime</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#ab214e0f52e1d704d9541de66b95030fc\">GetTime</a> () const </td></tr>\n\
<tr class=\"separator:ab214e0f52e1d704d9541de66b95030fc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a891540367d53d767ba03d75cee715f07\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">unsigned int&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a891540367d53d767ba03d75cee715f07\">GetSequenceIndex</a> () const </td></tr>\n\
<tr class=\"separator:a891540367d53d767ba03d75cee715f07\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a68ba913b7bc6e5810905f3dd2ad65dad\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">unsigned int&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a68ba913b7bc6e5810905f3dd2ad65dad\">GetSequenceLength</a> () const </td></tr>\n\
<tr class=\"separator:a68ba913b7bc6e5810905f3dd2ad65dad\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acd6dfce99749d8065d6311f546b6a74a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#acd6dfce99749d8065d6311f546b6a74a\">ProgressUpdate</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_strProgressShort, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_strProgressLong, int in_iPercentage)</td></tr>\n\
<tr class=\"separator:acd6dfce99749d8065d6311f546b6a74a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afd4489866206d672a6a115ddcb0bcef7\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#afd4489866206d672a6a115ddcb0bcef7\">NewFrame</a> (unsigned int in_uiWidth, unsigned int in_uiHeight)</td></tr>\n\
<tr class=\"separator:afd4489866206d672a6a115ddcb0bcef7\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae53cb46c97f7b24f64348a2bc83345e9\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#ae53cb46c97f7b24f64348a2bc83345e9\">NewFragment</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererImageFragment.html\">RendererImageFragment</a> &amp;in_fragment)</td></tr>\n\
<tr class=\"separator:ae53cb46c97f7b24f64348a2bc83345e9\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0dae3b66379c4fac4e728ccfebb08dea\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a0dae3b66379c4fac4e728ccfebb08dea\">TriggerEvent</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5\">siEventID</a> in_eEventID, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a03fe29449ab21ba9a85ae1ab1b38a532\">siRenderingType</a> in_eRenderingType, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">CTime</a> &amp;in_rTime, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a> &amp;in_filenames, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a21ecf40e5374e704576f1c0e32058cf9\">siRenderFieldType</a> in_eFieldType, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad2ad8c6d0c942fcd9c7ed4be85abd414\">siRenderingErrorType</a> in_eRenderErrorType)</td></tr>\n\
<tr class=\"separator:a0dae3b66379c4fac4e728ccfebb08dea\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ade812f7ad529f568b6e1590a33cd65c9\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\">Property</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#ade812f7ad529f568b6e1590a33cd65c9\">GetRendererProperty</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">CTime</a> &amp;in_rTime)</td></tr>\n\
<tr class=\"separator:ade812f7ad529f568b6e1590a33cd65c9\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac8fc4bbd170f32a1111e89a499af5d5a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Framebuffer.html\">Framebuffer</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#ac8fc4bbd170f32a1111e89a499af5d5a\">GetDisplayFramebuffer</a> ()</td></tr>\n\
<tr class=\"separator:ac8fc4bbd170f32a1111e89a499af5d5a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa3f0086485c102ac41ff990cc588c5b4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#aa3f0086485c102ac41ff990cc588c5b4\">GetFramebuffers</a> ()</td></tr>\n\
<tr class=\"separator:aa3f0086485c102ac41ff990cc588c5b4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6c2a97171e88477423af0c51feabb4e0\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a6c2a97171e88477423af0c51feabb4e0\">SetObjectClean</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a6c2a97171e88477423af0c51feabb4e0\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1Context\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1Context\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">Context</a></td></tr>\n\
<tr class=\"memitem:a7540648fc201ffee17e0cdea0888a6f7 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a7540648fc201ffee17e0cdea0888a6f7\">Context</a> ()</td></tr>\n\
<tr class=\"separator:a7540648fc201ffee17e0cdea0888a6f7 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad2cdbdf8ca6efd618beb4f0c416e02f9 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#ad2cdbdf8ca6efd618beb4f0c416e02f9\">~Context</a> ()</td></tr>\n\
<tr class=\"separator:ad2cdbdf8ca6efd618beb4f0c416e02f9 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a73fe9172a5147d89d695d3a57a284190 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a73fe9172a5147d89d695d3a57a284190\">Context</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a73fe9172a5147d89d695d3a57a284190 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2c9e9ed51cf3ea94f78e23544a55950c inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a2c9e9ed51cf3ea94f78e23544a55950c\">Context</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">Context</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a2c9e9ed51cf3ea94f78e23544a55950c inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7f9674ba9c40f063b97287a577c42013 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">Context</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a7f9674ba9c40f063b97287a577c42013\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">Context</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a7f9674ba9c40f063b97287a577c42013 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a70910e495d955d84cff6d25793bb6b1c inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">Context</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a70910e495d955d84cff6d25793bb6b1c\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a70910e495d955d84cff6d25793bb6b1c inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4120d0f5a8c5296445162539bb64fee8 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a4120d0f5a8c5296445162539bb64fee8\">GetSource</a> () const </td></tr>\n\
<tr class=\"separator:a4120d0f5a8c5296445162539bb64fee8 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aeeaa196cd9710d160c2d5dc08918cf7f inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#aeeaa196cd9710d160c2d5dc08918cf7f\">GetAttribute</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_AttributeName)</td></tr>\n\
<tr class=\"separator:aeeaa196cd9710d160c2d5dc08918cf7f inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae72b22490aa03abbda8a4c40dc553a3c inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#ae72b22490aa03abbda8a4c40dc553a3c\">PutAttribute</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_AttributeName, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> &amp;in_val)</td></tr>\n\
<tr class=\"separator:ae72b22490aa03abbda8a4c40dc553a3c inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a73bb3a21a46506ac475f0b1b19821f5d inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a73bb3a21a46506ac475f0b1b19821f5d\">PutArrayAttribute</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_AttributeName, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_array)</td></tr>\n\
<tr class=\"separator:a73bb3a21a46506ac475f0b1b19821f5d inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a78de0632797ae0789e00ef4336d4ec79 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a78de0632797ae0789e00ef4336d4ec79\">GetArrayAttribute</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_AttributeName) const </td></tr>\n\
<tr class=\"separator:a78de0632797ae0789e00ef4336d4ec79 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a47d177f40b4b488597d444d241dcc959 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a47d177f40b4b488597d444d241dcc959\">GetUserData</a> ()</td></tr>\n\
<tr class=\"separator:a47d177f40b4b488597d444d241dcc959 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a70bc1b65f444a8f8886e95a03c6b56f0 inherit pub_methods_classXSI_1_1Context\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a70bc1b65f444a8f8886e95a03c6b56f0\">PutUserData</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> &amp;in_val)</td></tr>\n\
<tr class=\"separator:a70bc1b65f444a8f8886e95a03c6b56f0 inherit pub_methods_classXSI_1_1Context\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1CBase\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1CBase\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td></tr>\n\
<tr class=\"memitem:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a3878f3ab13413eb6d4811dca38b4fa73\">CBase</a> ()</td></tr>\n\
<tr class=\"separator:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a012a4573399b53f0720fcf4ff787c048\">~CBase</a> ()</td></tr>\n\
<tr class=\"separator:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac347619969a79eb8afc0adf6ea9394ba\">GetClassIDName</a> () const </td></tr>\n\
<tr class=\"separator:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac8759bb33eaf8bf83949277169a048e6\">IsA</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a458e6e03ea0b71cb2205a5fd9e1999c8\">SetObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a> () const </td></tr>\n\
<tr class=\"separator:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac5a79b5ac1759bc4e66e8f662b8bad49\">ResetObject</a> ()</td></tr>\n\
<tr class=\"separator:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a20250592358718fccc1dad9e949d3d28\">operator CRef &amp;</a> ()</td></tr>\n\
<tr class=\"separator:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac91cdd4cb81fac44686c538126a4b98a\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a99049c404ae9b0ae189f80771dee0596\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#aac2a77c9ccdd6d0f9953ef784e2be5e9\">GetRef</a> () const </td></tr>\n\
<tr class=\"separator:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a2b3fe19679f40604eea9482972d032b8\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af3bf89ea3be1635d753c3354af387ee1\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a898b09a15e7d31d10dbbc21465eb37d0\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant reference object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a889da6592fa9b7f7bb7819fa00491146\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a6dd5a8a11eee55f434f151d1cd5d29d8\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool IsA </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_ClassID</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if a given class type is compatible with this API class. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ClassID</td><td>class type. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if the class is compatible, false otherwise. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">Context</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acc34f4a01f2089e40f7abc7e9d98bf15\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the type of the API class. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The class type. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#acc34f4a01f2089e40f7abc7e9d98bf15\">Context</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7abac6b21f22e3d268d8b32f0640d5b9\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from another object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\" title=\"This object is provided as the context object in the Renderer callbacks for a Plugin-based Custom Ren...\">RendererContext</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a2a297b245b3e9f43bdb64b057a77ed0c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\">RendererContext</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from a reference object. The newly created object is set to empty if the input reference object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html\" title=\"This object is provided as the context object in the Renderer callbacks for a Plugin-based Custom Ren...\">RendererContext</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab214e0f52e1d704d9541de66b95030fc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">CTime</a> GetTime </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the time at which the render process is occurring. The renderer should use this to set the evaluation time for the scene data being rendered. In the case of field rendering, or motion blurring, this time should be used as the base for which to derive other time stops. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The time at which the current frame is being rendered. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a891540367d53d767ba03d75cee715f07\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">unsigned int GetSequenceIndex </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the zero-based index of the frame being rendered within the rendered sequence. The sequence starts at zero and counts in ascending order. For single-frame renders, this function always returns zero. For sequence renders the highest value is always one less than the return value of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#a68ba913b7bc6e5810905f3dd2ad65dad\">RendererContext::GetSequenceLength</a>. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The sequence index of the current frame. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a68ba913b7bc6e5810905f3dd2ad65dad\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">unsigned int GetSequenceLength </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the length of the sequence being rendered. For single frames, this function always returns 1. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The number of frames in the sequence currently being rendered. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acd6dfce99749d8065d6311f546b6a74a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> ProgressUpdate </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_strProgressShort</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_strProgressLong</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">int&#160;</td>\n\
          <td class=\"paramname\"><em>in_iPercentage</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Notifies XSI as to what the current status of the rendering process is. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_strProgressShort</td><td>Short progress message (when using the small progress bar). </td></tr>\n\
    <tr><td class=\"paramname\">in_strProgressLong</td><td>Longer progress message (when using the big progress bar or the render viewer). </td></tr>\n\
    <tr><td class=\"paramname\">in_iPercentage</td><td>The percentage of the job done, if it can be indicated, or -1 </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"afd4489866206d672a6a115ddcb0bcef7\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> NewFrame </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">unsigned int&#160;</td>\n\
          <td class=\"paramname\"><em>in_uiWidth</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned int&#160;</td>\n\
          <td class=\"paramname\"><em>in_uiHeight</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Notifies the render manager that a new frame is about to be sent to whichever render viewer might be listening for frame fragments. In the case of field rendering, both frames should be sent to the viewer. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_uiWidth</td><td>The width of the new frame (needs to be the same as the value of the <code>ImageWidth</code> context parameter). </td></tr>\n\
    <tr><td class=\"paramname\">in_uiHeight</td><td>The height of the new frame (needs to be the same as the value of the <code>ImageHeight</code> context parameter). </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ae53cb46c97f7b24f64348a2bc83345e9\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> NewFragment </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererImageFragment.html\">RendererImageFragment</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_fragment</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Passes back a new frame fragment to the render manager. See RenderImageFragment for more details. </p>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">in_fragment</td><td>The new RenderImageFragment </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0dae3b66379c4fac4e728ccfebb08dea\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> TriggerEvent </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5\">siEventID</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_eEventID</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a03fe29449ab21ba9a85ae1ab1b38a532\">siRenderingType</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_eRenderingType</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">CTime</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_rTime</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_filenames</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a21ecf40e5374e704576f1c0e32058cf9\">siRenderFieldType</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_eFieldType</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad2ad8c6d0c942fcd9c7ed4be85abd414\">siRenderingErrorType</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_eRenderErrorType</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Triggers a specific render event. At the moment only <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5af9e646c144dfa9afa597b8f4fb59c28a\">siOnBeginFrame</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5a1eff897232b9eed6ee8bce1a982c0ff8\">siOnEndFrame</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5a708351d4e28dd02e53e1e9f57502f49d\">siOnBeginSequence</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5ad048d2d6c70e80012ff72af86665a713\">siOnEndSequence</a> and <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5a3f0e1229c3b22dddf1df8c694e676311\">siOnRenderAbort</a> are supported. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_eEventID</td><td>The event being called. </td></tr>\n\
    <tr><td class=\"paramname\">in_eRenderingType</td><td>The type of rendering being performed. </td></tr>\n\
    <tr><td class=\"paramname\">in_rTime</td><td>The time at which the render event is occurring. Only relevant for <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5af9e646c144dfa9afa597b8f4fb59c28a\">siOnBeginFrame</a> and <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5a1eff897232b9eed6ee8bce1a982c0ff8\">siOnEndFrame</a>. </td></tr>\n\
    <tr><td class=\"paramname\">in_filenames</td><td>The list of filenames being rendered out. In case of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5a708351d4e28dd02e53e1e9f57502f49d\">siOnBeginSequence</a> and <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5ad048d2d6c70e80012ff72af86665a713\">siOnEndSequence</a> these should be time-independent filenames, which can be accessed by calling <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Framebuffer.html#a215093b924a62b20329b9181f28a76f2\">Framebuffer::GetResolvedPath</a> with no parameters. </td></tr>\n\
    <tr><td class=\"paramname\">in_eFieldType</td><td>The field being rendered, or <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a21ecf40e5374e704576f1c0e32058cf9aab0a58f594e12d68fefa351c7687b746\">siRenderFieldNone</a> if not rendering fields. </td></tr>\n\
    <tr><td class=\"paramname\">siRenderingErrorType</td><td>The type of error for <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#afb6ebbe7710e6898a918148eb7c6b0e5a3f0e1229c3b22dddf1df8c694e676311\">siOnRenderAbort</a>, defaults to siRenderNoError.</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> The event was sent successfully. </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da596ba78c00d5ebb3b20ef2865efd74ed\">CStatus::Abort</a> The render was aborted while the event was being processed or the event requested an abort. The render should abort immediately at this point with a status code of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a>. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ade812f7ad529f568b6e1590a33cd65c9\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\">Property</a> GetRendererProperty </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">CTime</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_rTime</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the renderer\'s option property evaluated at a specific time. Which particular property instance this is, is dependent upon who triggered the render (pass, region, shaderballs, etc.) </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_rTime</td><td>The time to evaluate the property at. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The evaluated renderer option property. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ac8fc4bbd170f32a1111e89a499af5d5a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Framebuffer.html\">Framebuffer</a> GetDisplayFramebuffer </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Framebuffer.html\" title=\"The Framebuffer object controls the file output of a RenderChannel object. It can be created using th...\">Framebuffer</a> object whose contents should be sent back as an image fragment to the render manager via <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1RendererContext.html#ae53cb46c97f7b24f64348a2bc83345e9\">RendererContext::NewFragment</a>. If the Framebuffer object is not valid then no fragments are needed for viewing (for example when doing a command-line render or archive export). The display framebuffer also dictates the bit depth which the RenderImageFragment object should return its fragment data as. The object returned by this function is not guaranteed to be found in the list of Framebuffer objects returned by GetFramebuffers. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Framebuffer.html\" title=\"The Framebuffer object controls the file output of a RenderChannel object. It can be created using th...\">Framebuffer</a> object selected for viewing. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa3f0086485c102ac41ff990cc588c5b4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> GetFramebuffers </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns all <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Framebuffer.html\" title=\"The Framebuffer object controls the file output of a RenderChannel object. It can be created using th...\">Framebuffer</a> objects that should be rendered for the current frame. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>An array of references to <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Framebuffer.html\" title=\"The Framebuffer object controls the file output of a RenderChannel object. It can be created using th...\">Framebuffer</a> objects. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>6.01 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a6c2a97171e88477423af0c51feabb4e0\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetObjectClean </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Marks the given object from the dirty list as being clean. This only affects the next call to the renderer\'s <a href=\"#!/url=./files/cb_Renderer_Process.htm\">Process</a> callback, if the render got aborted and restarted. It does not update the copy of the dirty list, retrieved from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html#aeeaa196cd9710d160c2d5dc08918cf7f\">Context::GetAttribute</a>. It\'s up to the caller to ensure they stay synchronised during the callback.</p>\n\
<p>This call is used to ensure that if the render gets restarted, for example due to a parameter values change, that the renderer does not have to re-update its copy of scene data that it considers \'clean\'. The dirty list is cleared by Softimage upon the completion of a successful render.</p>\n\
<dl class=\"section user\"><dt>Note:</dt><dd>If the renderer gets called with a \'full\' list (i.e. the \"DirtyList\" attribute is not defined), then the renderer should call this with an empty <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\" title=\"This class is used to reference Softimage objects. Each instance of an CRef maintains a link with onl...\">CRef</a> object once the scene has been syncrhonised. Any attempts to clear out individual items with a \"full\" list will otherwise result in a \"full\" list still being given on next render. It is up to the renderer in this case to keep a map of which objects it has synchronised with, perhaps using the \"RenderID\" attribute to associate a synchronisation map with the current render.</dd></dl>\n\
<dl class=\"section user\"><dt>Note:</dt><dd>If an object was changed by the user during the Process callback, it will show up in the next call, whether it got marked clean or not. </dd></dl>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>The object to mark as clean and remove from the dirty list for the next call to the <a href=\"#!/url=./files/cb_Renderer_Process.htm\">Process</a> callback. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>9.0 (2011) </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__renderercontext_8h_source.html\">xsi_renderercontext.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";