var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>ClipEffect Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1ClipEffect.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>ClipEffect Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">ClipEffect Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__clipeffect_8h_source.html\">xsi_clipeffect.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>A ClipEffect represents the set of effects associated with a <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Clip.html\" title=\"Clips are instances of animation and shape actions (ActionSource), audio and image sources (Source) a...\">Clip</a>. Each ClipEffect object contains one item corresponding to a <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MappedItem.html\" title=\"A mapped item specifies the value driven by a specific clip instance (for example, an object&#39;s parameter or its geometry). \">MappedItem</a>. </p>\n\
<p>These ClipEffectItems contain expressions that control the clip without affecting the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Source.html\" title=\"Sources are references to data which are instantiated. For example, a shape source becomes a ShapeCli...\">Source</a> on which the clip was instantiated. For example, you can create a walk cycle with a progressive offset by using an expression similar to this:</p>\n\
<div class=\"fragment\"><div class=\"line\">(cid * 10) + <span class=\"keyword\">this</span> </div>\n\
</div><!-- fragment --><p>ClipEffects are available from the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Clip.html\" title=\"Clips are instances of animation and shape actions (ActionSource), audio and image sources (Source) a...\">Clip</a> object using <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Clip.html#ac34d2d933023a428d0b52a920d5d4f55\">Clip::GetEffect</a>.</p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Clip.html\" title=\"Clips are instances of animation and shape actions (ActionSource), audio and image sources (Source) a...\">Clip</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MappedItem.html#a91a5821e9d841a73c61689fb4311af9e\">MappedItem::GetClipEffectItem</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html\" title=\"A ClipEffectItem is an expression which is bound to a MappedItem of a Clip. \">ClipEffectItem</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Clip.html#ac34d2d933023a428d0b52a920d5d4f55\">Clip::GetEffect</a>, <a href=\"#!/url=./files/GetMappingRule.htm\">GetMappingRule</a>, <a href=\"#!/url=./files/SetMappingRule.htm\">SetMappingRule</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>4.0</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd>Demonstrates how to use MappedItems to look for a specific animation channel. Once this channel is found a clip effect is added onto it.</dd></dl>\n\
<div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a90b73ddc91605180a7d1ea4fa22014bf\">GetActiveSceneRoot</a>();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> myCube;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a0aa53709fda0b1b3de1cbdbfcd65445e\">AddGeometry</a>( L<span class=\"stringliteral\">&quot;Cube&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, myCube );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">//Creating the first animation source</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> args(9);</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>      outArg;</div>\n\
<div class=\"line\">args[0] = root;</div>\n\
<div class=\"line\">args[1] = L<span class=\"stringliteral\">&quot;cube.kine.local.posx,cube.kine.local.posy,cube.kine.local.posz&quot;</span>;</div>\n\
<div class=\"line\">args[2] = 1l;</div>\n\
<div class=\"line\">args[3] = L<span class=\"stringliteral\">&quot;StoredStaticPose&quot;</span>;</div>\n\
<div class=\"line\">args[4] = <span class=\"keyword\">true</span>;</div>\n\
<div class=\"line\">args[5] = 1l;</div>\n\
<div class=\"line\">args[6] = 5l;</div>\n\
<div class=\"line\">args[7] = <span class=\"keyword\">false</span>;</div>\n\
<div class=\"line\">args[8] = <span class=\"keyword\">false</span>;</div>\n\
<div class=\"line\">app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#afc4c4950c4f26c6fdd977c8058cf000b\">ExecuteCommand</a>( L<span class=\"stringliteral\">&quot;StoreAction&quot;</span>, args, outArg );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Source.html\">Source</a> mySource(outArg);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">//Creating the first clip</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> addClipArgs(6);</div>\n\
<div class=\"line\">addClipArgs[0] = root;</div>\n\
<div class=\"line\">addClipArgs[1] = mySource.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">addClipArgs[5] = L<span class=\"stringliteral\">&quot;MyClip1&quot;</span>;</div>\n\
<div class=\"line\">app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#afc4c4950c4f26c6fdd977c8058cf000b\">ExecuteCommand</a>( L<span class=\"stringliteral\">&quot;AddClip&quot;</span>, addClipArgs, outArg );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Clip.html\">Clip</a> myClip(outArg);</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> mappedItems = myClip.GetMappedItems();</div>\n\
<div class=\"line\"><span class=\"comment\">// Find the mapped item on which we wan&#39;t to add an effect.</span></div>\n\
<div class=\"line\"><span class=\"comment\">// We are looking for the local.posy parameter</span></div>\n\
<div class=\"line\">LONG i;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MappedItem.html\">MappedItem</a> currItem;</div>\n\
<div class=\"line\"><span class=\"keywordflow\">for</span>(i = 0; i &lt; mappedItems.GetCount(); ++i)</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    currItem = mappedItems[i];</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> param = currItem.GetDestination();</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">if</span>(param.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>().<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html#a2b91b77a2df26d55590f6a560ec3e6e2\">IsEqualNoCase</a>(L<span class=\"stringliteral\">&quot;cube.kine.local.posy&quot;</span>))</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> mappingRuleArgs(4);</div>\n\
<div class=\"line\">        mappingRuleArgs[0] = myClip.GetFullName() + L<span class=\"stringliteral\">&quot;.ActionClip&quot;</span>;</div>\n\
<div class=\"line\">        mappingRuleArgs[1] = param;</div>\n\
<div class=\"line\">        mappingRuleArgs[2] = L<span class=\"stringliteral\">&quot;frame&quot;</span>;</div>\n\
<div class=\"line\">        mappingRuleArgs[3] = (LONG)(i + 1);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">        app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#afc4c4950c4f26c6fdd977c8058cf000b\">ExecuteCommand</a>(L<span class=\"stringliteral\">&quot;SetMappingRule&quot;</span>, mappingRuleArgs, outArg);</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">break</span>;</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\">}</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html\">ClipEffectItem</a> effectItem(currItem.GetClipEffectItem());</div>\n\
<div class=\"line\">app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>(L<span class=\"stringliteral\">&quot;The expression associated with the posy item is &gt;&gt; &quot;</span> +</div>\n\
<div class=\"line\">                effectItem.GetExpression());</div>\n\
</div><!-- fragment --><dl class=\"section user\"><dt>Example:</dt><dd>Illustrates how to get at the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\" title=\"A ClipEffect represents the set of effects associated with a Clip. Each ClipEffect object contains on...\">ClipEffect</a> objects by creating some sources and clips with clip effects and then finding them again through the mapped items on the clips in the mixer.</dd></dl>\n\
<div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Forward declarations</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> GetRelativeNameForTarget( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a>&amp; in_param );</div>\n\
<div class=\"line\"><span class=\"keywordtype\">void</span> CreateStaticSource();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// NewScene command</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> cargs; <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> oarg;</div>\n\
<div class=\"line\">cargs.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html#ad7037428643c3f712e1887f8b7db9ede\">Add</a>( L<span class=\"stringliteral\">&quot;&quot;</span> ); cargs.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html#ad7037428643c3f712e1887f8b7db9ede\">Add</a>( <span class=\"keyword\">false</span> );</div>\n\
<div class=\"line\">app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#afc4c4950c4f26c6fdd977c8058cf000b\">ExecuteCommand</a>( L<span class=\"stringliteral\">&quot;NewScene&quot;</span>, cargs, oarg );</div>\n\
<div class=\"line\">cargs.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html#af91f0dee1a2a4d9fb7c8c3bc827199b7\">Clear</a>(); oarg.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html#aa71d36872f416feaa853788a7a7a7ef8\">Clear</a>();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Set up the scene</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a90b73ddc91605180a7d1ea4fa22014bf\">GetActiveSceneRoot</a>();</div>\n\
<div class=\"line\">CreateStaticSource();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Get all the clips in the mixer and then the sources</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Mixer.html\">Mixer</a> mix = root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html#a7b2c9dda644abd344a3347a99adb7a8c\">GetMixer</a>();</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> cliplist = mix.GetClips();</div>\n\
<div class=\"line\"><span class=\"keywordflow\">for</span> ( LONG i=0; i&lt;cliplist.GetCount(); ++i ) {</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Clip.html\">Clip</a> clp( cliplist[i] );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// Look at their mapped items, but avoid the audio clips</span></div>\n\
<div class=\"line\">    <span class=\"keywordflow\">if</span> ( clp.GetType() != <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a8b9938fcc76c3e61a009549d20ead942\">siClipAudioType</a> ) {</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> mappings = clp.GetMappedItems();</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">if</span> ( mappings.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a1d57f75f79e9178bdd17e38a23720d56\">IsValid</a>() ) {</div>\n\
<div class=\"line\">            app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>( L<span class=\"stringliteral\">&quot;Found &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(mappings.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a922e4c0f3b9c356806a07bd1f1b34736\">GetCount</a>()) + L<span class=\"stringliteral\">&quot; mapped items(s)&quot;</span> );</div>\n\
<div class=\"line\">            <span class=\"keywordflow\">for</span> ( LONG j=0; j&lt;mappings.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a922e4c0f3b9c356806a07bd1f1b34736\">GetCount</a>(); j++ ) {</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MappedItem.html\">MappedItem</a> mapitem( mappings[j] );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">                <span class=\"comment\">// Each item on the clip effect may have an expression that controls</span></div>\n\
<div class=\"line\">                <span class=\"comment\">// its behavior independently of the original source</span></div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html\">ClipEffectItem</a> clpfxitem = mapitem.GetClipEffectItem();</div>\n\
<div class=\"line\">                <span class=\"keywordflow\">if</span> ( clpfxitem.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html#a4a1c602b820b399e80f31f34d99cfa4a\">GetExpression</a>() != L<span class=\"stringliteral\">&quot;&quot;</span> ) {</div>\n\
<div class=\"line\">                    app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>( L<span class=\"stringliteral\">&quot;...this clip has a clip effect item matching this expression:&quot;</span> );</div>\n\
<div class=\"line\">                    app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>( L<span class=\"stringliteral\">&quot;   &quot;</span> + clpfxitem.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html#a4a1c602b820b399e80f31f34d99cfa4a\">GetExpression</a>() );</div>\n\
<div class=\"line\">                }</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">                <span class=\"comment\">// The mapped item also provides access to the driven parameter</span></div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> dest( mapitem.GetDestination() );</div>\n\
<div class=\"line\">                app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>( L<span class=\"stringliteral\">&quot;...destination parameter: &quot;</span> + dest.GetFullName() );</div>\n\
<div class=\"line\">            }</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\">}</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Expected Results:</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : Found 3 mapped items(s)</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : ...destination parameter: MyNull.kine.local.posx</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : ...destination parameter: MyNull.kine.local.posy</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : ...destination parameter: MyNull.kine.local.posy</span></div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// This is a handy function to have around if you&#39;re going to create an action</span></div>\n\
<div class=\"line\"><span class=\"comment\">// source or clip on a parameter that is in a nested model (ie., not directly</span></div>\n\
<div class=\"line\"><span class=\"comment\">// under the Scene_Root) because AddClip will force a mapping template if your</span></div>\n\
<div class=\"line\"><span class=\"comment\">// parameter is not relative.</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> GetRelativeNameForTarget( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a>&amp; in_param )</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> mdl = in_param.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html#ae429c84a91fc15fde31299798f45991f\">GetModel</a>();</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> mdlname = mdl.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">if</span> ( mdlname.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html#a2b91b77a2df26d55590f6a560ec3e6e2\">IsEqualNoCase</a>(L<span class=\"stringliteral\">&quot;Scene_Root&quot;</span>) ) {</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">return</span> in_param.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">    } <span class=\"keywordflow\">else</span> {</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> tmp = in_param.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> lookfor = mdlname + L<span class=\"stringliteral\">&quot;.&quot;</span>;</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> foundsofar = L<span class=\"stringliteral\">&quot;&quot;</span>;</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> relpath = L<span class=\"stringliteral\">&quot;&quot;</span>;</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">for</span> ( ULONG i=0; i&lt;tmp.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html#a8c3b193c06f950b092b7d1ca4db05e57\">Length</a>(); ++i ) {</div>\n\
<div class=\"line\">            <span class=\"keywordflow\">if</span> ( foundsofar.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html#a2b91b77a2df26d55590f6a560ec3e6e2\">IsEqualNoCase</a>(lookfor) ) {</div>\n\
<div class=\"line\">                relpath += tmp[i];</div>\n\
<div class=\"line\">            } <span class=\"keywordflow\">else</span> {</div>\n\
<div class=\"line\">                foundsofar += tmp[i];</div>\n\
<div class=\"line\">            }</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">return</span> relpath;</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\">}</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Convenience function</span></div>\n\
<div class=\"line\"><span class=\"keywordtype\">void</span> CreateStaticSource()</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// Get the SceneRoot and create a cone in it</span></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a90b73ddc91605180a7d1ea4fa22014bf\">GetActiveSceneRoot</a>();</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Null.html\">Null</a> n; root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a6d0f62914e9b6704e378909952c7e6c7\">AddNull</a>( L<span class=\"stringliteral\">&quot;MyNull&quot;</span>, n );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// Get the parameters to use as targets</span></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> posx = n.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ProjectItem.html#af3b309de51f722acd2de5735c661d7a9\">GetParameter</a>( L<span class=\"stringliteral\">&quot;posx&quot;</span> ); <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> rposx = GetRelativeNameForTarget( posx );</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> posy = n.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ProjectItem.html#af3b309de51f722acd2de5735c661d7a9\">GetParameter</a>( L<span class=\"stringliteral\">&quot;posy&quot;</span> ); <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> rposy = GetRelativeNameForTarget( posy );</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> posz = n.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ProjectItem.html#af3b309de51f722acd2de5735c661d7a9\">GetParameter</a>( L<span class=\"stringliteral\">&quot;posz&quot;</span> ); <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> rposz = GetRelativeNameForTarget( posz );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// Create a stored static pose</span></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ActionSource.html\">ActionSource</a> src = root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html#a3c7d1f86776dcd13e5b0357fd92e2741\">AddActionSource</a>( L<span class=\"stringliteral\">&quot;StoredStaticPose&quot;</span> );</div>\n\
<div class=\"line\">    src.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ActionSource.html#a2eeb928209f362fb9016d060907701e7\">AddSourceItem</a>( rposx, 5.5743, <span class=\"keyword\">true</span> );</div>\n\
<div class=\"line\">    src.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ActionSource.html#a2eeb928209f362fb9016d060907701e7\">AddSourceItem</a>( rposy, 0.1953, <span class=\"keyword\">true</span> );</div>\n\
<div class=\"line\">    src.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ActionSource.html#a2eeb928209f362fb9016d060907701e7\">AddSourceItem</a>( rposy, -0.0195, <span class=\"keyword\">true</span> );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// Instantiate it in the mixer</span></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> clpArgs(9); <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> clpOut;</div>\n\
<div class=\"line\">    clpArgs[0] = root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">    clpArgs[1] = src.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">    clpArgs[4] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(4.0);                          <span class=\"comment\">// starts at frame 4</span></div>\n\
<div class=\"line\">    app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#afc4c4950c4f26c6fdd977c8058cf000b\">ExecuteCommand</a>( L<span class=\"stringliteral\">&quot;AddClip&quot;</span>, clpArgs, clpOut );</div>\n\
<div class=\"line\">}</div>\n\
</div><!-- fragment --> </div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"closed.png\" alt=\"+\"> Inheritance diagram for ClipEffect:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"classXSI_1_1ClipEffect.png\" usemap=\"#ClipEffect_map\" alt=\"\">\n\
  <map id=\"ClipEffect_map\" name=\"ClipEffect_map\">\n\
<area href=\"classXSI_1_1SIObject.html\" title=\"SIObject derives from CBase and acts as the base class for the Softimage Object Model library...\" alt=\"SIObject\" shape=\"rect\" coords=\"0,56,67,80\">\n\
<area href=\"classXSI_1_1CBase.html\" title=\"CBase is the base class of all API classes and provides access to Softimage objects through generic C...\" alt=\"CBase\" shape=\"rect\" coords=\"0,0,67,24\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a2990eaa3130c60deb120ea8f143b6b70\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a2990eaa3130c60deb120ea8f143b6b70\">ClipEffect</a> ()</td></tr>\n\
<tr class=\"separator:a2990eaa3130c60deb120ea8f143b6b70\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a03b45a3377d7239707e517fd77724558\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a03b45a3377d7239707e517fd77724558\">~ClipEffect</a> ()</td></tr>\n\
<tr class=\"separator:a03b45a3377d7239707e517fd77724558\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af504cca85a37ea09e54a050b3b4e66bb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#af504cca85a37ea09e54a050b3b4e66bb\">ClipEffect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:af504cca85a37ea09e54a050b3b4e66bb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a79638f5b13f1503b31238b25e2bc3a07\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a79638f5b13f1503b31238b25e2bc3a07\">ClipEffect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a79638f5b13f1503b31238b25e2bc3a07\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa4d670d225cc455242155fa752e46f8e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#aa4d670d225cc455242155fa752e46f8e\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:aa4d670d225cc455242155fa752e46f8e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa82dce3aa72596259bf4c1964efef2e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#afa82dce3aa72596259bf4c1964efef2e\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:afa82dce3aa72596259bf4c1964efef2e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a964400efa039786d6a4fc6ca3d76a5c5\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a964400efa039786d6a4fc6ca3d76a5c5\">GetItems</a> () const </td></tr>\n\
<tr class=\"separator:a964400efa039786d6a4fc6ca3d76a5c5\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab9533e85e3ee84a3598c834c8a5e84cf\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CParameterRefArray.html\">CParameterRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#ab9533e85e3ee84a3598c834c8a5e84cf\">GetVariables</a> () const </td></tr>\n\
<tr class=\"separator:ab9533e85e3ee84a3598c834c8a5e84cf\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a74c3f0c6db83f30ca49291187c1db7f3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a74c3f0c6db83f30ca49291187c1db7f3\">GetIsActive</a> () const </td></tr>\n\
<tr class=\"separator:a74c3f0c6db83f30ca49291187c1db7f3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4779201582964bfcd53427e71e681ea2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a4779201582964bfcd53427e71e681ea2\">GetPoseIsActive</a> () const </td></tr>\n\
<tr class=\"separator:a4779201582964bfcd53427e71e681ea2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a76d09709ad6f2d5eaec73e91661e452e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a26db45cbff7ec682576c2f845adfeef4\">siTimeReferenceType</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a76d09709ad6f2d5eaec73e91661e452e\">GetTimeReference</a> () const </td></tr>\n\
<tr class=\"separator:a76d09709ad6f2d5eaec73e91661e452e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5d7b2c85823f5ef1e2db0e8c21fe6a45\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1StaticKinematicState.html\">StaticKinematicState</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html#a5d7b2c85823f5ef1e2db0e8c21fe6a45\">GetPoseEffect</a> () const </td></tr>\n\
<tr class=\"separator:a5d7b2c85823f5ef1e2db0e8c21fe6a45\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1SIObject\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1SIObject\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td></tr>\n\
<tr class=\"memitem:aa27dc882852af7ea1410aecde7a59fc2 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#aa27dc882852af7ea1410aecde7a59fc2\">SIObject</a> ()</td></tr>\n\
<tr class=\"separator:aa27dc882852af7ea1410aecde7a59fc2 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3019660a615dbe7cc0a9607a94b830a5 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a3019660a615dbe7cc0a9607a94b830a5\">~SIObject</a> ()</td></tr>\n\
<tr class=\"separator:a3019660a615dbe7cc0a9607a94b830a5 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a810fae9fad7bafe4ffb16df7083dfacd inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a810fae9fad7bafe4ffb16df7083dfacd\">SIObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a810fae9fad7bafe4ffb16df7083dfacd inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0e9d732eaeb68dfe6a43ccf68a06a132 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0e9d732eaeb68dfe6a43ccf68a06a132\">SIObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a0e9d732eaeb68dfe6a43ccf68a06a132 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a06a8a39f247c9826853433f5d87d6f48 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a06a8a39f247c9826853433f5d87d6f48\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a06a8a39f247c9826853433f5d87d6f48 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac699660f361bf8792b0249bc2f453ab4 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ac699660f361bf8792b0249bc2f453ab4\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:ac699660f361bf8792b0249bc2f453ab4 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a36cf1424d90dfdd72097f0959790d475 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a36cf1424d90dfdd72097f0959790d475\">GetApplication</a> () const </td></tr>\n\
<tr class=\"separator:a36cf1424d90dfdd72097f0959790d475 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab5e38bc9c650b2d8ca0abe29b516cf87 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a> () const </td></tr>\n\
<tr class=\"separator:ab5e38bc9c650b2d8ca0abe29b516cf87 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab5b36ddcfe22b04b0ca67b7be4f14f85 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5b36ddcfe22b04b0ca67b7be4f14f85\">GetName</a> () const </td></tr>\n\
<tr class=\"separator:ab5b36ddcfe22b04b0ca67b7be4f14f85 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afc968d8ce92392583fb64412ab3bed28 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#afc968d8ce92392583fb64412ab3bed28\">PutName</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_name)</td></tr>\n\
<tr class=\"separator:afc968d8ce92392583fb64412ab3bed28 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:addeb66825ef8aa3d36157a1959527f19 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#addeb66825ef8aa3d36157a1959527f19\">GetUniqueName</a> () const </td></tr>\n\
<tr class=\"separator:addeb66825ef8aa3d36157a1959527f19 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a327d1b55ff1e258417451a8a292c3c4f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a327d1b55ff1e258417451a8a292c3c4f\">GetType</a> () const </td></tr>\n\
<tr class=\"separator:a327d1b55ff1e258417451a8a292c3c4f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abc306e1a2d61cba72802d28f751aa640 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#abc306e1a2d61cba72802d28f751aa640\">GetParent</a> () const </td></tr>\n\
<tr class=\"separator:abc306e1a2d61cba72802d28f751aa640 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0d3dc111fd7156689b9b2c1fd2c5f581 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0d3dc111fd7156689b9b2c1fd2c5f581\">IsEqualTo</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:a0d3dc111fd7156689b9b2c1fd2c5f581 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8051b32ae9c745b35ded13029220080c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a8051b32ae9c745b35ded13029220080c\">GetHelp</a> () const </td></tr>\n\
<tr class=\"separator:a8051b32ae9c745b35ded13029220080c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a172c48e4a4d1341ea9002832a734c3ba inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a172c48e4a4d1341ea9002832a734c3ba\">GetOriginPath</a> () const </td></tr>\n\
<tr class=\"separator:a172c48e4a4d1341ea9002832a734c3ba inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab13f5aab4ca531714928a81bcea7b24c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a78f4f7bf0e1dcfc222ef5ccc055fc6af\">siInstallationPath</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab13f5aab4ca531714928a81bcea7b24c\">GetOrigin</a> () const </td></tr>\n\
<tr class=\"separator:ab13f5aab4ca531714928a81bcea7b24c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a53593f8cadffbaddd9245bbaa078eef6 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a53593f8cadffbaddd9245bbaa078eef6\">GetCategories</a> () const </td></tr>\n\
<tr class=\"separator:a53593f8cadffbaddd9245bbaa078eef6 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a86d8446a011274790e13534569a26b6f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a86d8446a011274790e13534569a26b6f\">GetNestedObjects</a> () const </td></tr>\n\
<tr class=\"separator:a86d8446a011274790e13534569a26b6f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1CBase\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1CBase\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td></tr>\n\
<tr class=\"memitem:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a3878f3ab13413eb6d4811dca38b4fa73\">CBase</a> ()</td></tr>\n\
<tr class=\"separator:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a012a4573399b53f0720fcf4ff787c048\">~CBase</a> ()</td></tr>\n\
<tr class=\"separator:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac347619969a79eb8afc0adf6ea9394ba\">GetClassIDName</a> () const </td></tr>\n\
<tr class=\"separator:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac8759bb33eaf8bf83949277169a048e6\">IsA</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a458e6e03ea0b71cb2205a5fd9e1999c8\">SetObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a> () const </td></tr>\n\
<tr class=\"separator:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac5a79b5ac1759bc4e66e8f662b8bad49\">ResetObject</a> ()</td></tr>\n\
<tr class=\"separator:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a20250592358718fccc1dad9e949d3d28\">operator CRef &amp;</a> ()</td></tr>\n\
<tr class=\"separator:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac91cdd4cb81fac44686c538126a4b98a\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a99049c404ae9b0ae189f80771dee0596\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#aac2a77c9ccdd6d0f9953ef784e2be5e9\">GetRef</a> () const </td></tr>\n\
<tr class=\"separator:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a2990eaa3130c60deb120ea8f143b6b70\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a03b45a3377d7239707e517fd77724558\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af504cca85a37ea09e54a050b3b4e66bb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant reference object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a79638f5b13f1503b31238b25e2bc3a07\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a6dd5a8a11eee55f434f151d1cd5d29d8\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool IsA </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_ClassID</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if a given class type is compatible with this API class. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ClassID</td><td>class type. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if the class is compatible, false otherwise. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a5a1833349ed14be553ae68b84ff60b8d\">CBase</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acc34f4a01f2089e40f7abc7e9d98bf15\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the type of the API class. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The class type. </dd></dl>\n\
\n\
<p>Implements <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a4b1359dd080cedb25e5f53df23d264b5\">CBase</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa4d670d225cc455242155fa752e46f8e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from another object. The newly created object is set to empty if the input object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\" title=\"A ClipEffect represents the set of effects associated with a Clip. Each ClipEffect object contains on...\">ClipEffect</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"afa82dce3aa72596259bf4c1964efef2e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\">ClipEffect</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from a reference object. The newly created object is set to empty if the input reference object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\" title=\"A ClipEffect represents the set of effects associated with a Clip. Each ClipEffect object contains on...\">ClipEffect</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a964400efa039786d6a4fc6ca3d76a5c5\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> GetItems </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns all items contained in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\" title=\"A ClipEffect represents the set of effects associated with a Clip. Each ClipEffect object contains on...\">ClipEffect</a>. There is one <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html\" title=\"A ClipEffectItem is an expression which is bound to a MappedItem of a Clip. \">ClipEffectItem</a> for every <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MappedItem.html\" title=\"A mapped item specifies the value driven by a specific clip instance (for example, an object&#39;s parameter or its geometry). \">MappedItem</a>. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of references to <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html\" title=\"A ClipEffectItem is an expression which is bound to a MappedItem of a Clip. \">ClipEffectItem</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab9533e85e3ee84a3598c834c8a5e84cf\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CParameterRefArray.html\">CParameterRefArray</a> GetVariables </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the parameters which are shared by all <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffectItem.html\" title=\"A ClipEffectItem is an expression which is bound to a MappedItem of a Clip. \">ClipEffectItem</a> objects. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of references to <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\" title=\"Represents a parameter value within the ProjectItem, for example, the angle parameter of the twist op...\">Parameter</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a74c3f0c6db83f30ca49291187c1db7f3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool GetIsActive </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\" title=\"A ClipEffect represents the set of effects associated with a Clip. Each ClipEffect object contains on...\">ClipEffect</a> will be computed in the clip evaluation. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>True if the effect is active, false otherwise. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4779201582964bfcd53427e71e681ea2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool GetPoseIsActive </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ClipEffect.html\" title=\"A ClipEffect represents the set of effects associated with a Clip. Each ClipEffect object contains on...\">ClipEffect</a> transformation effect is active. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>True if the effect is active, false otherwise. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a76d09709ad6f2d5eaec73e91661e452e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a26db45cbff7ec682576c2f845adfeef4\">siTimeReferenceType</a> GetTimeReference </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns either <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a26db45cbff7ec682576c2f845adfeef4a6b3550d0656cfecea9bf7ebb522af40f\">siOriginalClip</a> (the effect will repeat itself over time) or <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a26db45cbff7ec682576c2f845adfeef4ad3217c5ab44d6512a42838563e00251e\">siExtrapolatedClip</a> (the effect spans over extrapolation). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The time reference type (see the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a26db45cbff7ec682576c2f845adfeef4\">siTimeReferenceType</a> enum). </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a5d7b2c85823f5ef1e2db0e8c21fe6a45\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1StaticKinematicState.html\">StaticKinematicState</a> GetPoseEffect </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1StaticKinematicState.html\" title=\"The StaticKinematicState object represents the base pose of an object. Objects that have access to th...\">StaticKinematicState</a> property containing the transformation which is used for this clip effect. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1StaticKinematicState.html\" title=\"The StaticKinematicState object represents the base pose of an object. Objects that have access to th...\">StaticKinematicState</a> representing the transformation used. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__clipeffect_8h_source.html\">xsi_clipeffect.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";