var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CVector2f Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1MATH_1_1CVector2f.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CVector2f Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CVector2f Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__vector2f_8h_source.html\">xsi_vector2f.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>A 2-element vector represented by single floating point x,y coordinates. This class is typically used for implementing custom ICE nodes. </p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3f.html\" title=\"A 3-element vector that is represented by single floating point x,y,z coordinates. The class is used used for implementing custom ICE nodes. \">CVector3f</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector4f.html\" title=\"A 4-element vector that is represented by single floating point x,y,z coordinates. The class is used used for implementing custom ICE nodes. \">CVector4f</a> </dd></dl>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:aceed9e28c9d7a89fd6610377c89e8667\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#aceed9e28c9d7a89fd6610377c89e8667\">CVector2f</a> ()</td></tr>\n\
<tr class=\"separator:aceed9e28c9d7a89fd6610377c89e8667\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a50318462f62f9d797bb25655185f79a0\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a50318462f62f9d797bb25655185f79a0\">CVector2f</a> (float in_X, float in_Y)</td></tr>\n\
<tr class=\"separator:a50318462f62f9d797bb25655185f79a0\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8af8d4889e1b48a87438dd2b9e19bef4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a8af8d4889e1b48a87438dd2b9e19bef4\">CVector2f</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:a8af8d4889e1b48a87438dd2b9e19bef4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abdc62d8a13ed5cd9f2157a5198b42925\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#abdc62d8a13ed5cd9f2157a5198b42925\">~CVector2f</a> ()</td></tr>\n\
<tr class=\"separator:abdc62d8a13ed5cd9f2157a5198b42925\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1e0c5510d165282de1accba7c98c461f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a1e0c5510d165282de1accba7c98c461f\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:a1e0c5510d165282de1accba7c98c461f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a345b187c74fe052316e05c3ec7e480eb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a345b187c74fe052316e05c3ec7e480eb\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2) const </td></tr>\n\
<tr class=\"separator:a345b187c74fe052316e05c3ec7e480eb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a33f4a95243cb2ce2abd3f911446f4045\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a33f4a95243cb2ce2abd3f911446f4045\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2) const </td></tr>\n\
<tr class=\"separator:a33f4a95243cb2ce2abd3f911446f4045\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad9055ed0cad002c2f184083897bad9e5\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#ad9055ed0cad002c2f184083897bad9e5\">operator&lt;</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2) const </td></tr>\n\
<tr class=\"separator:ad9055ed0cad002c2f184083897bad9e5\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aefcdb20df53d3894e83edcaa021a7c89\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#aefcdb20df53d3894e83edcaa021a7c89\">operator~</a> ()</td></tr>\n\
<tr class=\"separator:aefcdb20df53d3894e83edcaa021a7c89\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a734fcc9a881bc6478bff53b8fc02bb4a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a734fcc9a881bc6478bff53b8fc02bb4a\">operator+=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:a734fcc9a881bc6478bff53b8fc02bb4a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a00e3d3ab783145b9131567e3b479e8a2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a00e3d3ab783145b9131567e3b479e8a2\">operator-=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:a00e3d3ab783145b9131567e3b479e8a2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7d93bd33095b670296d451b51f05d284\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a7d93bd33095b670296d451b51f05d284\">operator*=</a> (const float &amp;in_dAlpha)</td></tr>\n\
<tr class=\"separator:a7d93bd33095b670296d451b51f05d284\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4d8bde24f2c4b20363a4c56aaf02270a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a4d8bde24f2c4b20363a4c56aaf02270a\">SetNull</a> ()</td></tr>\n\
<tr class=\"separator:a4d8bde24f2c4b20363a4c56aaf02270a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5206b1111059d135c1f6c8ff3b727351\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a5206b1111059d135c1f6c8ff3b727351\">GetLength</a> () const </td></tr>\n\
<tr class=\"separator:a5206b1111059d135c1f6c8ff3b727351\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4b29638139c9e876d27e8cb4c7402318\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a4b29638139c9e876d27e8cb4c7402318\">GetLengthSquared</a> () const </td></tr>\n\
<tr class=\"separator:a4b29638139c9e876d27e8cb4c7402318\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac00487c1eaec058a6c2681f46c1ee972\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#ac00487c1eaec058a6c2681f46c1ee972\">Equals</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2) const </td></tr>\n\
<tr class=\"separator:ac00487c1eaec058a6c2681f46c1ee972\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abc3c39365c83b968ef3a113325397f81\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#abc3c39365c83b968ef3a113325397f81\">EpsilonEquals</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector, const float in_fEpsilon) const </td></tr>\n\
<tr class=\"separator:abc3c39365c83b968ef3a113325397f81\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aec7608136cebdb9265b1c844595c2c4e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#aec7608136cebdb9265b1c844595c2c4e\">ScaleAddInPlace</a> (float in_dS, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:aec7608136cebdb9265b1c844595c2c4e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a396ff111e737d7eb7541eb4eef63c839\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a396ff111e737d7eb7541eb4eef63c839\">ScaleAdd</a> (float in_dS, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector3A, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector3B)</td></tr>\n\
<tr class=\"separator:a396ff111e737d7eb7541eb4eef63c839\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a030923ec12b727d37b94cbe1a0dd8271\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a030923ec12b727d37b94cbe1a0dd8271\">ScaleInPlace</a> (float in_dAlpha)</td></tr>\n\
<tr class=\"separator:a030923ec12b727d37b94cbe1a0dd8271\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af5b5b4ad85885908aa93eccfaea726eb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#af5b5b4ad85885908aa93eccfaea726eb\">Scale</a> (float in_Alpha, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:af5b5b4ad85885908aa93eccfaea726eb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abd1b6c6bbb28f78953a4fa7e28a5730f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#abd1b6c6bbb28f78953a4fa7e28a5730f\">NegateInPlace</a> ()</td></tr>\n\
<tr class=\"separator:abd1b6c6bbb28f78953a4fa7e28a5730f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a832b7e938c8f1d0ddb068d3b8e5858cc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a832b7e938c8f1d0ddb068d3b8e5858cc\">Negate</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:a832b7e938c8f1d0ddb068d3b8e5858cc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0300aeddf823291e3690925095711fcd\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a0300aeddf823291e3690925095711fcd\">SubInPlace</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:a0300aeddf823291e3690925095711fcd\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af3e51a4877533f6a1986561032e181cb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#af3e51a4877533f6a1986561032e181cb\">Sub</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector3A, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector3B)</td></tr>\n\
<tr class=\"separator:af3e51a4877533f6a1986561032e181cb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab809c6d1ad0a31d7700cfeed53706577\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#ab809c6d1ad0a31d7700cfeed53706577\">AddInPlace</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector2)</td></tr>\n\
<tr class=\"separator:ab809c6d1ad0a31d7700cfeed53706577\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a59694af75bcafafc4593bb26ab2ec4a0\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a59694af75bcafafc4593bb26ab2ec4a0\">Add</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector3A, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;in_vector3B)</td></tr>\n\
<tr class=\"separator:a59694af75bcafafc4593bb26ab2ec4a0\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aff05bc6705b824185bcfd82a398620ac\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#aff05bc6705b824185bcfd82a398620ac\">GetY</a> () const </td></tr>\n\
<tr class=\"separator:aff05bc6705b824185bcfd82a398620ac\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0860eef6362a8c62789eca84ce38bbb5\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a0860eef6362a8c62789eca84ce38bbb5\">PutY</a> (float in_X)</td></tr>\n\
<tr class=\"separator:a0860eef6362a8c62789eca84ce38bbb5\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a60886eebdc9be71d5b2b5b940576cd35\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a60886eebdc9be71d5b2b5b940576cd35\">GetX</a> () const </td></tr>\n\
<tr class=\"separator:a60886eebdc9be71d5b2b5b940576cd35\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a05237d145f789515a76bb09ff3c86132\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a05237d145f789515a76bb09ff3c86132\">PutX</a> (float in_X)</td></tr>\n\
<tr class=\"separator:a05237d145f789515a76bb09ff3c86132\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"aceed9e28c9d7a89fd6610377c89e8667\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a50318462f62f9d797bb25655185f79a0\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_X</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_Y</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_X</td><td>Value of the x component </td></tr>\n\
    <tr><td class=\"paramname\">in_Y</td><td>Value of the y component </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8af8d4889e1b48a87438dd2b9e19bef4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abdc62d8a13ed5cd9f2157a5198b42925\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a1e0c5510d165282de1accba7c98c461f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Assignment operator. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a345b187c74fe052316e05c3ec7e480eb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator== </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Equality operator tests the strict equality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a> with the specified vector2. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#ac00487c1eaec058a6c2681f46c1ee972\">CVector2f::Equals</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a33f4a95243cb2ce2abd3f911446f4045\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator!= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Inequality operator tests the strict inequality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a> with the specified vector2. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#ac00487c1eaec058a6c2681f46c1ee972\">CVector2f::Equals</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad9055ed0cad002c2f184083897bad9e5\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator&lt; </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Less than operator. Performs a comparison with a specified <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a> to determine if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a> is less than the specified <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a>. The comparison is arbitrary and not geometrically meaningful, it\'s only purpose is to make <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a> compliant with stl for sorting operations. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a> to compare. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a> is less than the specified <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\" title=\"A 2-element vector represented by single floating point x,y coordinates. This class is typically used...\">CVector2f</a>, false otherwise. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>7.5 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aefcdb20df53d3894e83edcaa021a7c89\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; operator~ </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Negates this vector (this = - this). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#abd1b6c6bbb28f78953a4fa7e28a5730f\">CVector2f::NegateInPlace</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a734fcc9a881bc6478bff53b8fc02bb4a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; operator+= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Adds the input vector to this one (this = this + in_vector2) </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector.. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#ab809c6d1ad0a31d7700cfeed53706577\">CVector2f::AddInPlace</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a00e3d3ab783145b9131567e3b479e8a2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; operator-= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Subtracts the input vector (in_vector2) from this one (this = this - in_vector2). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a0300aeddf823291e3690925095711fcd\">CVector2f::SubInPlace</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7d93bd33095b670296d451b51f05d284\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; operator*= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_dAlpha</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Scales this vector by the input scalar (alpha) (this = alpha * this). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dAlpha</td><td>Scalar multiplicator. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html#a030923ec12b727d37b94cbe1a0dd8271\">CVector2f::ScaleInPlace</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4d8bde24f2c4b20363a4c56aaf02270a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; SetNull </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets this vector to a null vector. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a5206b1111059d135c1f6c8ff3b727351\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE float GetLength </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the length of this vector. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Length of this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4b29638139c9e876d27e8cb4c7402318\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE float GetLengthSquared </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the squared length of this vector. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Squared length of this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ac00487c1eaec058a6c2681f46c1ee972\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool Equals </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Tests the strict equality of this vector2 with the specified vector2. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abc3c39365c83b968ef3a113325397f81\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool EpsilonEquals </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const float&#160;</td>\n\
          <td class=\"paramname\"><em>in_fEpsilon</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Tests the equality of this vector with in_vector, with a tolerance of Epsilon. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector</td><td>Operand vector. </td></tr>\n\
    <tr><td class=\"paramname\">in_fEpsilon</td><td>Error margin <br>\n\
<b>Possible</b> <b>Values:</b> [0, +INF[ should be a positive value </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aec7608136cebdb9265b1c844595c2c4e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; ScaleAddInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_dS</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the value of this vector to the scalar multiplication of itself by s and then adds vector2 v. (this = s*this + v) </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dS</td><td>Scalar multiplicator. </td></tr>\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a396ff111e737d7eb7541eb4eef63c839\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; ScaleAdd </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_dS</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector3A</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector3B</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the value of this vector2 to the scalar multiplication of vector2 A by s and then adds vector2 B. (this = s*v1 + v2). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dS</td><td>Scalar multiplicator. </td></tr>\n\
    <tr><td class=\"paramname\">in_vector3A</td><td>Operand vector. </td></tr>\n\
    <tr><td class=\"paramname\">in_vector3B</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a030923ec12b727d37b94cbe1a0dd8271\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; ScaleInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_dAlpha</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Scales this vector by the input scalar (alpha) (this = alpha * this). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dAlpha</td><td>Scalar multiplicator. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af5b5b4ad85885908aa93eccfaea726eb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; Scale </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_Alpha</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Scales the input vector (v) by (alpha) store the result into this one (this = alpha * v). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_Alpha</td><td>Scalar multiplicator. </td></tr>\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abd1b6c6bbb28f78953a4fa7e28a5730f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; NegateInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Negates this vector (this = - this). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a832b7e938c8f1d0ddb068d3b8e5858cc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; Negate </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Negates the input vector (v) store the result into this one (this = - v). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0300aeddf823291e3690925095711fcd\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; SubInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Subtracts the input vector2 (v) from this one (this = this - v). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af3e51a4877533f6a1986561032e181cb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; Sub </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector3A</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector3B</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Subtracts the input vector2 (<code>in_vector3B</code>) from the input vector2 (<code>in_vector3A</code>) and stores the result in this one (<code>this = A - B</code>). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector3A</td><td>Operand vector. </td></tr>\n\
    <tr><td class=\"paramname\">in_vector3B</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab809c6d1ad0a31d7700cfeed53706577\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; AddInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector2</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Adds the input vector to this one (this = this + in_vector2). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector2</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a59694af75bcafafc4593bb26ab2ec4a0\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; Add </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector3A</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_vector3B</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Adds both input vectors and stores the result in this one. (this = A + B) </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_vector3A</td><td>Operand vector. </td></tr>\n\
    <tr><td class=\"paramname\">in_vector3B</td><td>Operand vector. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aff05bc6705b824185bcfd82a398620ac\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE float GetY </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the Y value of this vector. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Y value of this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0860eef6362a8c62789eca84ce38bbb5\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; PutY </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_X</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the Y value of this vector. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_X</td><td>y value. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a60886eebdc9be71d5b2b5b940576cd35\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE float GetX </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the X value of this vector. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>X value of this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a05237d145f789515a76bb09ff3c86132\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector2f.html\">CVector2f</a> &amp; PutX </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_X</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the X value of this vector. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_X</td><td>x value. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this vector. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__vector2f_8h_source.html\">xsi_vector2f.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";