var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CMatrix3 Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1MATH_1_1CMatrix3.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CMatrix3 Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CMatrix3 Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__matrix3_8h_source.html\">xsi_matrix3.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>This class represents a double precision floating point 3 by 3 matrix. </p>\n\
<dl class=\"section user\"><dt>Example:</dt><dd><div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI::MATH;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> mat3(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0);</div>\n\
<div class=\"line\">mat3.TransposeInPlace();</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\">app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;The transposed matrix is &quot;</span>) +</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(0,0)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(0,1)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(0,2)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(1,0)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(1,1)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(1,2)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(2,0)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(2,1)).GetAsText() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;, &quot;</span>)+</div>\n\
<div class=\"line\">               <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(mat3.GetValue(2,2)).GetAsText());</div>\n\
</div><!-- fragment --> </dd></dl>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:aafbc1380d1180108bd26267a3e04282b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#aafbc1380d1180108bd26267a3e04282b\">CMatrix3</a> ()</td></tr>\n\
<tr class=\"separator:aafbc1380d1180108bd26267a3e04282b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a60998deae35690b8034e15609b653284\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a60998deae35690b8034e15609b653284\">CMatrix3</a> (double in_d00, double in_d01, double in_d02, double in_d10, double in_d11, double in_d12, double in_d20, double in_d21, double in_d22)</td></tr>\n\
<tr class=\"separator:a60998deae35690b8034e15609b653284\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0b328eb7fc0197c2f25c038c14239211\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a0b328eb7fc0197c2f25c038c14239211\">CMatrix3</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a0b328eb7fc0197c2f25c038c14239211\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7ce3c3d0bec83dd194beace6a85967ba\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a7ce3c3d0bec83dd194beace6a85967ba\">~CMatrix3</a> ()</td></tr>\n\
<tr class=\"separator:a7ce3c3d0bec83dd194beace6a85967ba\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7b2ff185472683c4ac8a863263cd9857\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a7b2ff185472683c4ac8a863263cd9857\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a7b2ff185472683c4ac8a863263cd9857\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab449609d1d6f52fcb3f2b013f0906692\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#ab449609d1d6f52fcb3f2b013f0906692\">operator*=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:ab449609d1d6f52fcb3f2b013f0906692\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1ed84699ac4b741b6ad8bc4774dc84db\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">CVector3</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a1ed84699ac4b741b6ad8bc4774dc84db\">operator[]</a> (const short &amp;in_sIndex)</td></tr>\n\
<tr class=\"separator:a1ed84699ac4b741b6ad8bc4774dc84db\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3b50862712aeea7d6b48016ba5c25bae\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a3b50862712aeea7d6b48016ba5c25bae\">SetIdentity</a> ()</td></tr>\n\
<tr class=\"separator:a3b50862712aeea7d6b48016ba5c25bae\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1c08446a774f2afac9b3a718dc3194be\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a1c08446a774f2afac9b3a718dc3194be\">InvertInPlace</a> ()</td></tr>\n\
<tr class=\"separator:a1c08446a774f2afac9b3a718dc3194be\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a709b9ef89e32d7131cae20c55b3f6fc3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a709b9ef89e32d7131cae20c55b3f6fc3\">Invert</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a709b9ef89e32d7131cae20c55b3f6fc3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa380c3e9572445c6f435f727505a6608\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#aa380c3e9572445c6f435f727505a6608\">TransposeInverseInPlace</a> ()</td></tr>\n\
<tr class=\"separator:aa380c3e9572445c6f435f727505a6608\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af2d42652b36cc572ee2ce5832eef2423\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#af2d42652b36cc572ee2ce5832eef2423\">TransposeInverse</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:af2d42652b36cc572ee2ce5832eef2423\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abf33a1c0005458a7c27ca7b308c9787c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#abf33a1c0005458a7c27ca7b308c9787c\">TransposeInPlace</a> ()</td></tr>\n\
<tr class=\"separator:abf33a1c0005458a7c27ca7b308c9787c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a31eca736f1bfaeeb603b751abf15af0c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a31eca736f1bfaeeb603b751abf15af0c\">Transpose</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a31eca736f1bfaeeb603b751abf15af0c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0ed4cbfc5842f6b0f20a630800ff494e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a0ed4cbfc5842f6b0f20a630800ff494e\">MulInPlace</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a0ed4cbfc5842f6b0f20a630800ff494e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a94fbc8d4d8c773e62e2775273f675d95\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a94fbc8d4d8c773e62e2775273f675d95\">Mul</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3A, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3B)</td></tr>\n\
<tr class=\"separator:a94fbc8d4d8c773e62e2775273f675d95\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a41189ebcc342c5496910796ed7019733\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a41189ebcc342c5496910796ed7019733\">Get</a> (double &amp;io_d00, double &amp;io_d01, double &amp;io_d02, double &amp;io_d10, double &amp;io_d11, double &amp;io_d12, double &amp;io_d20, double &amp;io_d21, double &amp;io_d22) const </td></tr>\n\
<tr class=\"separator:a41189ebcc342c5496910796ed7019733\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aafe949b46e9a53ded98748f04590600c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#aafe949b46e9a53ded98748f04590600c\">Set</a> (double in_d00, double in_d01, double in_d02, double in_d10, double in_d11, double in_d12, double in_d20, double in_d21, double in_d22)</td></tr>\n\
<tr class=\"separator:aafe949b46e9a53ded98748f04590600c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3dc116f6d461cb29795e85ed9a5b06dc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a3dc116f6d461cb29795e85ed9a5b06dc\">Set</a> (const double in_dVal[3][3])</td></tr>\n\
<tr class=\"separator:a3dc116f6d461cb29795e85ed9a5b06dc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4e557292be88bd4051b64eef1f54a998\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE double&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a4e557292be88bd4051b64eef1f54a998\">GetValue</a> (short in_sRow, short in_sCol) const </td></tr>\n\
<tr class=\"separator:a4e557292be88bd4051b64eef1f54a998\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7c55f8d7711e9b007d8b2980830572c2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a7c55f8d7711e9b007d8b2980830572c2\">SetValue</a> (short in_sRow, short in_sCol, double in_dVal)</td></tr>\n\
<tr class=\"separator:a7c55f8d7711e9b007d8b2980830572c2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6cd3ae1d3d416003582f2fd2e9fc0c93\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a6cd3ae1d3d416003582f2fd2e9fc0c93\">SetFromQuaternion</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\">CQuaternion</a> &amp;in_quaternion)</td></tr>\n\
<tr class=\"separator:a6cd3ae1d3d416003582f2fd2e9fc0c93\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1d4f13bdd5bc8c43bdd97266d6bfee16\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\">CQuaternion</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a1d4f13bdd5bc8c43bdd97266d6bfee16\">GetQuaternion</a> (void) const </td></tr>\n\
<tr class=\"separator:a1d4f13bdd5bc8c43bdd97266d6bfee16\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aaee0d1e231a45b4cd292028768dc793d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#aaee0d1e231a45b4cd292028768dc793d\">EpsilonEquals</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3, double in_dEpsilon) const </td></tr>\n\
<tr class=\"separator:aaee0d1e231a45b4cd292028768dc793d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4d6b44cd0a2d1377656942cdecf2d87d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a4d6b44cd0a2d1377656942cdecf2d87d\">Equals</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3) const </td></tr>\n\
<tr class=\"separator:a4d6b44cd0a2d1377656942cdecf2d87d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a14533e8ce683f80484dfb8e30bea24db\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a14533e8ce683f80484dfb8e30bea24db\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3) const </td></tr>\n\
<tr class=\"separator:a14533e8ce683f80484dfb8e30bea24db\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae6871138a6947e13dfca48c4314073ff\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#ae6871138a6947e13dfca48c4314073ff\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;in_matrix3) const </td></tr>\n\
<tr class=\"separator:ae6871138a6947e13dfca48c4314073ff\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"aafbc1380d1180108bd26267a3e04282b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a60998deae35690b8034e15609b653284\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d00</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d01</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d02</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d10</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d11</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d12</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d20</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d21</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d22</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_d00</td><td>Value to set in this matrix[0,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d01</td><td>Value to set in this matrix[0,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d02</td><td>Value to set in this matrix[0,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d10</td><td>Value to set in this matrix[1,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d11</td><td>Value to set in this matrix[1,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d12</td><td>Value to set in this matrix[1,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d20</td><td>Value to set in this matrix[2,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d21</td><td>Value to set in this matrix[2,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d22</td><td>Value to set in this matrix[2,2]. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0b328eb7fc0197c2f25c038c14239211\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7ce3c3d0bec83dd194beace6a85967ba\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE ~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a7b2ff185472683c4ac8a863263cd9857\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Assignment operator. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3&amp;</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab449609d1d6f52fcb3f2b013f0906692\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp; operator*= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Right-multiplies this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object by the matrix m and stores the result in the same <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object (this = this . in_matrix3) </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>matrix to be multiplied with. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a0ed4cbfc5842f6b0f20a630800ff494e\">CMatrix3::MulInPlace</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1ed84699ac4b741b6ad8bc4774dc84db\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">CVector3</a>&amp; operator[] </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const short &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_sIndex</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Accesses a row of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_sIndex</td><td>0,1,2 for the row of the matrix. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\" title=\"A 3-element vector that is represented by double precision floating point x,y,z coordinates. \">CVector3</a> object. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html#a88dc6654c73f4826ef07bd00243ce4b1\">CVector3::operator[]</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3b50862712aeea7d6b48016ba5c25bae\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp; SetIdentity </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object to the identity matrix (this = id). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1c08446a774f2afac9b3a718dc3194be\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool InvertInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Inverts this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object (if not singular) (this = this^-1). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object has been inverted (not singular), else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a709b9ef89e32d7131cae20c55b3f6fc3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool Invert </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Inverts this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object (if not singular) (this = this^-1). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>matrix to be inverted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object has been inverted (not singular), else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa380c3e9572445c6f435f727505a6608\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool TransposeInverseInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object to the transpose of the inverse of itself (if not singular) (this = Transpose(this^-1)). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object has been inverted (not singular), else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af2d42652b36cc572ee2ce5832eef2423\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool TransposeInverse </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object to the transpose of the inverse of the input matrix (if not singular) (this = Transpose(in_matrix3^-1)). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object to be inversed and transposed. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object has been inverted (not singular), else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abf33a1c0005458a7c27ca7b308c9787c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void TransposeInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Transposes this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object in place (this = Transpose(this)). </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a31eca736f1bfaeeb603b751abf15af0c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Transpose </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Transposes the specified matrix and stores the result in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object (this = Transpose(in_matrix3)). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>matrix to be inversed and transposed. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0ed4cbfc5842f6b0f20a630800ff494e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp; MulInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Right-multiplies this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object by the matrix m and stores the result in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object (this = this . in_matrix3). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>matrix to be multiplied with. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a94fbc8d4d8c773e62e2775273f675d95\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp; Mul </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3A</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3B</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Right-multiplies the matrix A by the matrix B and stores the result in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object (this = in_matrix3A . in_matrix3B). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3A</td><td>matrix </td></tr>\n\
    <tr><td class=\"paramname\">in_matrix3B</td><td>matrix </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a>&amp; A reference to the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object which contains the result of the multiplication. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a41189ebcc342c5496910796ed7019733\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Get </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d00</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d01</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d02</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d10</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d11</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d12</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d20</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d21</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_d22</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the 9 components of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">io_d00</td><td>Value of this matrix[0,0]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d01</td><td>Value of this matrix[0,1]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d02</td><td>Value of this matrix[0,2]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d10</td><td>Value of this matrix[1,0]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d11</td><td>Value of this matrix[1,1]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d12</td><td>Value of this matrix[1,2]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d20</td><td>Value of this matrix[2,0]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d21</td><td>Value of this matrix[2,1]. </td></tr>\n\
    <tr><td class=\"paramname\">io_d22</td><td>Value of this matrix[2,2]. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aafe949b46e9a53ded98748f04590600c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Set </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d00</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d01</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d02</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d10</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d11</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d12</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d20</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d21</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_d22</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the 9 components of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_d00</td><td>Value to set to this matrix[0,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d01</td><td>Value to set to this matrix[0,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d02</td><td>Value to set to this matrix[0,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d10</td><td>Value to set to this matrix[1,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d11</td><td>Value to set to this matrix[1,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d12</td><td>Value to set to this matrix[1,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d20</td><td>Value to set to this matrix[2,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d21</td><td>Value to set to this matrix[2,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_d22</td><td>Value to set to this matrix[2,2]. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3dc116f6d461cb29795e85ed9a5b06dc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Set </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dVal</em>[3][3]</td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the 9 components of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dVal</td><td>A 3x3 array of double values. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4e557292be88bd4051b64eef1f54a998\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE double GetValue </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sRow</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sCol</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the (i,j)th value of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_sRow</td><td>access to the i th row </td></tr>\n\
    <tr><td class=\"paramname\">in_sCol</td><td>access to the j th column </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The (i,j)th value of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7c55f8d7711e9b007d8b2980830572c2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void SetValue </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sRow</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sCol</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dVal</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the (i,j)th value of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_sRow</td><td>access to the i th row </td></tr>\n\
    <tr><td class=\"paramname\">in_sCol</td><td>access to the j th column </td></tr>\n\
    <tr><td class=\"paramname\">in_dVal</td><td>new value </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a6cd3ae1d3d416003582f2fd2e9fc0c93\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a>&amp; SetFromQuaternion </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\">CQuaternion</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_quaternion</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object using rotation <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\" title=\"Implementation of a quaternion q=a+bi+cj+dk. \">CQuaternion</a>. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_quaternion</td><td>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\" title=\"Implementation of a quaternion q=a+bi+cj+dk. \">CQuaternion</a> containing the new matrix3 values </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1d4f13bdd5bc8c43bdd97266d6bfee16\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\">CQuaternion</a> GetQuaternion </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">void&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Gets the rotation <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\" title=\"Implementation of a quaternion q=a+bi+cj+dk. \">CQuaternion</a> representation of this matrix3. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Rotation <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CQuaternion.html\" title=\"Implementation of a quaternion q=a+bi+cj+dk. \">CQuaternion</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aaee0d1e231a45b4cd292028768dc793d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool EpsilonEquals </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dEpsilon</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Tests the equality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object with the specified matrix, with a tolerance of Epsilon. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix. </td></tr>\n\
    <tr><td class=\"paramname\">in_dEpsilon</td><td>Error margin Possible Values: [0, +INF[ should be a positive value </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4d6b44cd0a2d1377656942cdecf2d87d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool Equals </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Tests the strict equality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object with the specified matrix. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a14533e8ce683f80484dfb8e30bea24db\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator== </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Equality operator. Tests the strict equality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object with the specified matrix. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix3. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a4d6b44cd0a2d1377656942cdecf2d87d\">CMatrix3::Equals</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ae6871138a6947e13dfca48c4314073ff\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator!= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\">CMatrix3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Inequality operator. Tests the strict inequality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html\" title=\"This class represents a double precision floating point 3 by 3 matrix. \">CMatrix3</a> object with the specified matrix. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3.html#a4d6b44cd0a2d1377656942cdecf2d87d\">CMatrix3::Equals</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__matrix3_8h_source.html\">xsi_matrix3.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";