var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CDataArray2D&lt; T &gt;::Accessor Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1CDataArray2D_1_1Accessor.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CDataArray2D&lt; T &gt;::Accessor Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CDataArray2D&lt; T &gt;::Accessor Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__dataarray2D_8h_source.html\">xsi_dataarray2D.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><h3>template&lt;class T&gt;<br>\n\
class XSI::CDataArray2D&lt; T &gt;::Accessor</h3>\n\
\n\
<p>A class for accessing the sub-array data of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D.html\" title=\"This template class encapsulates 2D data arrays that are passed to custom node plug-ins during a grap...\">CDataArray2D</a> objects. </p>\n\
<dl class=\"section since\"><dt>Since</dt><dd>7.0 </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CIndexSet.html\" title=\"CIndexSet encapsulates an index set for indexing CDataArray object types for the current evaluation...\">CIndexSet</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray.html\" title=\"This template class encapsulates the 1D data arrays passed to custom node plug-ins during a graph eva...\">CDataArray</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D.html\" title=\"This template class encapsulates 2D data arrays that are passed to custom node plug-ins during a grap...\">CDataArray2D</a> </dd></dl>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:afb09f444d90862bcf8d72bd7684d73bf\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#afb09f444d90862bcf8d72bd7684d73bf\">Accessor</a> ()</td></tr>\n\
<tr class=\"separator:afb09f444d90862bcf8d72bd7684d73bf\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab610f7161f4077b1d789991a1aaf1b1d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#ab610f7161f4077b1d789991a1aaf1b1d\">Accessor</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a> &amp;in_accessor)</td></tr>\n\
<tr class=\"separator:ab610f7161f4077b1d789991a1aaf1b1d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:adee49fe6a6e95cd6dd89113f76921a56\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#adee49fe6a6e95cd6dd89113f76921a56\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a> &amp;in_accessor)</td></tr>\n\
<tr class=\"separator:adee49fe6a6e95cd6dd89113f76921a56\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aaf99ae62191d421f6b41f34092e683e2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">ULONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#aaf99ae62191d421f6b41f34092e683e2\">GetCount</a> () const </td></tr>\n\
<tr class=\"separator:aaf99ae62191d421f6b41f34092e683e2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afec5eefe5a8c5f4d3a43d13bded7e7fc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const T &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#afec5eefe5a8c5f4d3a43d13bded7e7fc\">operator[]</a> (ULONG in_nIndex) const </td></tr>\n\
<tr class=\"separator:afec5eefe5a8c5f4d3a43d13bded7e7fc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7f186e29bf49fdb07be00391418292da\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">T &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#a7f186e29bf49fdb07be00391418292da\">operator[]</a> (ULONG in_nIndex)</td></tr>\n\
<tr class=\"separator:a7f186e29bf49fdb07be00391418292da\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"afb09f444d90862bcf8d72bd7684d73bf\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab610f7161f4077b1d789991a1aaf1b1d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_accessor</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructs an Accessor object from another Accessor object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_accessor</td><td>constant Accessor object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"adee49fe6a6e95cd6dd89113f76921a56\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">Accessor</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_accessor</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Assignment operator. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_accessor</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this Accessor. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aaf99ae62191d421f6b41f34092e683e2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">ULONG GetCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">void&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the number of elements in the array. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Number of elements. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"afec5eefe5a8c5f4d3a43d13bded7e7fc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">const T&amp; operator[] </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">ULONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIndex</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Accessor to elements at a given index. This operator is called when reading the data so the return value is read-only. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIndex</td><td>Index in the array. The index must be smaller than the number of elements in the array, otherwise the results are unpredicted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A read-only reference to the indexed item. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7f186e29bf49fdb07be00391418292da\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">T&amp; operator[] </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">ULONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIndex</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Accessor to elements at a given index. This operator can also be used to access and modify the sub-array stored at the in_nIndex position. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIndex</td><td>Index in this zero-based array. The index must be smaller than the number of elements in the array, otherwise the results are unpredicted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to the indexed item.</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd><div class=\"fragment\"><div class=\"line\"><span class=\"comment\">// Demonstrates how to access/modify the CDataArray2D&lt;T&gt; sub-arrays from the CDataArray2D&lt;T&gt;::Accessor class.</span></div>\n\
<div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">XSIPLUGINCALLBACK <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> UnionArrayNode_Evaluate( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ICENodeContext.html\">ICENodeContext</a>&amp; in_ctxt )</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    <span class=\"comment\">// The current output port being evaluated...</span></div>\n\
<div class=\"line\">    ULONG out_portID = in_ctxt.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ICENodeContext.html#a7ea5c9f40651741e896890b5b9cb7e08\">GetEvaluatedOutputPortID</a>( );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"keywordflow\">switch</span>( out_portID )</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">case</span> ID_OUT_result:</div>\n\
<div class=\"line\">        {</div>\n\
<div class=\"line\">            <span class=\"comment\">// Get the output port array ...</span></div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D.html\">CDataArray2DLong</a> outData( in_ctxt );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">            <span class=\"comment\">// Get the input data buffers for each port</span></div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D.html\">CDataArray2DLong</a> InArray1Data( in_ctxt, ID_IN_InArray1 );</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D.html\">CDataArray2DLong</a> InArray2Data( in_ctxt, ID_IN_InArray2 );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">            <span class=\"comment\">// We need a CIndexSet to iterate over the data</span></div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CIndexSet.html\">CIndexSet</a> indexSet( in_ctxt );</div>\n\
<div class=\"line\">            <span class=\"keywordflow\">for</span>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CIndexSet_1_1Iterator.html\">CIndexSet::Iterator</a> it = indexSet.Begin(); it.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CIndexSet_1_1Iterator.html#a1f00a3daad37178257564e4817b69d40\">HasNext</a>(); it.Next())</div>\n\
<div class=\"line\">            {</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">CDataArray2DLong::Accessor</a> a1 = InArray1Data[it];</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">CDataArray2DLong::Accessor</a> a2 = InArray2Data[it];</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">                <span class=\"comment\">// Sort arrays in place</span></div>\n\
<div class=\"line\">                ULONG nCount1 = a1.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#aaf99ae62191d421f6b41f34092e683e2\">GetCount</a>();</div>\n\
<div class=\"line\">                ULONG nCount2 = a2.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html#aaf99ae62191d421f6b41f34092e683e2\">GetCount</a>();</div>\n\
<div class=\"line\">                std::sort( &amp;a1[0], &amp;a1[0]+nCount1 );</div>\n\
<div class=\"line\">                std::sort( &amp;a2[0], &amp;a2[0]+nCount2 );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">                <span class=\"comment\">// Resize out to max array</span></div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CDataArray2D_1_1Accessor.html\">CDataArray2DLong::Accessor</a> out = outData.Resize( it, nCount1 + nCount2 );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">                <span class=\"comment\">// Union of a1 + a2</span></div>\n\
<div class=\"line\">                LONG* pLast = std::set_union( &amp;a1[0], &amp;a1[0]+nCount1, &amp;a2[0], &amp;a2[0]+nCount2, &amp;out[0]);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">                <span class=\"comment\">// resize out with number of elements in union</span></div>\n\
<div class=\"line\">                ULONG nOutCount = (ULONG)(pLast - &amp;out[0]);</div>\n\
<div class=\"line\">                outData.Resize( it, nOutCount );</div>\n\
<div class=\"line\">            }</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">break</span>;</div>\n\
<div class=\"line\">    };</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a>;</div>\n\
<div class=\"line\">}</div>\n\
</div><!-- fragment --> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__dataarray2D_8h_source.html\">xsi_dataarray2D.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";