var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><meta name=\"robots\" content=\"noindex, follow\"><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>Member List</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1PolygonNode-members.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>Member List</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">PolygonNode Member List</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p>This is the complete list of members for <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a>, including all inherited members.</p>\n\
<table class=\"directory\">\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a3878f3ab13413eb6d4811dca38b4fa73\">CBase</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a36cf1424d90dfdd72097f0959790d475\">GetApplication</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a53593f8cadffbaddd9245bbaa078eef6\">GetCategories</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"><span class=\"mlabel\">virtual</span></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac347619969a79eb8afc0adf6ea9394ba\">GetClassIDName</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a8051b32ae9c745b35ded13029220080c\">GetHelp</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#a3993d8a3481950823a84c8845773d366\">GetIndex</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5b36ddcfe22b04b0ca67b7be4f14f85\">GetName</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a86d8446a011274790e13534569a26b6f\">GetNestedObjects</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#a38bbd5b95d8182fc5821837620e528f7\">GetNormal</a>(bool &amp;io_bValid) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab13f5aab4ca531714928a81bcea7b24c\">GetOrigin</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a172c48e4a4d1341ea9002832a734c3ba\">GetOriginPath</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#abc306e1a2d61cba72802d28f751aa640\">GetParent</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#aac2a77c9ccdd6d0f9953ef784e2be5e9\">GetRef</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html#a975ed2daa5104b0cbf5d4d58a0ca5e4d\">GetSubComponent</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html\">Sample</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a327d1b55ff1e258417451a8a292c3c4f\">GetType</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#addeb66825ef8aa3d36157a1959527f19\">GetUniqueName</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a>(siClassID in_ClassID) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"><span class=\"mlabel\">virtual</span></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac8759bb33eaf8bf83949277169a048e6\">XSI::CBase::IsA</a>(const CRef &amp;in_ref) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0d3dc111fd7156689b9b2c1fd2c5f581\">IsEqualTo</a>(const CRef &amp;in_ref) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html#a025ade69a7eb9796802821a66b14796d\">Navigate</a>(siNavigateComponentType in_siNavigate) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html\">Sample</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a20250592358718fccc1dad9e949d3d28\">operator CRef &amp;</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a99049c404ae9b0ae189f80771dee0596\">operator!=</a>(const CBase &amp;in_obj) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#a0a36786609915dbc57986ff2d0a69a9b\">operator=</a>(const PolygonNode &amp;in_obj)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#a2c779c8aa26ac465fb513781c2307a4d\">operator=</a>(const CRef &amp;in_ref)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html#ac82ef24b38468f721f2b0c06596c1a54\">XSI::Sample::operator=</a>(const Sample &amp;in_obj)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html\">Sample</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a06a8a39f247c9826853433f5d87d6f48\">XSI::SIObject::operator=</a>(const SIObject &amp;in_obj)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac91cdd4cb81fac44686c538126a4b98a\">operator==</a>(const CBase &amp;in_obj) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#aac2c5b63f4ec9fa2e5a11242a0681b69\">PolygonNode</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#a033ab5b410aedba453b0a729695c324a\">PolygonNode</a>(const CRef &amp;in_ref)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#adcc87e1a84af981cc06c86784e381fda\">PolygonNode</a>(const PolygonNode &amp;in_obj)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#afc968d8ce92392583fb64412ab3bed28\">PutName</a>(const CString &amp;in_name)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac5a79b5ac1759bc4e66e8f662b8bad49\">ResetObject</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html#af338d729c459654963a511ac9f383db4\">Sample</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html\">Sample</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html#a564c186e5a95e526a68c11eef5852d32\">Sample</a>(const CRef &amp;in_ref)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html\">Sample</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html#aa9cc60a151e1df28b7692410ff5d095e\">Sample</a>(const Sample &amp;in_obj)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html\">Sample</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a458e6e03ea0b71cb2205a5fd9e1999c8\">SetObject</a>(const CRef &amp;in_obj)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#aa27dc882852af7ea1410aecde7a59fc2\">SIObject</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a810fae9fad7bafe4ffb16df7083dfacd\">SIObject</a>(const CRef &amp;in_ref)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0e9d732eaeb68dfe6a43ccf68a06a132\">SIObject</a>(const SIObject &amp;in_obj)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a012a4573399b53f0720fcf4ff787c048\">~CBase</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td><td class=\"entry\"><span class=\"mlabel\">virtual</span></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html#a99e104a6f6bc4f532f1774606b0bd110\">~PolygonNode</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\">PolygonNode</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html#a9874a6b8164422b468d2a947b4c8884e\">~Sample</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Sample.html\">Sample</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a3019660a615dbe7cc0a9607a94b830a5\">~SIObject</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td><td class=\"entry\"></td></tr>\n\
</table></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";