var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>NurbsCurve Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1NurbsCurve.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>NurbsCurve Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">NurbsCurve Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__nurbscurve_8h_source.html\">xsi_nurbscurve.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> object gives access to the geometry curves of an <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\" title=\"The X3DObject object represents a basic 3D object of a scene in Softimage. \">X3DObject</a>\'s primitive. </p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurveList.html#adb1d72d49e07f845a3174df1dedb65c8\">NurbsCurveList.GetCurves()</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CNurbsCurveRefArray.html\" title=\"An array of NurbsCurve objects representing the curve in a curve list. \">CNurbsCurveRefArray</a></dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd><div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"><span class=\"keyword\">using namespace </span>MATH;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a90b73ddc91605180a7d1ea4fa22014bf\">GetActiveSceneRoot</a>();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> circle;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a0aa53709fda0b1b3de1cbdbfcd65445e\">AddGeometry</a>(L<span class=\"stringliteral\">&quot;Circle&quot;</span>,L<span class=\"stringliteral\">&quot;NurbsCurve&quot;</span>,L<span class=\"stringliteral\">&quot;&quot;</span>,circle);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurveList.html\">NurbsCurveList</a> curveList = circle.GetActivePrimitive().GetGeometry();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> curve = curveList.GetCurves().GetItem(0);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CControlPointRefArray.html\">CControlPointRefArray</a> cpArray = curve.GetControlPoints();</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CKnotArray.html\">CKnotArray</a> knotArray = curve.GetKnots();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CNurbsCurveData.html\">CNurbsCurveData</a> curveData;</div>\n\
<div class=\"line\">cpArray.GetArray(curveData.m_aControlPoints);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">knotArray.GetClosed(curveData.m_bClosed);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> circleCopyWithoutKnots;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a5533406dd409ac37f788735cbc748267\">AddNurbsCurve</a>(curveData,<a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5e68ac68443f945d0dd92137e2895d0baa33e32f7f996bf361ee8031a38b4dcce\">siSINurbs</a>,L<span class=\"stringliteral\">&quot;&quot;</span>,circleCopyWithoutKnots);</div>\n\
</div><!-- fragment --> </dd></dl>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"closed.png\" alt=\"+\"> Inheritance diagram for NurbsCurve:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"classXSI_1_1NurbsCurve.png\" usemap=\"#NurbsCurve_map\" alt=\"\">\n\
  <map id=\"NurbsCurve_map\" name=\"NurbsCurve_map\">\n\
<area href=\"classXSI_1_1SIObject.html\" title=\"SIObject derives from CBase and acts as the base class for the Softimage Object Model library...\" alt=\"SIObject\" shape=\"rect\" coords=\"0,56,81,80\">\n\
<area href=\"classXSI_1_1CBase.html\" title=\"CBase is the base class of all API classes and provides access to Softimage objects through generic C...\" alt=\"CBase\" shape=\"rect\" coords=\"0,0,81,24\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:aa39626c2ce24b81d94cd69eda713f06f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#aa39626c2ce24b81d94cd69eda713f06f\">NurbsCurve</a> ()</td></tr>\n\
<tr class=\"separator:aa39626c2ce24b81d94cd69eda713f06f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3108373b502ef10946c453de683dfb06\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a3108373b502ef10946c453de683dfb06\">~NurbsCurve</a> ()</td></tr>\n\
<tr class=\"separator:a3108373b502ef10946c453de683dfb06\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac5c09b9dcc0046ab0a20005ee0626603\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#ac5c09b9dcc0046ab0a20005ee0626603\">NurbsCurve</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:ac5c09b9dcc0046ab0a20005ee0626603\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae2959b2ba2b42405ff3a8d9283455533\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#ae2959b2ba2b42405ff3a8d9283455533\">NurbsCurve</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:ae2959b2ba2b42405ff3a8d9283455533\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a26d8f308ca76daddd39d483aff5343fc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a26d8f308ca76daddd39d483aff5343fc\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a26d8f308ca76daddd39d483aff5343fc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a776d09aa5ff1d62c7e32059c5047acf7\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a776d09aa5ff1d62c7e32059c5047acf7\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a776d09aa5ff1d62c7e32059c5047acf7\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac0019ee10fc0d7657d491d4a8b6aa980\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CKnotArray.html\">CKnotArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#ac0019ee10fc0d7657d491d4a8b6aa980\">GetKnots</a> () const </td></tr>\n\
<tr class=\"separator:ac0019ee10fc0d7657d491d4a8b6aa980\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a00bc05abc953afcd3fe0c6825b146946\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CControlPointRefArray.html\">CControlPointRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a00bc05abc953afcd3fe0c6825b146946\">GetControlPoints</a> () const </td></tr>\n\
<tr class=\"separator:a00bc05abc953afcd3fe0c6825b146946\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a42f6259af7931a3b98ae3b6f5a9a8de6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a42f6259af7931a3b98ae3b6f5a9a8de6\">Get</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5e68ac68443f945d0dd92137e2895d0b\">siNurbsFormat</a> in_siNurbsFormat, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/structXSI_1_1CNurbsCurveData.html\">CNurbsCurveData</a> &amp;out_curve) const </td></tr>\n\
<tr class=\"separator:a42f6259af7931a3b98ae3b6f5a9a8de6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aeb04b76aa0644d6c2e9d01beaa4e556e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#aeb04b76aa0644d6c2e9d01beaa4e556e\">Set</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/structXSI_1_1CNurbsCurveData.html\">CNurbsCurveData</a> &amp;in_curve, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5e68ac68443f945d0dd92137e2895d0b\">siNurbsFormat</a> in_siNurbsFormat=<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5e68ac68443f945d0dd92137e2895d0baa33e32f7f996bf361ee8031a38b4dcce\">siSINurbs</a>)</td></tr>\n\
<tr class=\"separator:aeb04b76aa0644d6c2e9d01beaa4e556e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae22938c7c37d3fe4d3c1e2697d20faa6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#ae22938c7c37d3fe4d3c1e2697d20faa6\">EvaluatePosition</a> (double in_dUValue, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vPosition, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vTangent, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vNormal, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vBiNormal) const </td></tr>\n\
<tr class=\"separator:ae22938c7c37d3fe4d3c1e2697d20faa6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a258a84e35bee210c6d54c69c2ff6d773\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a258a84e35bee210c6d54c69c2ff6d773\">EvaluateNormalizedPosition</a> (double in_dUNormalizedValue, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vPosition, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vTangent, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vNormal, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vBiNormal) const </td></tr>\n\
<tr class=\"separator:a258a84e35bee210c6d54c69c2ff6d773\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7bc3a3838fc1c870d0e93597a4c3f70a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a7bc3a3838fc1c870d0e93597a4c3f70a\">EvaluatePositionFromPercentage</a> (double in_dPercentage, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vPosition, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vTangent, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vNormal, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_vBiNormal) const </td></tr>\n\
<tr class=\"separator:a7bc3a3838fc1c870d0e93597a4c3f70a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a28579584318871930ec88b8fb64bc479\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a28579584318871930ec88b8fb64bc479\">GetDegree</a> (LONG &amp;out_lDegree) const </td></tr>\n\
<tr class=\"separator:a28579584318871930ec88b8fb64bc479\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc1903211a46db390d6e9b385f79e15e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#acc1903211a46db390d6e9b385f79e15e\">GetLength</a> (double &amp;out_dLength) const </td></tr>\n\
<tr class=\"separator:acc1903211a46db390d6e9b385f79e15e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2d978fb2b708d1f03bf2cbc1b3ed61aa\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a2d978fb2b708d1f03bf2cbc1b3ed61aa\">GetNormalizedUFromU</a> (double in_dUValue, double &amp;out_dNormalizedUValue) const </td></tr>\n\
<tr class=\"separator:a2d978fb2b708d1f03bf2cbc1b3ed61aa\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a00180dbdd96040897e2013d67567ac4d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a00180dbdd96040897e2013d67567ac4d\">GetUFromNormalizedU</a> (double in_dNormalizedUValue, double &amp;out_dUValue) const </td></tr>\n\
<tr class=\"separator:a00180dbdd96040897e2013d67567ac4d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af080017df83c7e92a265a90675c564fe\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#af080017df83c7e92a265a90675c564fe\">GetUFromPercentage</a> (double in_dPercentage, double &amp;out_dUValue) const </td></tr>\n\
<tr class=\"separator:af080017df83c7e92a265a90675c564fe\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af8f76d001025258321e2877b1a3b1272\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#af8f76d001025258321e2877b1a3b1272\">GetPercentageFromU</a> (double in_dUValue, double &amp;out_dPercentage) const </td></tr>\n\
<tr class=\"separator:af8f76d001025258321e2877b1a3b1272\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3993d8a3481950823a84c8845773d366\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a3993d8a3481950823a84c8845773d366\">GetIndex</a> () const </td></tr>\n\
<tr class=\"separator:a3993d8a3481950823a84c8845773d366\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a975ed2daa5104b0cbf5d4d58a0ca5e4d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\">SubComponent</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a975ed2daa5104b0cbf5d4d58a0ca5e4d\">GetSubComponent</a> () const </td></tr>\n\
<tr class=\"separator:a975ed2daa5104b0cbf5d4d58a0ca5e4d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3f52b3d010229eed00d8d39eabab93ac\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html#a3f52b3d010229eed00d8d39eabab93ac\">Navigate</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a334ced880a64fec1d3f9db910b789e1c\">siNavigateComponentType</a> in_siNavigate) const </td></tr>\n\
<tr class=\"separator:a3f52b3d010229eed00d8d39eabab93ac\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1SIObject\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1SIObject\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td></tr>\n\
<tr class=\"memitem:aa27dc882852af7ea1410aecde7a59fc2 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#aa27dc882852af7ea1410aecde7a59fc2\">SIObject</a> ()</td></tr>\n\
<tr class=\"separator:aa27dc882852af7ea1410aecde7a59fc2 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3019660a615dbe7cc0a9607a94b830a5 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a3019660a615dbe7cc0a9607a94b830a5\">~SIObject</a> ()</td></tr>\n\
<tr class=\"separator:a3019660a615dbe7cc0a9607a94b830a5 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a810fae9fad7bafe4ffb16df7083dfacd inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a810fae9fad7bafe4ffb16df7083dfacd\">SIObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a810fae9fad7bafe4ffb16df7083dfacd inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0e9d732eaeb68dfe6a43ccf68a06a132 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0e9d732eaeb68dfe6a43ccf68a06a132\">SIObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a0e9d732eaeb68dfe6a43ccf68a06a132 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a06a8a39f247c9826853433f5d87d6f48 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a06a8a39f247c9826853433f5d87d6f48\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a06a8a39f247c9826853433f5d87d6f48 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac699660f361bf8792b0249bc2f453ab4 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ac699660f361bf8792b0249bc2f453ab4\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:ac699660f361bf8792b0249bc2f453ab4 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a36cf1424d90dfdd72097f0959790d475 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a36cf1424d90dfdd72097f0959790d475\">GetApplication</a> () const </td></tr>\n\
<tr class=\"separator:a36cf1424d90dfdd72097f0959790d475 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab5e38bc9c650b2d8ca0abe29b516cf87 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a> () const </td></tr>\n\
<tr class=\"separator:ab5e38bc9c650b2d8ca0abe29b516cf87 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab5b36ddcfe22b04b0ca67b7be4f14f85 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5b36ddcfe22b04b0ca67b7be4f14f85\">GetName</a> () const </td></tr>\n\
<tr class=\"separator:ab5b36ddcfe22b04b0ca67b7be4f14f85 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afc968d8ce92392583fb64412ab3bed28 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#afc968d8ce92392583fb64412ab3bed28\">PutName</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_name)</td></tr>\n\
<tr class=\"separator:afc968d8ce92392583fb64412ab3bed28 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:addeb66825ef8aa3d36157a1959527f19 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#addeb66825ef8aa3d36157a1959527f19\">GetUniqueName</a> () const </td></tr>\n\
<tr class=\"separator:addeb66825ef8aa3d36157a1959527f19 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a327d1b55ff1e258417451a8a292c3c4f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a327d1b55ff1e258417451a8a292c3c4f\">GetType</a> () const </td></tr>\n\
<tr class=\"separator:a327d1b55ff1e258417451a8a292c3c4f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abc306e1a2d61cba72802d28f751aa640 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#abc306e1a2d61cba72802d28f751aa640\">GetParent</a> () const </td></tr>\n\
<tr class=\"separator:abc306e1a2d61cba72802d28f751aa640 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0d3dc111fd7156689b9b2c1fd2c5f581 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0d3dc111fd7156689b9b2c1fd2c5f581\">IsEqualTo</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:a0d3dc111fd7156689b9b2c1fd2c5f581 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8051b32ae9c745b35ded13029220080c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a8051b32ae9c745b35ded13029220080c\">GetHelp</a> () const </td></tr>\n\
<tr class=\"separator:a8051b32ae9c745b35ded13029220080c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a172c48e4a4d1341ea9002832a734c3ba inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a172c48e4a4d1341ea9002832a734c3ba\">GetOriginPath</a> () const </td></tr>\n\
<tr class=\"separator:a172c48e4a4d1341ea9002832a734c3ba inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab13f5aab4ca531714928a81bcea7b24c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a78f4f7bf0e1dcfc222ef5ccc055fc6af\">siInstallationPath</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab13f5aab4ca531714928a81bcea7b24c\">GetOrigin</a> () const </td></tr>\n\
<tr class=\"separator:ab13f5aab4ca531714928a81bcea7b24c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a53593f8cadffbaddd9245bbaa078eef6 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a53593f8cadffbaddd9245bbaa078eef6\">GetCategories</a> () const </td></tr>\n\
<tr class=\"separator:a53593f8cadffbaddd9245bbaa078eef6 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a86d8446a011274790e13534569a26b6f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a86d8446a011274790e13534569a26b6f\">GetNestedObjects</a> () const </td></tr>\n\
<tr class=\"separator:a86d8446a011274790e13534569a26b6f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1CBase\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1CBase\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td></tr>\n\
<tr class=\"memitem:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a3878f3ab13413eb6d4811dca38b4fa73\">CBase</a> ()</td></tr>\n\
<tr class=\"separator:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a012a4573399b53f0720fcf4ff787c048\">~CBase</a> ()</td></tr>\n\
<tr class=\"separator:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac347619969a79eb8afc0adf6ea9394ba\">GetClassIDName</a> () const </td></tr>\n\
<tr class=\"separator:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac8759bb33eaf8bf83949277169a048e6\">IsA</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a458e6e03ea0b71cb2205a5fd9e1999c8\">SetObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a> () const </td></tr>\n\
<tr class=\"separator:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac5a79b5ac1759bc4e66e8f662b8bad49\">ResetObject</a> ()</td></tr>\n\
<tr class=\"separator:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a20250592358718fccc1dad9e949d3d28\">operator CRef &amp;</a> ()</td></tr>\n\
<tr class=\"separator:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac91cdd4cb81fac44686c538126a4b98a\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a99049c404ae9b0ae189f80771dee0596\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#aac2a77c9ccdd6d0f9953ef784e2be5e9\">GetRef</a> () const </td></tr>\n\
<tr class=\"separator:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"aa39626c2ce24b81d94cd69eda713f06f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3108373b502ef10946c453de683dfb06\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ac5c09b9dcc0046ab0a20005ee0626603\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant reference object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ae2959b2ba2b42405ff3a8d9283455533\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a6dd5a8a11eee55f434f151d1cd5d29d8\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool IsA </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_ClassID</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if a given class type is compatible with this API class. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ClassID</td><td>class type. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if the class is compatible, false otherwise. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a5a1833349ed14be553ae68b84ff60b8d\">CBase</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acc34f4a01f2089e40f7abc7e9d98bf15\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the type of the API class. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The class type. </dd></dl>\n\
\n\
<p>Implements <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a4b1359dd080cedb25e5f53df23d264b5\">CBase</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a26d8f308ca76daddd39d483aff5343fc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from another object. The newly created object is set to empty if the input object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a776d09aa5ff1d62c7e32059c5047acf7\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from a reference object. The newly created object is set to empty if the input reference object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ac0019ee10fc0d7657d491d4a8b6aa980\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CKnotArray.html\">CKnotArray</a> GetKnots </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of all Knot values on this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> object. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of knots. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a00bc05abc953afcd3fe0c6825b146946\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CControlPointRefArray.html\">CControlPointRefArray</a> GetControlPoints </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of all <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ControlPoint.html\" title=\"The ControlPoint of a NurbsSurface or a NurbsCurve. \">ControlPoint</a> objects on this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> object. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ControlPoint.html\" title=\"The ControlPoint of a NurbsSurface or a NurbsCurve. \">ControlPoint</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a42f6259af7931a3b98ae3b6f5a9a8de6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Get </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5e68ac68443f945d0dd92137e2895d0b\">siNurbsFormat</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_siNurbsFormat</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/structXSI_1_1CNurbsCurveData.html\">CNurbsCurveData</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_curve</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns a complete data description of a nurbs curve. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_siNurbsFormat</td><td>Specifies how the data is formatted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_curve</td><td>The entire curve data description. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aeb04b76aa0644d6c2e9d01beaa4e556e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Set </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/structXSI_1_1CNurbsCurveData.html\">CNurbsCurveData</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_curve</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5e68ac68443f945d0dd92137e2895d0b\">siNurbsFormat</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_siNurbsFormat</em> = <code><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5e68ac68443f945d0dd92137e2895d0baa33e32f7f996bf361ee8031a38b4dcce\">siSINurbs</a></code>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the current description from a complete data description of nurbs curve. This is only available from compiled operators; if you use it on an object with some clusters and you change the topology the burden of updating the clusters is on the user. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_curve</td><td>The new data description for this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a>. </td></tr>\n\
    <tr><td class=\"paramname\">in_siNurbsFormat</td><td>Specifies how the data is formatted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da60a075acd0b5e992180ec8ad7d794ea4\">CStatus::AccessDenied</a> function used outside of a plug-in operator context. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ae22938c7c37d3fe4d3c1e2697d20faa6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EvaluatePosition </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dUValue</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vPosition</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vTangent</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vNormal</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vBiNormal</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the Position, Tangent, Normal and BiNormal at a given U value. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dUValue</td><td>The U Value at which we want to evaluate the curve. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_vPosition</td><td>Position at the given U. </td></tr>\n\
    <tr><td class=\"paramname\">out_vTangent</td><td>Tangent at the given U. </td></tr>\n\
    <tr><td class=\"paramname\">out_vNormal</td><td>Normal at the given U. </td></tr>\n\
    <tr><td class=\"paramname\">out_vBiNormal</td><td>Bi-Normal at the given U. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a258a84e35bee210c6d54c69c2ff6d773\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EvaluateNormalizedPosition </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dUNormalizedValue</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vPosition</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vTangent</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vNormal</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vBiNormal</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the Position, Tangent, Normal and BiNormal at a given normalized U value. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dUNormalizedValue</td><td>The normalized UValue(0.0 to 1.0) at which we want to evaluate the curve. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_vPosition</td><td>Position at the given U. </td></tr>\n\
    <tr><td class=\"paramname\">out_vTangent</td><td>Tangent at the given U. </td></tr>\n\
    <tr><td class=\"paramname\">out_vNormal</td><td>Normal at the given U. </td></tr>\n\
    <tr><td class=\"paramname\">out_vBiNormal</td><td>Bi-Normal at the given U. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7bc3a3838fc1c870d0e93597a4c3f70a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EvaluatePositionFromPercentage </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dPercentage</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vPosition</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vTangent</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vNormal</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_vBiNormal</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns a 3D vector giving the position, tangent in U direction, normal and bi-normal at a given percentage along the curve. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dPercentage</td><td>The percentange(with values between 0.0 and 100.0 inclusive) of the length of the curve at which we want to evaluate the curve. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_vPosition</td><td>Position at the given percentage. </td></tr>\n\
    <tr><td class=\"paramname\">out_vTangent</td><td>Tangent at the given percentage. </td></tr>\n\
    <tr><td class=\"paramname\">out_vNormal</td><td>Normal at the given percentage. </td></tr>\n\
    <tr><td class=\"paramname\">out_vBiNormal</td><td>Bi-Normal at the given percentage. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a28579584318871930ec88b8fb64bc479\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetDegree </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_lDegree</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the degree of the curve. </p>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_lDegree</td><td>The degree of the curve. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acc1903211a46db390d6e9b385f79e15e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetLength </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_dLength</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the length of the curve. </p>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_dLength</td><td>The length of the curve. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a2d978fb2b708d1f03bf2cbc1b3ed61aa\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetNormalizedUFromU </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dUValue</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_dNormalizedUValue</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the Normalized equivalent of U value. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dUValue</td><td>The UValue from which we want the Normalized equivalent. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_dNormalizedUValue</td><td>The normalized U value equivalent. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a00180dbdd96040897e2013d67567ac4d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetUFromNormalizedU </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dNormalizedUValue</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_dUValue</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the U actual value equivalent to the specified normalized U value. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dNormalizedUValue</td><td>The normalized UValue(0.0 to 1.0) from which we want the actual value equivalent. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_dUValue</td><td>The actual U value equivalent. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af080017df83c7e92a265a90675c564fe\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetUFromPercentage </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dPercentage</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_dUValue</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the U value at a certain percentage along the curve. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dPercentage</td><td>A percentage (with values between 0.0 and 100.0 inclusive) of the length of the curve. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_dUValue</td><td>The actual U value equivalent. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af8f76d001025258321e2877b1a3b1272\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetPercentageFromU </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">double&#160;</td>\n\
          <td class=\"paramname\"><em>in_dUValue</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">double &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_dPercentage</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the percentage (with values between 0.0 and 100.0 inclusive) along the curve at the given U value. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_dUValue</td><td>The U value at which we want to evaluate the curve. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_dPercentage</td><td>The actual U value equivalent. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> other failure </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3993d8a3481950823a84c8845773d366\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetIndex </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the index of the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> in the geometry\'s <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurveList.html\" title=\"A NurbsCurveList is a kind of Geometry and is a collection of NurbsCurve objects. ...\">NurbsCurveList</a>. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> index </dd>\n\
<dd>\n\
-1 if the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> object is not initialized. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a975ed2daa5104b0cbf5d4d58a0ca5e4d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\">SubComponent</a> GetSubComponent </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates a <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\" title=\"Provides access to the subelements of an object&#39;s Geometry. \">SubComponent</a> object from this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> object. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\" title=\"Provides access to the subelements of an object&#39;s Geometry. \">SubComponent</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3f52b3d010229eed00d8d39eabab93ac\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\">NurbsCurve</a> Navigate </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a334ced880a64fec1d3f9db910b789e1c\">siNavigateComponentType</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_siNavigate</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Navigates the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> objects of the underlying geometry as specifed by the navigation component type. The navigation is circular, therefore if you ask for siNextComponent on the last <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a> it returns the first <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1NurbsCurve.html\" title=\"The NurbsCurve object gives access to the geometry curves of an X3DObject&#39;s primitive. \">NurbsCurve</a>. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_siNavigate</td><td>Type of direction for navigating the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html\" title=\"A facet is a generic concept used to describe a Geometry&#39;s PolygonFace, NurbsSurface or NurbsCurve...\">Facet</a> objects. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> object being visited. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__nurbscurve_8h_source.html\">xsi_nurbscurve.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";