var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>PolygonFace Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1PolygonFace.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>PolygonFace Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">PolygonFace Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__polygonface_8h_source.html\">xsi_polygonface.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> object gives access to the geometry polygons of an <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\" title=\"The X3DObject object represents a basic 3D object of a scene in Softimage. \">X3DObject</a>\'s primitive. </p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonMesh.html#a460536201c5acbf2339bf93f17076cd5\">PolygonMesh.GetPolygons()</a>, CPolygonFaceArray</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd><div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.GetActiveSceneRoot();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> myCube;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a0aa53709fda0b1b3de1cbdbfcd65445e\">AddGeometry</a>( L<span class=\"stringliteral\">&quot;Cube&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, myCube );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonMesh.html\">PolygonMesh</a> mesh( myCube.GetActivePrimitive().GetGeometry() );</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> face( mesh.GetPolygons().GetItem(0) );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">app.LogMessage(L<span class=\"stringliteral\">&quot;Number of nodes: &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(face.GetNodes().GetCount()).GetAsText() );</div>\n\
</div><!-- fragment --> </dd></dl>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"closed.png\" alt=\"+\"> Inheritance diagram for PolygonFace:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"classXSI_1_1PolygonFace.png\" usemap=\"#PolygonFace_map\" alt=\"\">\n\
  <map id=\"PolygonFace_map\" name=\"PolygonFace_map\">\n\
<area href=\"classXSI_1_1Facet.html\" title=\"A facet is a generic concept used to describe a Geometry&#39;s PolygonFace, NurbsSurface or NurbsCurve...\" alt=\"Facet\" shape=\"rect\" coords=\"0,112,87,136\">\n\
<area href=\"classXSI_1_1SIObject.html\" title=\"SIObject derives from CBase and acts as the base class for the Softimage Object Model library...\" alt=\"SIObject\" shape=\"rect\" coords=\"0,56,87,80\">\n\
<area href=\"classXSI_1_1CBase.html\" title=\"CBase is the base class of all API classes and provides access to Softimage objects through generic C...\" alt=\"CBase\" shape=\"rect\" coords=\"0,0,87,24\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a9fa3055fef075a93f28b93e5bd2caea3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a9fa3055fef075a93f28b93e5bd2caea3\">PolygonFace</a> ()</td></tr>\n\
<tr class=\"separator:a9fa3055fef075a93f28b93e5bd2caea3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af80450ec94d556411c92d08186087587\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#af80450ec94d556411c92d08186087587\">~PolygonFace</a> ()</td></tr>\n\
<tr class=\"separator:af80450ec94d556411c92d08186087587\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9f36357b481cc0cf7590edbca6988ed0\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a9f36357b481cc0cf7590edbca6988ed0\">PolygonFace</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a9f36357b481cc0cf7590edbca6988ed0\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae785f40a72683314b07b6bdb98c588f5\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#ae785f40a72683314b07b6bdb98c588f5\">PolygonFace</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:ae785f40a72683314b07b6bdb98c588f5\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a110ca1f65d0c81a3272facf549cf75f2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a110ca1f65d0c81a3272facf549cf75f2\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a110ca1f65d0c81a3272facf549cf75f2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af639636f2b9a8407624c1ddac37a1a95\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#af639636f2b9a8407624c1ddac37a1a95\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:af639636f2b9a8407624c1ddac37a1a95\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad1106ce4f4f41a25d3790ec93a488d85\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPolygonNodeRefArray.html\">CPolygonNodeRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#ad1106ce4f4f41a25d3790ec93a488d85\">GetNodes</a> () const </td></tr>\n\
<tr class=\"separator:ad1106ce4f4f41a25d3790ec93a488d85\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a003c826507bc5bd356b467d878e35847\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html\">CVertexRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a003c826507bc5bd356b467d878e35847\">GetVertices</a> () const </td></tr>\n\
<tr class=\"separator:a003c826507bc5bd356b467d878e35847\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0023c7663e164949ff5ff4c0e38bda7e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CEdgeRefArray.html\">CEdgeRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a0023c7663e164949ff5ff4c0e38bda7e\">GetEdges</a> () const </td></tr>\n\
<tr class=\"separator:a0023c7663e164949ff5ff4c0e38bda7e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a809a7063603ca06168b528d2c39b536a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html\">CVertexRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a809a7063603ca06168b528d2c39b536a\">GetNeighborVertices</a> (LONG in_lDistance=1) const </td></tr>\n\
<tr class=\"separator:a809a7063603ca06168b528d2c39b536a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5607690f92395e78b490c576bf4ebbb8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CEdgeRefArray.html\">CEdgeRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a5607690f92395e78b490c576bf4ebbb8\">GetNeighborEdges</a> (LONG in_lDistance=1) const </td></tr>\n\
<tr class=\"separator:a5607690f92395e78b490c576bf4ebbb8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abc5944b41d5a29a66fe96e488909b1bd\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPolygonFaceRefArray.html\">CPolygonFaceRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#abc5944b41d5a29a66fe96e488909b1bd\">GetNeighborPolygons</a> (LONG in_lDistance=1) const </td></tr>\n\
<tr class=\"separator:abc5944b41d5a29a66fe96e488909b1bd\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7b0b14436a95c7568e7432a147b70907\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPolygonFaceRefArray.html\">CPolygonFaceRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a7b0b14436a95c7568e7432a147b70907\">GrowNeighborPolygons</a> (LONG in_lDistance=1) const </td></tr>\n\
<tr class=\"separator:a7b0b14436a95c7568e7432a147b70907\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a857b2721a957849d9d6ee51d30506985\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a857b2721a957849d9d6ee51d30506985\">GetTriangleSubIndexArray</a> () const </td></tr>\n\
<tr class=\"separator:a857b2721a957849d9d6ee51d30506985\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa4c8fd2d3b354ddc94befd518ac6af50\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">ULONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#aa4c8fd2d3b354ddc94befd518ac6af50\">GetTurnInternalEdgeOffset</a> () const </td></tr>\n\
<tr class=\"separator:aa4c8fd2d3b354ddc94befd518ac6af50\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1Facet\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1Facet\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html\">Facet</a></td></tr>\n\
<tr class=\"memitem:a95a828fdef116f12a206216d6164cd1a inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a95a828fdef116f12a206216d6164cd1a\">Facet</a> ()</td></tr>\n\
<tr class=\"separator:a95a828fdef116f12a206216d6164cd1a inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a43139597ea8cbe7d97703a6791fb18b6 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a43139597ea8cbe7d97703a6791fb18b6\">~Facet</a> ()</td></tr>\n\
<tr class=\"separator:a43139597ea8cbe7d97703a6791fb18b6 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac55f6759e8e84b3a627129462e2a4d0d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#ac55f6759e8e84b3a627129462e2a4d0d\">Facet</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:ac55f6759e8e84b3a627129462e2a4d0d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a018baf2338fc614e07068adc90356b7d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a018baf2338fc614e07068adc90356b7d\">Facet</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html\">Facet</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a018baf2338fc614e07068adc90356b7d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af5fdc3a2f664c1ef3dc572a7533c2ec8 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html\">Facet</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#af5fdc3a2f664c1ef3dc572a7533c2ec8\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html\">Facet</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:af5fdc3a2f664c1ef3dc572a7533c2ec8 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a637514d1202eb71902e1aa7ec38b202f inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html\">Facet</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a637514d1202eb71902e1aa7ec38b202f\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a637514d1202eb71902e1aa7ec38b202f inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2b0a0b9e21e6f2415cf899316b11ec6c inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CSegmentRefArray.html\">CSegmentRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a2b0a0b9e21e6f2415cf899316b11ec6c\">GetSegments</a> () const </td></tr>\n\
<tr class=\"separator:a2b0a0b9e21e6f2415cf899316b11ec6c inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a811d3648a75a4eccea18f644e10ba31d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\">CPointRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a811d3648a75a4eccea18f644e10ba31d\">GetPoints</a> () const </td></tr>\n\
<tr class=\"separator:a811d3648a75a4eccea18f644e10ba31d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a46003fb2f95609f5f646fd6f7dc312bb inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a46003fb2f95609f5f646fd6f7dc312bb\">GetNbPoints</a> () const </td></tr>\n\
<tr class=\"separator:a46003fb2f95609f5f646fd6f7dc312bb inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3993d8a3481950823a84c8845773d366 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a3993d8a3481950823a84c8845773d366\">GetIndex</a> () const </td></tr>\n\
<tr class=\"separator:a3993d8a3481950823a84c8845773d366 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a162db2455b6a2442aace908cf6becde2 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CSampleRefArray.html\">CSampleRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a162db2455b6a2442aace908cf6becde2\">GetSamples</a> () const </td></tr>\n\
<tr class=\"separator:a162db2455b6a2442aace908cf6becde2 inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a975ed2daa5104b0cbf5d4d58a0ca5e4d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\">SubComponent</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a975ed2daa5104b0cbf5d4d58a0ca5e4d\">GetSubComponent</a> () const </td></tr>\n\
<tr class=\"separator:a975ed2daa5104b0cbf5d4d58a0ca5e4d inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abfd03f6e8807024fea167a75687ab0dc inherit pub_methods_classXSI_1_1Facet\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html\">Facet</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#abfd03f6e8807024fea167a75687ab0dc\">Navigate</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a334ced880a64fec1d3f9db910b789e1c\">siNavigateComponentType</a> in_siNavigate) const </td></tr>\n\
<tr class=\"separator:abfd03f6e8807024fea167a75687ab0dc inherit pub_methods_classXSI_1_1Facet\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1SIObject\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1SIObject\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a></td></tr>\n\
<tr class=\"memitem:aa27dc882852af7ea1410aecde7a59fc2 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#aa27dc882852af7ea1410aecde7a59fc2\">SIObject</a> ()</td></tr>\n\
<tr class=\"separator:aa27dc882852af7ea1410aecde7a59fc2 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3019660a615dbe7cc0a9607a94b830a5 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a3019660a615dbe7cc0a9607a94b830a5\">~SIObject</a> ()</td></tr>\n\
<tr class=\"separator:a3019660a615dbe7cc0a9607a94b830a5 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a810fae9fad7bafe4ffb16df7083dfacd inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a810fae9fad7bafe4ffb16df7083dfacd\">SIObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a810fae9fad7bafe4ffb16df7083dfacd inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0e9d732eaeb68dfe6a43ccf68a06a132 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0e9d732eaeb68dfe6a43ccf68a06a132\">SIObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a0e9d732eaeb68dfe6a43ccf68a06a132 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a06a8a39f247c9826853433f5d87d6f48 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a06a8a39f247c9826853433f5d87d6f48\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a06a8a39f247c9826853433f5d87d6f48 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac699660f361bf8792b0249bc2f453ab4 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html\">SIObject</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ac699660f361bf8792b0249bc2f453ab4\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:ac699660f361bf8792b0249bc2f453ab4 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a36cf1424d90dfdd72097f0959790d475 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a36cf1424d90dfdd72097f0959790d475\">GetApplication</a> () const </td></tr>\n\
<tr class=\"separator:a36cf1424d90dfdd72097f0959790d475 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab5e38bc9c650b2d8ca0abe29b516cf87 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a> () const </td></tr>\n\
<tr class=\"separator:ab5e38bc9c650b2d8ca0abe29b516cf87 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab5b36ddcfe22b04b0ca67b7be4f14f85 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5b36ddcfe22b04b0ca67b7be4f14f85\">GetName</a> () const </td></tr>\n\
<tr class=\"separator:ab5b36ddcfe22b04b0ca67b7be4f14f85 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afc968d8ce92392583fb64412ab3bed28 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#afc968d8ce92392583fb64412ab3bed28\">PutName</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_name)</td></tr>\n\
<tr class=\"separator:afc968d8ce92392583fb64412ab3bed28 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:addeb66825ef8aa3d36157a1959527f19 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#addeb66825ef8aa3d36157a1959527f19\">GetUniqueName</a> () const </td></tr>\n\
<tr class=\"separator:addeb66825ef8aa3d36157a1959527f19 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a327d1b55ff1e258417451a8a292c3c4f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a327d1b55ff1e258417451a8a292c3c4f\">GetType</a> () const </td></tr>\n\
<tr class=\"separator:a327d1b55ff1e258417451a8a292c3c4f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abc306e1a2d61cba72802d28f751aa640 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#abc306e1a2d61cba72802d28f751aa640\">GetParent</a> () const </td></tr>\n\
<tr class=\"separator:abc306e1a2d61cba72802d28f751aa640 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0d3dc111fd7156689b9b2c1fd2c5f581 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a0d3dc111fd7156689b9b2c1fd2c5f581\">IsEqualTo</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:a0d3dc111fd7156689b9b2c1fd2c5f581 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8051b32ae9c745b35ded13029220080c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a8051b32ae9c745b35ded13029220080c\">GetHelp</a> () const </td></tr>\n\
<tr class=\"separator:a8051b32ae9c745b35ded13029220080c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a172c48e4a4d1341ea9002832a734c3ba inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a172c48e4a4d1341ea9002832a734c3ba\">GetOriginPath</a> () const </td></tr>\n\
<tr class=\"separator:a172c48e4a4d1341ea9002832a734c3ba inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab13f5aab4ca531714928a81bcea7b24c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a78f4f7bf0e1dcfc222ef5ccc055fc6af\">siInstallationPath</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab13f5aab4ca531714928a81bcea7b24c\">GetOrigin</a> () const </td></tr>\n\
<tr class=\"separator:ab13f5aab4ca531714928a81bcea7b24c inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a53593f8cadffbaddd9245bbaa078eef6 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a53593f8cadffbaddd9245bbaa078eef6\">GetCategories</a> () const </td></tr>\n\
<tr class=\"separator:a53593f8cadffbaddd9245bbaa078eef6 inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a86d8446a011274790e13534569a26b6f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#a86d8446a011274790e13534569a26b6f\">GetNestedObjects</a> () const </td></tr>\n\
<tr class=\"separator:a86d8446a011274790e13534569a26b6f inherit pub_methods_classXSI_1_1SIObject\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1CBase\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1CBase\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td></tr>\n\
<tr class=\"memitem:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a3878f3ab13413eb6d4811dca38b4fa73\">CBase</a> ()</td></tr>\n\
<tr class=\"separator:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a012a4573399b53f0720fcf4ff787c048\">~CBase</a> ()</td></tr>\n\
<tr class=\"separator:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac347619969a79eb8afc0adf6ea9394ba\">GetClassIDName</a> () const </td></tr>\n\
<tr class=\"separator:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac8759bb33eaf8bf83949277169a048e6\">IsA</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a458e6e03ea0b71cb2205a5fd9e1999c8\">SetObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a> () const </td></tr>\n\
<tr class=\"separator:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac5a79b5ac1759bc4e66e8f662b8bad49\">ResetObject</a> ()</td></tr>\n\
<tr class=\"separator:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a20250592358718fccc1dad9e949d3d28\">operator CRef &amp;</a> ()</td></tr>\n\
<tr class=\"separator:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac91cdd4cb81fac44686c538126a4b98a\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a99049c404ae9b0ae189f80771dee0596\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#aac2a77c9ccdd6d0f9953ef784e2be5e9\">GetRef</a> () const </td></tr>\n\
<tr class=\"separator:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a9fa3055fef075a93f28b93e5bd2caea3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af80450ec94d556411c92d08186087587\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9f36357b481cc0cf7590edbca6988ed0\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant reference object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ae785f40a72683314b07b6bdb98c588f5\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a6dd5a8a11eee55f434f151d1cd5d29d8\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool IsA </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_ClassID</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if a given class type is compatible with this API class. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ClassID</td><td>class type. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if the class is compatible, false otherwise. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">Facet</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acc34f4a01f2089e40f7abc7e9d98bf15\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the type of the API class. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The class type. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#acc34f4a01f2089e40f7abc7e9d98bf15\">Facet</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a110ca1f65d0c81a3272facf549cf75f2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from another object. The newly created object is set to empty if the input object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af639636f2b9a8407624c1ddac37a1a95\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from a reference object. The newly created object is set to empty if the input reference object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad1106ce4f4f41a25d3790ec93a488d85\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPolygonNodeRefArray.html\">CPolygonNodeRefArray</a> GetNodes </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\" title=\"The PolygonNode object gives access to the X3DObject&#39;s polygon node geometry. A polygon represents th...\">PolygonNode</a> objects on this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> object. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonNode.html\" title=\"The PolygonNode object gives access to the X3DObject&#39;s polygon node geometry. A polygon represents th...\">PolygonNode</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a003c826507bc5bd356b467d878e35847\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html\">CVertexRefArray</a> GetVertices </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Vertex.html\" title=\"The Vertex object gives access to the geometry vertices of an X3DObject&#39;s Primitive. A Vertex is the object PolygonMesh specifics of the Point object. \">Vertex</a> objects on this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> object. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Vertex.html\" title=\"The Vertex object gives access to the geometry vertices of an X3DObject&#39;s Primitive. A Vertex is the object PolygonMesh specifics of the Point object. \">Vertex</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0023c7663e164949ff5ff4c0e38bda7e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CEdgeRefArray.html\">CEdgeRefArray</a> GetEdges </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Edge.html\" title=\"The Edge object gives access to the geometry edges of an X3DObject&#39;s primitive. \">Edge</a> objects on this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> object. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Edge.html\" title=\"The Edge object gives access to the geometry edges of an X3DObject&#39;s primitive. \">Edge</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a809a7063603ca06168b528d2c39b536a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html\">CVertexRefArray</a> GetNeighborVertices </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_lDistance</em> = <code>1</code></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Vertex.html\" title=\"The Vertex object gives access to the geometry vertices of an X3DObject&#39;s Primitive. A Vertex is the object PolygonMesh specifics of the Point object. \">Vertex</a> neighbors within a given distance.If the distance is 1 all <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Vertex.html\" title=\"The Vertex object gives access to the geometry vertices of an X3DObject&#39;s Primitive. A Vertex is the object PolygonMesh specifics of the Point object. \">Vertex</a> objects comprising the current <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> are returned in counter-clockwise order.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_lDistance</td><td>Value representing the degree of neighborhood (eg: degree=2 for a polygon means its adjacent vertices plus the adjacent vertices of the adjacent polygons).</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Vertex.html\" title=\"The Vertex object gives access to the geometry vertices of an X3DObject&#39;s Primitive. A Vertex is the object PolygonMesh specifics of the Point object. \">Vertex</a> objects </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a5607690f92395e78b490c576bf4ebbb8\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CEdgeRefArray.html\">CEdgeRefArray</a> GetNeighborEdges </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_lDistance</em> = <code>1</code></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Edge.html\" title=\"The Edge object gives access to the geometry edges of an X3DObject&#39;s primitive. \">Edge</a> neighbors within a given distance. If the distance is 1 all <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Edge.html\" title=\"The Edge object gives access to the geometry edges of an X3DObject&#39;s primitive. \">Edge</a> objects comprising the current <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> are returned in counter-clockwise order.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_lDistance</td><td>Value representing the degree of neighborhood (eg: degree=2 for a polygon means its adjacent vertices plus the adjacent vertices of the adjacent polygons).</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Edge.html\" title=\"The Edge object gives access to the geometry edges of an X3DObject&#39;s primitive. \">Edge</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abc5944b41d5a29a66fe96e488909b1bd\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPolygonFaceRefArray.html\">CPolygonFaceRefArray</a> GetNeighborPolygons </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_lDistance</em> = <code>1</code></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> neighbors within a given distance. If the distance is 1 all <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> objects that share an <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Edge.html\" title=\"The Edge object gives access to the geometry edges of an X3DObject&#39;s primitive. \">Edge</a> with the current <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> are returned in counter-clockwise order.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_lDistance</td><td>Value representing the degree of neighborhood (eg: degree=2 for a polygon means its adjacent vertices plus the adjacent vertices of the adjacent polygons).</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7b0b14436a95c7568e7432a147b70907\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPolygonFaceRefArray.html\">CPolygonFaceRefArray</a> GrowNeighborPolygons </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_lDistance</em> = <code>1</code></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> objects that are adjacent to this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> object, within a given distance.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_lDistance</td><td>Value representing the degree of neighborhood (eg: degree=2 for a polygon means its adjacent vertices plus the adjacent vertices of the adjacent polygons).</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\" title=\"The PolygonFace object gives access to the geometry polygons of an X3DObject&#39;s primitive. \">PolygonFace</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a857b2721a957849d9d6ee51d30506985\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> GetTriangleSubIndexArray </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns a packed array of triangulation descriptions corresponding to the tesselation of the polygon. The polygon is tesselated into (Facet::NbPoints - 2) triangles, and 3 indices in the range (0..Facet::NbPoints-1) are returned for each triangle. Each index triplet describes a subtriangle of the polygon, and the indices correspond to the vertex or node ordering within the polygon.</p>\n\
<p>Notice that the triangulation of a polygon may change accordingly to the deformation of the geometry.</p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of packed triangle subindices triplets.</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd>This example demonstrates how to describe the triangulation of some polygons.</dd></dl>\n\
<div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.GetActiveSceneRoot();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> meshSphereObj;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a0aa53709fda0b1b3de1cbdbfcd65445e\">AddGeometry</a>( L<span class=\"stringliteral\">&quot;Sphere&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, meshSphereObj );</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonMesh.html\">PolygonMesh</a> meshSphereGeom( meshSphereObj.GetActivePrimitive().GetGeometry() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CPolygonFaceRefArray.html\">CPolygonFaceRefArray</a> polygons = meshSphereGeom.GetPolygons();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">LONG i;</div>\n\
<div class=\"line\"><span class=\"keywordflow\">for</span>(i = 0; i &lt; polygons.GetCount(); i++)</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html\">PolygonFace</a> polygon = polygons[i];</div>\n\
<div class=\"line\">    LONG nbTriangles = polygon.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Facet.html#a46003fb2f95609f5f646fd6f7dc312bb\">GetNbPoints</a>()-2;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> polygonNeiVtxIndices = polygon.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a003c826507bc5bd356b467d878e35847\">GetVertices</a>().<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#ab4fde8a2050e5834a751cbdf8e9d0a3f\">GetIndexArray</a>();</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> polygonNeiNodIndices = polygon.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#ad1106ce4f4f41a25d3790ec93a488d85\">GetNodes</a>().<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CSampleRefArray.html#ab4fde8a2050e5834a751cbdf8e9d0a3f\">GetIndexArray</a>();</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> polygonTriSubIndices = polygon.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PolygonFace.html#a857b2721a957849d9d6ee51d30506985\">GetTriangleSubIndexArray</a>();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    LONG j;</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">for</span>(j = 0; j &lt; nbTriangles; j++)</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        app.LogMessage(L<span class=\"stringliteral\">&quot;SubTriangle &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(j)) + L<span class=\"stringliteral\">&quot; of Polygon &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(i)) + L<span class=\"stringliteral\">&quot; correspond to vertices (&quot;</span> +</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(polygonNeiVtxIndices[polygonTriSubIndices[j*3]])) + L<span class=\"stringliteral\">&quot;, &quot;</span> +</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(polygonNeiVtxIndices[polygonTriSubIndices[j*3+1]])) + L<span class=\"stringliteral\">&quot;, &quot;</span> +</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(polygonNeiVtxIndices[polygonTriSubIndices[j*3+2]])) + L<span class=\"stringliteral\">&quot;) and nodes (&quot;</span> +</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(polygonNeiNodIndices[polygonTriSubIndices[j*3]])) + L<span class=\"stringliteral\">&quot;, &quot;</span> +</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(polygonNeiNodIndices[polygonTriSubIndices[j*3+1]])) + L<span class=\"stringliteral\">&quot;, &quot;</span> +</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(polygonNeiNodIndices[polygonTriSubIndices[j*3+2]])) + L<span class=\"stringliteral\">&quot;).&quot;</span>);</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\">}</div>\n\
<div class=\"line\"><span class=\"comment\">// Expected results:</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : SubTriangle 0 of Polygon 0 correspond to vertices (9, 2, 0) and nodes (0, 1, 2).</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : SubTriangle 0 of Polygon 1 correspond to vertices (2, 9, 10) and nodes (3, 4, 5).</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : SubTriangle 1 of Polygon 1 correspond to vertices (2, 10, 3) and nodes (3, 5, 6).</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : SubTriangle 0 of Polygon 2 correspond to vertices (3, 10, 11) and nodes (7, 8, 9).</span></div>\n\
<div class=\"line\"><span class=\"comment\">//INFO : SubTriangle 1 of Polygon 2 correspond to vertices (3, 11, 4) and nodes (7, 9, 10).</span></div>\n\
<div class=\"line\"><span class=\"comment\">//etc.</span></div>\n\
</div><!-- fragment --> \n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa4c8fd2d3b354ddc94befd518ac6af50\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">ULONG GetTurnInternalEdgeOffset </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the polygon node used to start the triangle fan of the default triangulation of the polygon. This offset is controlled by applying the TurnEdge operator. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The offset between <code>0</code> and <code>NbPoints-1</code> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>8.0 (2010) </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__polygonface_8h_source.html\">xsi_polygonface.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";