var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><meta name=\"robots\" content=\"noindex, follow\"><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>Member List</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1CICEGeometry-members.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>Member List</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CICEGeometry Member List</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p>This is the complete list of members for <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a>, including all inherited members.</p>\n\
<table class=\"directory\">\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1c692d778193acab29ee534b98bf9a62\">CICEGeometry</a>(ICENodeContext &amp;in_ctxt, ULONG in_nInputPortID, ULONG in_nInstanceIndex=0)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#ac6244b19a6076c0da097993a2f597700\">CICEGeometry</a>(const CICEGeometry &amp;in_geom)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a7acb999636a9a52d9c0be254d47da976\">CICEGeometry</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#aadd0c8bf4d40d83e231053dc5094bd63\">ClearState</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a79be0489b44a77620de069631265f22f\">DirtyState</a> enum name</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#af97e84fbc38ab707fd0b372ecae09abc\">GetGeometryType</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a90e70723c8e2011efade4f8f292d0fcd\">GetPointPositionCount</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a46886a5f4f4a6d727e12b61316fffbbf\">GetPointPositions</a>(CDoubleArray &amp;out_points) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1518e5249e9cbc9b489758c8f42d80f8\">GetPolygonCount</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#afc7c4d0d6b954c667275cf5302cea1a2\">GetPolygonIndices</a>(CLongArray &amp;out_sizes, CLongArray &amp;out_indices) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#ab2f262f1df0eb3bdad001d8b1490754d\">GetSegmentCount</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#aa1fcef4f32bf290bf9309affaf0bfb68\">GetSegmentIndices</a>(CLongArray &amp;out_indices) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#af16a9c7af1fcb54401a1227e9dec7bae\">GetSubGeometry</a>(ULONG in_index) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a28f33a989da2fda9b0600b923c19cd3c\">GetSubGeometryCount</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a16ac89213569622fb00fe5e981fa2918\">GetTransformation</a>(XSI::MATH::CMatrix4f &amp;out_mat44) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a6df014e0773c54335e619f0e5c65ad27\">GetTriangleCount</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a3af79e96715bb4ad9e600644d5374e46\">GetTrianglePointIndices</a>(CLongArray &amp;out_indices) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a8ba7104f19642abbf575c4a5475ae5fe\">IsDirty</a>(unsigned short in_flag=siAnyDirtyState) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a>() const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a794883e61636653b8de04c16bdd26b44\">operator!=</a>(const CICEGeometry &amp;in_geom) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#abe308a04919d9ff3ed57535b221cc854\">operator=</a>(const CICEGeometry &amp;in_geom)</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1dcdb8358ea31624af3d9d50146353e2\">operator==</a>(const CICEGeometry &amp;in_geom) const </td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a79be0489b44a77620de069631265f22fa4990f4431660053845f6189e5e019198\">siAnyDirtyState</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a79be0489b44a77620de069631265f22fa434376409d26c467320b1d046435c72a\">siGeometryTypeDirtyState</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1d1cfd8ffb84e947f82999c682b666a7a24b0984b47f8d96bc3874357c001321d\">siGroupType</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1d1cfd8ffb84e947f82999c682b666a7a17989a42a25a20706d1f46c7473a68eb\">siMeshSurfaceType</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1d1cfd8ffb84e947f82999c682b666a7a503c885e8c07d491843923e6295252b5\">siNoneType</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1d1cfd8ffb84e947f82999c682b666a7a5d4d6d710d8c05c4ac2f89c690ad4207\">siNurbsCurveType</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1d1cfd8ffb84e947f82999c682b666a7a1a55b1710dffaec6e982fa6b9dd5d6e6\">siNurbsSurfaceType</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1d1cfd8ffb84e947f82999c682b666a7a732a272e8d93b3d9934f506ec7be4e42\">siPointCloudType</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a79be0489b44a77620de069631265f22fafda97d4337b4872babc8c6a9463c9e9c\">siPointPositionDirtyState</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a79be0489b44a77620de069631265f22fa9be0106c9503b862ed14f4a71fa8b956\">siTopologyDirtyState</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a79be0489b44a77620de069631265f22fa9ee491e427205139588b4ea649b4a00b\">siTransformationDirtyState</a> enum value</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#a1d1cfd8ffb84e947f82999c682b666a7\">Type</a> enum name</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html#ae8521998851caa6ea695fdb7070120d4\">~CICEGeometry</a>()</td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEGeometry.html\">CICEGeometry</a></td><td class=\"entry\"></td></tr>\n\
</table></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";