var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CUserDataArray Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1CUserDataArray.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CUserDataArray Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CUserDataArray Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__userdataarray_8h_source.html\">xsi_userdataarray.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>A <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> is an uni-dimensional array used to store binary values. <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> contains items of type CUserDataArray::Value which holds the data set on a user data map property. </p>\n\
<p>The array is-zero based, which means that the first item index is 0 and the larger index is one less that the number of elements contained in the array.</p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1UserDataMap.html#aad746dfe740a1ce3c817be2837c3e541\">UserDataMap::GetValues</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1UserDataMap.html#a1a82361f761ec3dacd39238a4a70c4e6\">UserDataMap::SetValues</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1UserDataMap.html#aa03660c328c133e710cce064b43323a7\">UserDataMap::SetFixedSizeValues</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>5.0</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd><div class=\"fragment\"><div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__application_8h.html\">xsi_application.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__userdatamap_8h.html\">xsi_userdatamap.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__userdataarray_8h.html\">xsi_userdataarray.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__x3dobject_8h.html\">xsi_x3dobject.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__model_8h.html\">xsi_model.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__primitive_8h.html\">xsi_primitive.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__geometry_8h.html\">xsi_geometry.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__polygonmesh_8h.html\">xsi_polygonmesh.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__clusterpropertybuilder_8h.html\">xsi_clusterpropertybuilder.h</a>&quot;</span></div>\n\
<div class=\"line\"><span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__geometryaccessor_8h.html\">xsi_geometryaccessor.h</a>&quot;</span></div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">Application app;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">Model root = app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a90b73ddc91605180a7d1ea4fa22014bf\">GetActiveSceneRoot</a>();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">X3DObject mySphere;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a0aa53709fda0b1b3de1cbdbfcd65445e\">AddGeometry</a>( L<span class=\"stringliteral\">&quot;Sphere&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, mySphere );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">PolygonMesh mesh = mySphere.GetActivePrimitive().GetGeometry();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Adds a user data map on a complete cluster vertices</span></div>\n\
<div class=\"line\">CClusterPropertyBuilder cpBuilder = mesh.GetClusterPropertyBuilder();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">UserDataMap udm = cpBuilder.AddUserDataMap(<a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#aeb91819cc41168e5c364275273e36080aa6bb9071d74d9a9d926adc5adde61606\">XSI::siClusterVertexType</a>);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Set the new property with user data on vertex 10, 20, 30</span></div>\n\
<div class=\"line\"><span class=\"keyword\">struct </span>FooData</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    FooData(<span class=\"keywordtype\">float</span> a,<span class=\"keywordtype\">float</span> b,<span class=\"keywordtype\">float</span> c) : x(a), y(b), z(c) {}</div>\n\
<div class=\"line\">    <span class=\"keywordtype\">float</span> x,y,z;</div>\n\
<div class=\"line\">};</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">FooData f1(10,10,10);</div>\n\
<div class=\"line\">FooData f2(20,20,20);</div>\n\
<div class=\"line\">FooData f3(30,30,30);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span>* fds[] =</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    (<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span>*)&amp;f1,</div>\n\
<div class=\"line\">    (<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span>*)&amp;f2,</div>\n\
<div class=\"line\">    (<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span>*)&amp;f3,</div>\n\
<div class=\"line\">};</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">LONG vtxIndices[] = {10,20,30};</div>\n\
<div class=\"line\">udm.SetFixedSizeValues( vtxIndices,</div>\n\
<div class=\"line\">                        (<span class=\"keyword\">const</span> <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span>**)fds,</div>\n\
<div class=\"line\">                        3,</div>\n\
<div class=\"line\">                        <span class=\"keyword\">sizeof</span>(FooData) );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Get all user data values from the user data map</span></div>\n\
<div class=\"line\">CGeometryAccessor ga = mesh.GetGeometryAccessor();</div>\n\
<div class=\"line\">CRefArray udmaps = ga.GetUserDataMaps( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#aeb91819cc41168e5c364275273e36080aa6bb9071d74d9a9d926adc5adde61606\">XSI::siClusterVertexType</a> );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"keywordflow\">for</span> (LONG i=0; i&lt;udmaps.GetCount(); i++)</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    udm = udmaps[i];</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a8ffdff30cb10b84c2419f99c6f2a5aac\">CUserDataArray</a> data;</div>\n\
<div class=\"line\">    udm.GetValues( data );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// Log all vertex user data</span></div>\n\
<div class=\"line\">    <span class=\"keywordflow\">for</span> (LONG j=0; j&lt;data.GetCount(); j++)</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        CUserDataArray::Value val = data[j];</div>\n\
<div class=\"line\">        FooData* pfd = (FooData*)val.m_pData;</div>\n\
<div class=\"line\">        if (pfd)</div>\n\
<div class=\"line\">        {</div>\n\
<div class=\"line\">            app.LogMessage( CString(L<span class=\"stringliteral\">&quot;FooData[&quot;</span>) + CString(j) + CString(L<span class=\"stringliteral\">&quot;]=&quot;</span>)</div>\n\
<div class=\"line\">                            + CString(pfd-&gt;x) + L<span class=\"stringliteral\">&quot;,&quot;</span></div>\n\
<div class=\"line\">                            + CString(pfd-&gt;y) + L<span class=\"stringliteral\">&quot;,&quot;</span></div>\n\
<div class=\"line\">                            + CString(pfd-&gt;z) );</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\">        {</div>\n\
<div class=\"line\">            app.LogMessage( CString(L<span class=\"stringliteral\">&quot;FooData[&quot;</span>) + CString(j) + CString(L<span class=\"stringliteral\">&quot;]=empty&quot;</span>) );</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\">}</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Get only the user data values set on the user data map</span></div>\n\
<div class=\"line\"><span class=\"keywordflow\">for</span> (LONG i=0; i&lt;udmaps.GetCount(); i++)</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    udm = udmaps[i];</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a8ffdff30cb10b84c2419f99c6f2a5aac\">CUserDataArray</a> data;</div>\n\
<div class=\"line\">    CBitArray flags;</div>\n\
<div class=\"line\">    udm.GetValues( data, flags );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// Log only the vertex with user data</span></div>\n\
<div class=\"line\">    LONG j = flags.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CBitArray.html#a771607a08d7091a372d8f3fc4d1e9b5c\">GetIterator</a>();</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">while</span> (flags.GetNextTrueBit(j))</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        CUserDataArray::Value val = data[j];</div>\n\
<div class=\"line\">        FooData* pfd = (FooData*)val.m_pData;</div>\n\
<div class=\"line\">        app.LogMessage( CString(L<span class=\"stringliteral\">&quot;FooData[&quot;</span>) + CString(j) + CString(L<span class=\"stringliteral\">&quot;]=&quot;</span>)</div>\n\
<div class=\"line\">                        + CString(pfd-&gt;x) + L<span class=\"stringliteral\">&quot;,&quot;</span></div>\n\
<div class=\"line\">                        + CString(pfd-&gt;y) + L<span class=\"stringliteral\">&quot;,&quot;</span></div>\n\
<div class=\"line\">                        + CString(pfd-&gt;z) );</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\">}</div>\n\
</div><!-- fragment --> </dd></dl>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a8ffdff30cb10b84c2419f99c6f2a5aac\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a8ffdff30cb10b84c2419f99c6f2a5aac\">CUserDataArray</a> (LONG in_size=0)</td></tr>\n\
<tr class=\"separator:a8ffdff30cb10b84c2419f99c6f2a5aac\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a098432c622c79f0cc824cb237ebb6800\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a098432c622c79f0cc824cb237ebb6800\">CUserDataArray</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;in_array)</td></tr>\n\
<tr class=\"separator:a098432c622c79f0cc824cb237ebb6800\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2a13b34c71d7334735ff9ecf55334e45\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a2a13b34c71d7334735ff9ecf55334e45\">~CUserDataArray</a> ()</td></tr>\n\
<tr class=\"separator:a2a13b34c71d7334735ff9ecf55334e45\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2a260bd5e00b18f3c79956db8d2b4838\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a2a260bd5e00b18f3c79956db8d2b4838\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;in_array)</td></tr>\n\
<tr class=\"separator:a2a260bd5e00b18f3c79956db8d2b4838\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a845aa1e5063b24aedec1a99da2d8a4f3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a845aa1e5063b24aedec1a99da2d8a4f3\">GetCount</a> () const </td></tr>\n\
<tr class=\"separator:a845aa1e5063b24aedec1a99da2d8a4f3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a44f2538daabc6812f4bb2e373954b44e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a44f2538daabc6812f4bb2e373954b44e\">Add</a> (const CUserDataArray::Value &amp;in_val)</td></tr>\n\
<tr class=\"separator:a44f2538daabc6812f4bb2e373954b44e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af91f0dee1a2a4d9fb7c8c3bc827199b7\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#af91f0dee1a2a4d9fb7c8c3bc827199b7\">Clear</a> ()</td></tr>\n\
<tr class=\"separator:af91f0dee1a2a4d9fb7c8c3bc827199b7\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a97599ffb24626fe615ad31b40cf1a29f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a97599ffb24626fe615ad31b40cf1a29f\">Resize</a> (LONG in_size)</td></tr>\n\
<tr class=\"separator:a97599ffb24626fe615ad31b40cf1a29f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad1ea27fddd57b140fdb07227c70e57ed\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const CUserDataArray::Value &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#ad1ea27fddd57b140fdb07227c70e57ed\">operator[]</a> (LONG in_index) const </td></tr>\n\
<tr class=\"separator:ad1ea27fddd57b140fdb07227c70e57ed\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab88e5ce4ca03e06efa35b81c5077e361\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">CUserDataArray::Value &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#ab88e5ce4ca03e06efa35b81c5077e361\">operator[]</a> (LONG in_index)</td></tr>\n\
<tr class=\"separator:ab88e5ce4ca03e06efa35b81c5077e361\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a383bbf74702a8873477d4a17ee0a234f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a383bbf74702a8873477d4a17ee0a234f\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;in_array) const </td></tr>\n\
<tr class=\"separator:a383bbf74702a8873477d4a17ee0a234f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0f5d1678a4afb47fba2ef9a7dd24ffc3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html#a0f5d1678a4afb47fba2ef9a7dd24ffc3\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;in_array) const </td></tr>\n\
<tr class=\"separator:a0f5d1678a4afb47fba2ef9a7dd24ffc3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a8ffdff30cb10b84c2419f99c6f2a5aac\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_size</em> = <code>0</code></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructs a <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> and optionally initializes the array to a known size. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_size</td><td>Size of array, defaults to 0. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a098432c622c79f0cc824cb237ebb6800\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_array</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructs a <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> object from another <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_array</td><td>constant <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a2a13b34c71d7334735ff9ecf55334e45\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a2a260bd5e00b18f3c79956db8d2b4838\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_array</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Assignment operator. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_array</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this array. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a845aa1e5063b24aedec1a99da2d8a4f3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the number of items in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The number of items in the array. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a44f2538daabc6812f4bb2e373954b44e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Add </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const CUserDataArray::Value &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_val</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Adds a value to the end of this array. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_val</td><td>The new value. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af91f0dee1a2a4d9fb7c8c3bc827199b7\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Clear </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Erases all elements contained in the array. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a97599ffb24626fe615ad31b40cf1a29f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Resize </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_size</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Reallocates memory for the array, preserves its contents if new new size is larger than existing size. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_size</td><td>New size of the array. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281dad795f6709d0c6419c4fe31703e454e27\">CStatus::InvalidArgument</a> in_size &lt; 0 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad1ea27fddd57b140fdb07227c70e57ed\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">const CUserDataArray::Value&amp; operator[] </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_index</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Accessor to elements at a given index. This function can only be called by constant objects, the returned value is read-only. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_index</td><td>index in this zero based array.The index must be smaller than the number of element in the array, otherwise the results are unpredicted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A read only reference to the indexed item. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab88e5ce4ca03e06efa35b81c5077e361\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">CUserDataArray::Value&amp; operator[] </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_index</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Accessor to elements at a given index. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_index</td><td>index in this zero based array.The index must be smaller than the number of element in the array, otherwise the results are unpredicted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to the indexed item. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a383bbf74702a8873477d4a17ee0a234f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool operator== </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_array</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Equality operator. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_array</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> to compare with. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if in_array contains the same number of elements as this array and that all members of in_array are equal to the corresponding one contained in this array. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0f5d1678a4afb47fba2ef9a7dd24ffc3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool operator!= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\">CUserDataArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_array</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Inequality operator. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_array</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CUserDataArray.html\" title=\"A CUserDataArray is an uni-dimensional array used to store binary values. CUserDataArray contains ite...\">CUserDataArray</a> to compare with. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if one member of in_array is different of the corresponding members in this array or if the arrays are not of the same size. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__userdataarray_8h_source.html\">xsi_userdataarray.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";