var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CMatrix3f Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1MATH_1_1CMatrix3f.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CMatrix3f Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CMatrix3f Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__matrix3f_8h_source.html\">xsi_matrix3f.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>A class to represent a single precision floating point 3 by 3 matrix. This class is typically used for implementing custom ICE nodes. </p>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a8bea93fd1ad5b6f616827e50baef8813\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a8bea93fd1ad5b6f616827e50baef8813\">CMatrix3f</a> ()</td></tr>\n\
<tr class=\"separator:a8bea93fd1ad5b6f616827e50baef8813\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8a41a5f51fc09db242d927b869c7dc84\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a8a41a5f51fc09db242d927b869c7dc84\">CMatrix3f</a> (float in_00, float in_01, float in_02, float in_10, float in_11, float in_12, float in_20, float in_21, float in_22)</td></tr>\n\
<tr class=\"separator:a8a41a5f51fc09db242d927b869c7dc84\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7f50062f2786eedf10fda53740649738\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a7f50062f2786eedf10fda53740649738\">CMatrix3f</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a7f50062f2786eedf10fda53740649738\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9f53bcea592063a86ff4c8b3519e6742\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a9f53bcea592063a86ff4c8b3519e6742\">~CMatrix3f</a> ()</td></tr>\n\
<tr class=\"separator:a9f53bcea592063a86ff4c8b3519e6742\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6036995c1e2156ed51d2fc4158bbaba6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a6036995c1e2156ed51d2fc4158bbaba6\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a6036995c1e2156ed51d2fc4158bbaba6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab831d133007cef2b507cf4df239bacc7\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#ab831d133007cef2b507cf4df239bacc7\">operator*=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:ab831d133007cef2b507cf4df239bacc7\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a830fbbf3e3a8e46bdeea87c31874e894\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a830fbbf3e3a8e46bdeea87c31874e894\">SetIdentity</a> ()</td></tr>\n\
<tr class=\"separator:a830fbbf3e3a8e46bdeea87c31874e894\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1c2ad61453ffa550095af8989130f295\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a1c2ad61453ffa550095af8989130f295\">Invert</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a1c2ad61453ffa550095af8989130f295\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad6f5eef9c6bf37cc8aa99faa6c6ab3e4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#ad6f5eef9c6bf37cc8aa99faa6c6ab3e4\">TransposeInverseInPlace</a> ()</td></tr>\n\
<tr class=\"separator:ad6f5eef9c6bf37cc8aa99faa6c6ab3e4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3d3338dea9ea11f63a54812850852ca2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a3d3338dea9ea11f63a54812850852ca2\">TransposeInverse</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a3d3338dea9ea11f63a54812850852ca2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abf33a1c0005458a7c27ca7b308c9787c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#abf33a1c0005458a7c27ca7b308c9787c\">TransposeInPlace</a> ()</td></tr>\n\
<tr class=\"separator:abf33a1c0005458a7c27ca7b308c9787c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a45db8a2a955ff945c9e8bb936495e74f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a45db8a2a955ff945c9e8bb936495e74f\">Transpose</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a45db8a2a955ff945c9e8bb936495e74f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a29e7d20fd28a0aa83186208172a7af94\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a29e7d20fd28a0aa83186208172a7af94\">MulInPlace</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3)</td></tr>\n\
<tr class=\"separator:a29e7d20fd28a0aa83186208172a7af94\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ada5d3e396c6d8dc5266c392fd1246976\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#ada5d3e396c6d8dc5266c392fd1246976\">Mul</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3A, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3B)</td></tr>\n\
<tr class=\"separator:ada5d3e396c6d8dc5266c392fd1246976\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab21477f817f9f95e5ea8ec890c5ad050\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#ab21477f817f9f95e5ea8ec890c5ad050\">Get</a> (float &amp;io_00, float &amp;io_01, float &amp;io_02, float &amp;io_10, float &amp;io_11, float &amp;io_12, float &amp;io_20, float &amp;io_21, float &amp;io_22) const </td></tr>\n\
<tr class=\"separator:ab21477f817f9f95e5ea8ec890c5ad050\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2c7e6ce4f37f32773f201816f9e260c4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a2c7e6ce4f37f32773f201816f9e260c4\">Set</a> (float in_00, float in_01, float in_02, float in_10, float in_11, float in_12, float in_20, float in_21, float in_22)</td></tr>\n\
<tr class=\"separator:a2c7e6ce4f37f32773f201816f9e260c4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa3ee8fae12881af4cd7867a53e90d9f4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#aa3ee8fae12881af4cd7867a53e90d9f4\">Set</a> (const float in_Val[3][3])</td></tr>\n\
<tr class=\"separator:aa3ee8fae12881af4cd7867a53e90d9f4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a86c53511ca1a82d57c966afa5a9b8fcc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE float *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a86c53511ca1a82d57c966afa5a9b8fcc\">Get</a> ()</td></tr>\n\
<tr class=\"separator:a86c53511ca1a82d57c966afa5a9b8fcc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a79390b5dc626cf75ab5aa8ccf5f5b94e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a79390b5dc626cf75ab5aa8ccf5f5b94e\">GetValue</a> (short in_sRow, short in_sCol) const </td></tr>\n\
<tr class=\"separator:a79390b5dc626cf75ab5aa8ccf5f5b94e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0a4f42972ece314a61f461f9ed82f814\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a0a4f42972ece314a61f461f9ed82f814\">SetValue</a> (short in_sRow, short in_sCol, float in_Val)</td></tr>\n\
<tr class=\"separator:a0a4f42972ece314a61f461f9ed82f814\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af53444079253420028fe23aa9e01291f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#af53444079253420028fe23aa9e01291f\">EpsilonEquals</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3, float in_Epsilon) const </td></tr>\n\
<tr class=\"separator:af53444079253420028fe23aa9e01291f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8a8c8e92bc1019f5198214cbaab2e660\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a8a8c8e92bc1019f5198214cbaab2e660\">Equals</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3) const </td></tr>\n\
<tr class=\"separator:a8a8c8e92bc1019f5198214cbaab2e660\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7b397c4c234ad20daf33dc5a84b440b2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a7b397c4c234ad20daf33dc5a84b440b2\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3) const </td></tr>\n\
<tr class=\"separator:a7b397c4c234ad20daf33dc5a84b440b2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acf0313bec280fe509b60ac4c402eb566\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#acf0313bec280fe509b60ac4c402eb566\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3) const </td></tr>\n\
<tr class=\"separator:acf0313bec280fe509b60ac4c402eb566\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa1df576280517699a4f713f69dda2704\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#aa1df576280517699a4f713f69dda2704\">operator&lt;</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;in_matrix3) const </td></tr>\n\
<tr class=\"separator:aa1df576280517699a4f713f69dda2704\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a502ed25c91c663225bbb8d7b4e6c4732\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">SICPPSDK_INLINE const float *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a502ed25c91c663225bbb8d7b4e6c4732\">Get</a> () const </td></tr>\n\
<tr class=\"separator:a502ed25c91c663225bbb8d7b4e6c4732\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a8bea93fd1ad5b6f616827e50baef8813\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8a41a5f51fc09db242d927b869c7dc84\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_00</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_01</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_02</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_10</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_11</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_12</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_20</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_21</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_22</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_00</td><td>Value to set in this matrix[0,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_01</td><td>Value to set in this matrix[0,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_02</td><td>Value to set in this matrix[0,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_10</td><td>Value to set in this matrix[1,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_11</td><td>Value to set in this matrix[1,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_12</td><td>Value to set in this matrix[1,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_20</td><td>Value to set in this matrix[2,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_21</td><td>Value to set in this matrix[2,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_22</td><td>Value to set in this matrix[2,2]. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7f50062f2786eedf10fda53740649738\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9f53bcea592063a86ff4c8b3519e6742\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE ~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a6036995c1e2156ed51d2fc4158bbaba6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Assignment operator. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3&amp;</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab831d133007cef2b507cf4df239bacc7\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp; operator*= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Right-multiplies this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object by in_matrix3 and stores the result in the same <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object (this = this * in_matrix3) </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Matrix to be multiplied with. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a29e7d20fd28a0aa83186208172a7af94\">CMatrix3f::MulInPlace</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a830fbbf3e3a8e46bdeea87c31874e894\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp; SetIdentity </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object to the identity matrix (this = id). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1c2ad61453ffa550095af8989130f295\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool Invert </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Inverts this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object (if not singular) (this = this^-1). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Matrix to be inverted. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object has been inverted (not singular), else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad6f5eef9c6bf37cc8aa99faa6c6ab3e4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool TransposeInverseInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object to the transpose of the inverse of itself (if not singular) (this = Transpose(this^-1)). </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object has been inverted (not singular), else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3d3338dea9ea11f63a54812850852ca2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool TransposeInverse </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object to the transpose of the inverse of the input matrix (if not singular) (this = Transpose(in_matrix3^-1)). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object to be inversed and transposed. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object has been inverted (not singular), else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abf33a1c0005458a7c27ca7b308c9787c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void TransposeInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Transposes this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object in place (this = Transpose(this)). </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a45db8a2a955ff945c9e8bb936495e74f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Transpose </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Transposes the specified matrix and stores the result in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object (this = Transpose(in_matrix3)). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>matrix to be inversed and transposed. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a29e7d20fd28a0aa83186208172a7af94\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp; MulInPlace </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Right-multiplies this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object by in_matrix3 and stores the result in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object (this = this * in_matrix3). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>matrix to be multiplied with. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ada5d3e396c6d8dc5266c392fd1246976\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp; Mul </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3A</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3B</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Right-multiplies in_matrix3A by in_matrix3B and stores the result in this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object (this = in_matrix3A * in_matrix3B). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3A</td><td>matrix </td></tr>\n\
    <tr><td class=\"paramname\">in_matrix3B</td><td>matrix </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a>&amp; A reference to the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object which contains the result of the multiplication. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab21477f817f9f95e5ea8ec890c5ad050\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Get </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_00</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_01</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_02</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_10</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_11</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_12</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_20</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_21</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>io_22</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the 9 components of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">io_00</td><td>Value of this matrix[0,0]. </td></tr>\n\
    <tr><td class=\"paramname\">io_01</td><td>Value of this matrix[0,1]. </td></tr>\n\
    <tr><td class=\"paramname\">io_02</td><td>Value of this matrix[0,2]. </td></tr>\n\
    <tr><td class=\"paramname\">io_10</td><td>Value of this matrix[1,0]. </td></tr>\n\
    <tr><td class=\"paramname\">io_11</td><td>Value of this matrix[1,1]. </td></tr>\n\
    <tr><td class=\"paramname\">io_12</td><td>Value of this matrix[1,2]. </td></tr>\n\
    <tr><td class=\"paramname\">io_20</td><td>Value of this matrix[2,0]. </td></tr>\n\
    <tr><td class=\"paramname\">io_21</td><td>Value of this matrix[2,1]. </td></tr>\n\
    <tr><td class=\"paramname\">io_22</td><td>Value of this matrix[2,2]. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a2c7e6ce4f37f32773f201816f9e260c4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Set </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_00</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_01</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_02</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_10</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_11</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_12</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_20</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_21</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_22</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the 9 components of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_00</td><td>Value to set to this matrix[0,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_01</td><td>Value to set to this matrix[0,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_02</td><td>Value to set to this matrix[0,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_10</td><td>Value to set to this matrix[1,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_11</td><td>Value to set to this matrix[1,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_12</td><td>Value to set to this matrix[1,2]. </td></tr>\n\
    <tr><td class=\"paramname\">in_20</td><td>Value to set to this matrix[2,0]. </td></tr>\n\
    <tr><td class=\"paramname\">in_21</td><td>Value to set to this matrix[2,1]. </td></tr>\n\
    <tr><td class=\"paramname\">in_22</td><td>Value to set to this matrix[2,2]. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa3ee8fae12881af4cd7867a53e90d9f4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void Set </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const float&#160;</td>\n\
          <td class=\"paramname\"><em>in_Val</em>[3][3]</td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the 9 components of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_Val</td><td>A 3x3 array of float values. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a86c53511ca1a82d57c966afa5a9b8fcc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE float * Get </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Gets a pointer to the internal matrix. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Pointer to matrix. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a79390b5dc626cf75ab5aa8ccf5f5b94e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE float GetValue </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sRow</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sCol</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the (i,j)th value of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_sRow</td><td>access to the i th row </td></tr>\n\
    <tr><td class=\"paramname\">in_sCol</td><td>access to the j th column </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The (i,j)th value of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0a4f42972ece314a61f461f9ed82f814\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE void SetValue </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sRow</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">short&#160;</td>\n\
          <td class=\"paramname\"><em>in_sCol</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_Val</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the (i,j)th value of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_sRow</td><td>access to the i th row </td></tr>\n\
    <tr><td class=\"paramname\">in_sCol</td><td>access to the j th column </td></tr>\n\
    <tr><td class=\"paramname\">in_Val</td><td>new value </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"af53444079253420028fe23aa9e01291f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool EpsilonEquals </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>in_Epsilon</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Tests the equality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object with the specified matrix, with a tolerance of Epsilon. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix. </td></tr>\n\
    <tr><td class=\"paramname\">in_Epsilon</td><td>Error margin Possible Values: [0, +INF[ should be a positive value </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8a8c8e92bc1019f5198214cbaab2e660\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool Equals </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Tests the strict equality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object with the specified matrix. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7b397c4c234ad20daf33dc5a84b440b2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator== </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Equality operator. Tests the strict equality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object with the specified matrix. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix3. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a8a8c8e92bc1019f5198214cbaab2e660\">CMatrix3f::Equals</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acf0313bec280fe509b60ac4c402eb566\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator!= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Inequality operator. Tests the strict inequality of this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> object with the specified matrix. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td>Operand matrix. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if equal else false. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html#a8a8c8e92bc1019f5198214cbaab2e660\">CMatrix3f::Equals</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa1df576280517699a4f713f69dda2704\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE bool operator&lt; </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\">CMatrix3f</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_matrix3</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Less than operator. Performs a comparison with a specified <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> to determine if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> is less than the specified <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a>. The comparison is arbitrary and not geometrically meaningful, it\'s only purpose is to make CMAtrix3ff compliant with stl for sorting operations. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_matrix3</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> to compare. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a> is less than the specified <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix3f.html\" title=\"A class to represent a single precision floating point 3 by 3 matrix. This class is typically used fo...\">CMatrix3f</a>, false otherwise. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>7.5 </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a502ed25c91c663225bbb8d7b4e6c4732\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">SICPPSDK_INLINE const float * Get </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Gets a pointer to the const version of the internal matrix. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Pointer to const matrix. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>11.0 (2013) </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__matrix3f_8h_source.html\">xsi_matrix3f.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";