var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CPointRefArray Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1CPointRefArray.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CPointRefArray Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CPointRefArray Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__point_8h_source.html\">xsi_point.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>An array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> objects that represent the points in the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Geometry.html\" title=\"The Geometry class gives access to a X3DObject&#39;s geometry. Geometry is the base class for specific ge...\">Geometry</a>. </p>\n\
<dl class=\"section warning\"><dt>Warning</dt><dd>This specialized array is returned by <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Geometry.html#a811d3648a75a4eccea18f644e10ba31d\">Geometry::GetPoints</a>, it is not meant to be created and modified in user-defined functions. If you want to add and remove arbitrary items to a collection, you must use a <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\" title=\"The CRefArray class holds generic CRef objects and acts as a base class for other specialized CRef ar...\">CRefArray</a> instead.</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd></dd></dl>\n\
<div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"><span class=\"keyword\">using namespace </span>MATH;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a90b73ddc91605180a7d1ea4fa22014bf\">GetActiveSceneRoot</a>();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> myGrid;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a0aa53709fda0b1b3de1cbdbfcd65445e\">AddGeometry</a>( L<span class=\"stringliteral\">&quot;Grid&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, myGrid );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Geometry.html\">Geometry</a> geom = myGrid.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a8a39851003f7f789e90481dddc6253dc\">GetActivePrimitive</a>().<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Primitive.html#a54a307411fedb54e38a833083056162a\">GetGeometry</a>(0);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\">CPointRefArray</a> points( geom.GetPoints() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> val(points.GetCount());</div>\n\
<div class=\"line\">app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;Number of points: &quot;</span>) + val.GetAsText() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"keywordflow\">for</span>(LONG i = 0; i &lt; points.GetCount();  ++i)</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\">Point</a> pt(points[i]);</div>\n\
<div class=\"line\">    CVector3 pos( pt.GetPosition() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>(</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(pos.GetX()).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() + L<span class=\"stringliteral\">&quot;,&quot;</span> +</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(pos.GetY()).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() + L<span class=\"stringliteral\">&quot;,&quot;</span> +</div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(pos.GetZ()).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() );</div>\n\
<div class=\"line\">}</div>\n\
</div><!-- fragment --> </div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"closed.png\" alt=\"+\"> Inheritance diagram for CPointRefArray:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"classXSI_1_1CPointRefArray.png\" usemap=\"#CPointRefArray_map\" alt=\"\">\n\
  <map id=\"CPointRefArray_map\" name=\"CPointRefArray_map\">\n\
<area href=\"classXSI_1_1CRefArray.html\" title=\"The CRefArray class holds generic CRef objects and acts as a base class for other specialized CRef ar...\" alt=\"CRefArray\" shape=\"rect\" coords=\"76,0,218,24\">\n\
<area href=\"classXSI_1_1CControlPointRefArray.html\" title=\"An array of ControlPoint object references representing the NurbsCurve or NurbsSurface control points...\" alt=\"CControlPointRefArray\" shape=\"rect\" coords=\"0,112,142,136\">\n\
<area href=\"classXSI_1_1CVertexRefArray.html\" title=\"Represents an array of Vertex objects. \" alt=\"CVertexRefArray\" shape=\"rect\" coords=\"152,112,294,136\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:aff2ce0a5629080a2700b065137437fa6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#aff2ce0a5629080a2700b065137437fa6\">CPointRefArray</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\">CPointRefArray</a> &amp;in_array)</td></tr>\n\
<tr class=\"separator:aff2ce0a5629080a2700b065137437fa6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aadd1f10944ec7c05a35c1548b502d7e1\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#aadd1f10944ec7c05a35c1548b502d7e1\">GetItem</a> (LONG in_index) const </td></tr>\n\
<tr class=\"separator:aadd1f10944ec7c05a35c1548b502d7e1\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a49bf157eaa382bff464f5a5d8dacd6ff\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#a49bf157eaa382bff464f5a5d8dacd6ff\">GetItem</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_name) const </td></tr>\n\
<tr class=\"separator:a49bf157eaa382bff464f5a5d8dacd6ff\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a845aa1e5063b24aedec1a99da2d8a4f3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#a845aa1e5063b24aedec1a99da2d8a4f3\">GetCount</a> () const </td></tr>\n\
<tr class=\"separator:a845aa1e5063b24aedec1a99da2d8a4f3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa8720abaf6972d6dac22a8cd1a67225\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a> () const </td></tr>\n\
<tr class=\"separator:afa8720abaf6972d6dac22a8cd1a67225\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aaa61862b3d8da370ea69b9dbdb06b97d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3Array.html\">MATH::CVector3Array</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#aaa61862b3d8da370ea69b9dbdb06b97d\">GetPositionArray</a> () const </td></tr>\n\
<tr class=\"separator:aaa61862b3d8da370ea69b9dbdb06b97d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acd4269d0f53422d641d3b16ec8ffb568\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#acd4269d0f53422d641d3b16ec8ffb568\">PutPositionArray</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3Array.html\">MATH::CVector3Array</a> &amp;in_points)</td></tr>\n\
<tr class=\"separator:acd4269d0f53422d641d3b16ec8ffb568\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab90c57a28492b2d5b490df882fa72f5e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3Array.html\">MATH::CVector3Array</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#ab90c57a28492b2d5b490df882fa72f5e\">GetNormalArray</a> () const </td></tr>\n\
<tr class=\"separator:ab90c57a28492b2d5b490df882fa72f5e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab4fde8a2050e5834a751cbdf8e9d0a3f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#ab4fde8a2050e5834a751cbdf8e9d0a3f\">GetIndexArray</a> () const </td></tr>\n\
<tr class=\"separator:ab4fde8a2050e5834a751cbdf8e9d0a3f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a975ed2daa5104b0cbf5d4d58a0ca5e4d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\">SubComponent</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#a975ed2daa5104b0cbf5d4d58a0ca5e4d\">GetSubComponent</a> () const </td></tr>\n\
<tr class=\"separator:a975ed2daa5104b0cbf5d4d58a0ca5e4d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0ac725b96410e3d50bdf70fbdd193bcb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\">CPointRefArray</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html#a0ac725b96410e3d50bdf70fbdd193bcb\">Navigate</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a334ced880a64fec1d3f9db910b789e1c\">siNavigateComponentType</a> in_siNavigate) const </td></tr>\n\
<tr class=\"separator:a0ac725b96410e3d50bdf70fbdd193bcb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1CRefArray\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1CRefArray\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a></td></tr>\n\
<tr class=\"memitem:ad942d47f2fc5488491eab1b6c2a3f527 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#ad942d47f2fc5488491eab1b6c2a3f527\">CRefArray</a> (LONG in_lSize=0)</td></tr>\n\
<tr class=\"separator:ad942d47f2fc5488491eab1b6c2a3f527 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aadbe7c020bc7cd2807958a3e03144da6 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#aadbe7c020bc7cd2807958a3e03144da6\">CRefArray</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_refArray)</td></tr>\n\
<tr class=\"separator:aadbe7c020bc7cd2807958a3e03144da6 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1b0f9457402865643a9f7a1cf33c707d inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a1b0f9457402865643a9f7a1cf33c707d\">~CRefArray</a> ()</td></tr>\n\
<tr class=\"separator:a1b0f9457402865643a9f7a1cf33c707d inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a578bdcdee20c7e76626cc81f8cfb4d34 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a578bdcdee20c7e76626cc81f8cfb4d34\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_refArray)</td></tr>\n\
<tr class=\"separator:a578bdcdee20c7e76626cc81f8cfb4d34 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a82e1ed16d1f3208c61b60b8a8846cd7f inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a82e1ed16d1f3208c61b60b8a8846cd7f\">operator+=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_refArray)</td></tr>\n\
<tr class=\"separator:a82e1ed16d1f3208c61b60b8a8846cd7f inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a332ce71dcafd67d265df9fb12481daa7 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a332ce71dcafd67d265df9fb12481daa7\">operator[]</a> (LONG in_index) const </td></tr>\n\
<tr class=\"separator:a332ce71dcafd67d265df9fb12481daa7 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a44c1e5a45c3aeaa1217adc6fbaeccc4e inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a44c1e5a45c3aeaa1217adc6fbaeccc4e\">operator[]</a> (LONG in_index)</td></tr>\n\
<tr class=\"separator:a44c1e5a45c3aeaa1217adc6fbaeccc4e inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6e17e1b3670289fcb09943e75a934fb9 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a6e17e1b3670289fcb09943e75a934fb9\">Add</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_item)</td></tr>\n\
<tr class=\"separator:a6e17e1b3670289fcb09943e75a934fb9 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af61b38a30d8bab877beebad331601094 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#af61b38a30d8bab877beebad331601094\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_classID) const </td></tr>\n\
<tr class=\"separator:af61b38a30d8bab877beebad331601094 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#ac347619969a79eb8afc0adf6ea9394ba\">GetClassIDName</a> () const </td></tr>\n\
<tr class=\"separator:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa385aa18f5e42db5a415c25a90f4193d inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#aa385aa18f5e42db5a415c25a90f4193d\">operator bool</a> () const </td></tr>\n\
<tr class=\"separator:aa385aa18f5e42db5a415c25a90f4193d inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af52af7957fb07a15210e51faba4176c8 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#af52af7957fb07a15210e51faba4176c8\">Filter</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_strType, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a> &amp;in_strFam, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_strObjName, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;io_array) const </td></tr>\n\
<tr class=\"separator:af52af7957fb07a15210e51faba4176c8 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a75676e362da2004576788d05c8cbeb4c inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a75676e362da2004576788d05c8cbeb4c\">Find</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_strType, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;io_obj) const </td></tr>\n\
<tr class=\"separator:a75676e362da2004576788d05c8cbeb4c inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acb58b1fecf704752ebcf59a50444cf37 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#acb58b1fecf704752ebcf59a50444cf37\">Set</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> &amp;in_valarray)</td></tr>\n\
<tr class=\"separator:acb58b1fecf704752ebcf59a50444cf37 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8e9fcb3f49aa0647625c63badb5d5cda inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a8e9fcb3f49aa0647625c63badb5d5cda\">Set</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_strarray, const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_sep=L&quot;,&quot;)</td></tr>\n\
<tr class=\"separator:a8e9fcb3f49aa0647625c63badb5d5cda inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a553f83804976fcf663a4b65adb905cc6 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a553f83804976fcf663a4b65adb905cc6\">Remove</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a553f83804976fcf663a4b65adb905cc6 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a666736fbd0ebb8dc7e6ff3392423d6c0 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a666736fbd0ebb8dc7e6ff3392423d6c0\">Clear</a> (void)</td></tr>\n\
<tr class=\"separator:a666736fbd0ebb8dc7e6ff3392423d6c0 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa6bc9a7b39751a8415262efb422a87b3 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a> () const </td></tr>\n\
<tr class=\"separator:aa6bc9a7b39751a8415262efb422a87b3 inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a97599ffb24626fe615ad31b40cf1a29f inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a97599ffb24626fe615ad31b40cf1a29f\">Resize</a> (LONG in_size)</td></tr>\n\
<tr class=\"separator:a97599ffb24626fe615ad31b40cf1a29f inherit pub_methods_classXSI_1_1CRefArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"aff2ce0a5629080a2700b065137437fa6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\">CPointRefArray</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\">CPointRefArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_array</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy onstructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_array</td><td>constant <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\" title=\"An array of Point objects that represent the points in the Geometry. \">CPointRefArray</a> reference object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"aadd1f10944ec7c05a35c1548b502d7e1\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> GetItem </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_index</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns a reference to the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> object at a specified index in the array. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_index</td><td>The index of the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a>. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> reference object. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a52d3e64b2147598316a824665e587f85\">CRefArray</a>.</p>\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html#aadd1f10944ec7c05a35c1548b502d7e1\">CVertexRefArray</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a49bf157eaa382bff464f5a5d8dacd6ff\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> GetItem </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_name</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns a reference to the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> object matching the specified index. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_name</td><td>The name of the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a>. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> reference object. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#ac291428eb08ba0567bf7601c6827f942\">CRefArray</a>.</p>\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html#a49bf157eaa382bff464f5a5d8dacd6ff\">CVertexRefArray</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a845aa1e5063b24aedec1a99da2d8a4f3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the number of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> objects in the array. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The number of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> objects. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a922e4c0f3b9c356806a07bd1f1b34736\">CRefArray</a>.</p>\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html#a845aa1e5063b24aedec1a99da2d8a4f3\">CVertexRefArray</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"afa8720abaf6972d6dac22a8cd1a67225\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool IsValid </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if this array is a valid object or false otherwise. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if valid, false otherwise. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a1d57f75f79e9178bdd17e38a23720d56\">CRefArray</a>.</p>\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexRefArray.html#afa8720abaf6972d6dac22a8cd1a67225\">CVertexRefArray</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aaa61862b3d8da370ea69b9dbdb06b97d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3Array.html\">MATH::CVector3Array</a> GetPositionArray </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of positions expressed with CVector3 objects. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of CVector3 objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acd4269d0f53422d641d3b16ec8ffb568\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutPositionArray </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3Array.html\">MATH::CVector3Array</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_points</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the positions as an array of CVector3 objects. For non-custom operators this property can only be set if the object has been frozen. This operation is not undoable. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_points</td><td>An array of CVector3. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab90c57a28492b2d5b490df882fa72f5e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3Array.html\">MATH::CVector3Array</a> GetNormalArray </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of normals expressed with CVector3 objects. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>Array of CVector3 objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab4fde8a2050e5834a751cbdf8e9d0a3f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> GetIndexArray </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Return an array of indices in the geometry <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> array </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>An array of indices. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a975ed2daa5104b0cbf5d4d58a0ca5e4d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\">SubComponent</a> GetSubComponent </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates a <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\" title=\"Provides access to the subelements of an object&#39;s Geometry. \">SubComponent</a> object from this <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> array, </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1SubComponent.html\" title=\"Provides access to the subelements of an object&#39;s Geometry. \">SubComponent</a> object </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0ac725b96410e3d50bdf70fbdd193bcb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CPointRefArray.html\">CPointRefArray</a> Navigate </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a334ced880a64fec1d3f9db910b789e1c\">siNavigateComponentType</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_siNavigate</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Navigates the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> objects of the underlying geometry as specifed by the navigation component type. The function returns an array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> objects corresponding to each <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> object visited. Navigation is circular &ndash; for instance, navigating beyond the last component will return the first and vis versa. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_siNavigate</td><td>Type of direction for navigating the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> objects. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>An array of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Point.html\" title=\"A Point is a generic concept used to describe a Geometry&#39;s Vertex or ControlPoint. \">Point</a> objects. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__point_8h_source.html\">xsi_point.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";