var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CRenderHairAccessor Class Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1CRenderHairAccessor.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CRenderHairAccessor Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CRenderHairAccessor Class Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__renderhairaccessor_8h_source.html\">xsi_renderhairaccessor.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>This class provides access to the render hair information exposed by the hair primitive. This information includes: the vertex positions of each generated render hair, the root/tip radius values, the UVW, weight map and vertex color values for each render hair root location. </p>\n\
<p><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\" title=\"This class provides access to the render hair information exposed by the hair primitive. This information includes: the vertex positions of each generated render hair, the root/tip radius values, the UVW, weight map and vertex color values for each render hair root location. \">CRenderHairAccessor</a> provides a mechanism to access the data in chunks which allows you to optimize the memory allocation required for accessing such a large data set.</p>\n\
<p>Use <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1HairPrimitive.html#ac608f08bfc3985aa231a8d8c92aa5879\">HairPrimitive::GetRenderHairAccessor</a> to create an instance of <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\" title=\"This class provides access to the render hair information exposed by the hair primitive. This information includes: the vertex positions of each generated render hair, the root/tip radius values, the UVW, weight map and vertex color values for each render hair root location. \">CRenderHairAccessor</a>.</p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1HairPrimitive.html\" title=\"This class represents the primitive of an X3DObject used for simulating hair in Softimage and can be ...\">HairPrimitive</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>5.0</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd>This example demonstrates how to use the render hair accessor to extract the render hair data from a hair primitive. <div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Model.html\">Model</a> root = app.GetActiveSceneRoot();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// create a cone with hair along with a uv property</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> myCone;</div>\n\
<div class=\"line\">root.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a0aa53709fda0b1b3de1cbdbfcd65445e\">AddGeometry</a>( L<span class=\"stringliteral\">&quot;Cone&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>,L<span class=\"stringliteral\">&quot;myCone&quot;</span>,myCone);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Material.html\">Material</a> myMat;</div>\n\
<div class=\"line\">myCone.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SceneItem.html#aa9c1e83c510a0594487ed0839e31b3cc\">AddMaterial</a>(L<span class=\"stringliteral\">&quot;Phong&quot;</span>, <span class=\"keyword\">false</span>, L<span class=\"stringliteral\">&quot;myMat&quot;</span>, myMat);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Shader.html\">Shader</a> sh = myMat.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Shader.html#a48737456a289ce84d457c9a7061ecefd\">GetShaders</a>().<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html#a52d3e64b2147598316a824665e587f85\">GetItem</a>(0);</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> p = sh.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html#a7f92f91ca4d491c196b70e3a7f1574b2\">GetParameters</a>().<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CParameterRefArray.html#a434c8dadcc3af9367cf06934ef6dd339\">GetItem</a>(L<span class=\"stringliteral\">&quot;diffuse&quot;</span>);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// connect an image parameter and add a UV property on the diffuse param</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> newSource;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> prevSource;</div>\n\
<div class=\"line\">p.ConnectFromPreset( L<span class=\"stringliteral\">&quot;Image&quot;</span>, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a207a345ae4cc61904e92b1c3345e8527\">siTextureShaderFamily</a>, prevSource, newSource );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// creates a projection i.e. UV property</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> args(7);</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> outArg;</div>\n\
<div class=\"line\">args[0] = myCone.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">args[1] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;siTxtSpherical&quot;</span>);</div>\n\
<div class=\"line\">args[2] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;siTxtDefaultSpherical&quot;</span>);</div>\n\
<div class=\"line\">args[3] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>();</div>\n\
<div class=\"line\">args[4] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;Texture_Projection&quot;</span>);</div>\n\
<div class=\"line\">args[5] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>();</div>\n\
<div class=\"line\">args[6] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>((LONG)<a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ab38b5edd6e2cf13e41420399b1aa71a5a9c875a37091de0b62f8e08ae14ed259d\">XSI::siRelDefault</a>);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">app.ExecuteCommand( L<span class=\"stringliteral\">&quot;CreateProjection&quot;</span>, args, outArg );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// assign the projection to the cone</span></div>\n\
<div class=\"line\">args.Resize(3);</div>\n\
<div class=\"line\">args[0] = myCone.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">args[1] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;Sources.Materials.DefaultLib.myMat.Phong.Image.tspace_id&quot;</span>);</div>\n\
<div class=\"line\">args[2] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;Texture_Projection&quot;</span>);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">app.ExecuteCommand( L<span class=\"stringliteral\">&quot;SetInstanceDataValue&quot;</span>, args, outArg );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// add hair to the cone</span></div>\n\
<div class=\"line\">args.Resize(1);</div>\n\
<div class=\"line\">args[0] = myCone;</div>\n\
<div class=\"line\">app.ExecuteCommand( L<span class=\"stringliteral\">&quot;ApplyHairOp&quot;</span>, args, outArg ) ;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// transfer the uv property to the hair primitive</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> myHair = myCone.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html#a00af94c5bbae0b3d9384d11f2ac0f2ef\">FindChild</a>( L<span class=\"stringliteral\">&quot;Hair&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a>() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">args.Resize(2);</div>\n\
<div class=\"line\">args[0] = myHair.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1SIObject.html#ab5e38bc9c650b2d8ca0abe29b516cf87\">GetFullName</a>();</div>\n\
<div class=\"line\">args[1] = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot;myCone.polymsh.cls.Texture_Coordinates_AUTO.Texture_Projection&quot;</span>);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">app.ExecuteCommand( L<span class=\"stringliteral\">&quot;PropertyTransfer&quot;</span>, args, outArg ) ;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// setup a render hair accessor for 100 hairs with a chunk size of 10</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HairPrimitive.html\">HairPrimitive</a> myHairPrim( myHair.GetActivePrimitive() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> rha = myHairPrim.GetRenderHairAccessor( 100, 10 );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">LONG nReqChunkSize = rha.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#ab34e848afe148ec6d0dc6e109c038698\">GetRequestedChunkSize</a>();</div>\n\
<div class=\"line\">app.LogMessage( L<span class=\"stringliteral\">&quot;nReqChunkSize: &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(nReqChunkSize).GetAsText() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">LONG nReqHairCount = rha.GetRequestedHairCount();</div>\n\
<div class=\"line\">app.LogMessage( L<span class=\"stringliteral\">&quot;nReqHairCount: &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(nReqHairCount).GetAsText() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">LONG nUVs = rha.GetUVCount();</div>\n\
<div class=\"line\">app.LogMessage( L<span class=\"stringliteral\">&quot;nUVs: &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(nUVs).GetAsText() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// get the values in chunks</span></div>\n\
<div class=\"line\">LONG nChunk = 0;</div>\n\
<div class=\"line\">LONG i=0;</div>\n\
<div class=\"line\"><span class=\"keywordflow\">while</span>( rha.Next() )</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    app.LogMessage( L<span class=\"stringliteral\">&quot;Chunk: &quot;</span> + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(nChunk++).GetAsText() );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// get the number of vertices for each render hair</span></div>\n\
<div class=\"line\">    <span class=\"comment\">// note: this array is used for iterating over the render hair position</span></div>\n\
<div class=\"line\">    <span class=\"comment\">// and radius values</span></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> verticesCountArray;</div>\n\
<div class=\"line\">    rha.GetVerticesCount(verticesCountArray);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// get the render hair positions</span></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> posVals;</div>\n\
<div class=\"line\">    rha.GetVertexPositions(posVals);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    LONG k = 0;</div>\n\
<div class=\"line\">    app.LogMessage( L<span class=\"stringliteral\">&quot;Render hair position values: &quot;</span> );</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">for</span> (i=0; i&lt;verticesCountArray.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html#a845aa1e5063b24aedec1a99da2d8a4f3\">GetCount</a>(); i++ )</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        LONG nCount = verticesCountArray[i];</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">for</span> (LONG j=0; j&lt;nCount; j++ )</div>\n\
<div class=\"line\">        {</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> strVals;</div>\n\
<div class=\"line\">            strVals=</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(posVals[k++]).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot; &quot;</span>) +</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(posVals[k++]).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() + <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>(L<span class=\"stringliteral\">&quot; &quot;</span>) +</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(posVals[k++]).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() ;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">            app.LogMessage( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(i).GetAsText() + L<span class=\"stringliteral\">&quot;: &quot;</span> + strVals );</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// get the render hair radius</span></div>\n\
<div class=\"line\">    app.LogMessage( L<span class=\"stringliteral\">&quot;Render hair radius values: &quot;</span> );</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> radVals;</div>\n\
<div class=\"line\">    rha.GetVertexRadiusValues(radVals);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    k = 0;</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">for</span> (i=0; i&lt;verticesCountArray.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html#a845aa1e5063b24aedec1a99da2d8a4f3\">GetCount</a>(); i++ )</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        LONG nCount = verticesCountArray[i];</div>\n\
<div class=\"line\">        <span class=\"keywordflow\">for</span> (LONG j=0; j&lt;nCount; j++ )</div>\n\
<div class=\"line\">        {</div>\n\
<div class=\"line\">            app.LogMessage( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(i).GetAsText() + L<span class=\"stringliteral\">&quot;: &quot;</span> +</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(radVals[k++]).GetAsText() );</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <span class=\"comment\">// get the uv values</span></div>\n\
<div class=\"line\">    app.LogMessage( L<span class=\"stringliteral\">&quot;Render hair uv values: &quot;</span> );</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">for</span> (i=0; i&lt;nUVs; i++)</div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        app.LogMessage( L<span class=\"stringliteral\">&quot;    UV: &quot;</span> +  rha.GetUVName(i) );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">        <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> uvVals;</div>\n\
<div class=\"line\">        rha.GetUVValues( i, uvVals );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">        <span class=\"keywordflow\">for</span> (LONG j=0,k=0; j&lt;uvVals.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html#a845aa1e5063b24aedec1a99da2d8a4f3\">GetCount</a>(); j+=3, k++)</div>\n\
<div class=\"line\">        {</div>\n\
<div class=\"line\">            <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> strVals;</div>\n\
<div class=\"line\">            strVals =</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(uvVals[j+0]).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() + L<span class=\"stringliteral\">&quot; &quot;</span> +</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(uvVals[j+1]).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() + L<span class=\"stringliteral\">&quot; &quot;</span> +</div>\n\
<div class=\"line\">                <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(uvVals[j+2]).<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html#aa6bc9a7b39751a8415262efb422a87b3\">GetAsText</a>() ;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">            app.LogMessage( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>(k).GetAsText() + L<span class=\"stringliteral\">&quot;: &quot;</span> + strVals );</div>\n\
<div class=\"line\">        }</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\">}</div>\n\
</div><!-- fragment --> </dd></dl>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"closed.png\" alt=\"+\"> Inheritance diagram for CRenderHairAccessor:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"classXSI_1_1CRenderHairAccessor.png\" usemap=\"#CRenderHairAccessor_map\" alt=\"\">\n\
  <map id=\"CRenderHairAccessor_map\" name=\"CRenderHairAccessor_map\">\n\
<area href=\"classXSI_1_1CBase.html\" title=\"CBase is the base class of all API classes and provides access to Softimage objects through generic C...\" alt=\"CBase\" shape=\"rect\" coords=\"0,0,140,24\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a8697f7320da63432ac6611c095bf3645\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a8697f7320da63432ac6611c095bf3645\">CRenderHairAccessor</a> ()</td></tr>\n\
<tr class=\"separator:a8697f7320da63432ac6611c095bf3645\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6f6c9f0b724e4f76d27f2790bd028645\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a6f6c9f0b724e4f76d27f2790bd028645\">~CRenderHairAccessor</a> ()</td></tr>\n\
<tr class=\"separator:a6f6c9f0b724e4f76d27f2790bd028645\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a84fb82eb4321055140ce415f75300321\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a84fb82eb4321055140ce415f75300321\">CRenderHairAccessor</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a84fb82eb4321055140ce415f75300321\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9c7c906f84283bba95610139ad0a5ba2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a9c7c906f84283bba95610139ad0a5ba2\">CRenderHairAccessor</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a9c7c906f84283bba95610139ad0a5ba2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a6dd5a8a11eee55f434f151d1cd5d29d8\">IsA</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) const </td></tr>\n\
<tr class=\"separator:a6dd5a8a11eee55f434f151d1cd5d29d8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#acc34f4a01f2089e40f7abc7e9d98bf15\">GetClassID</a> () const </td></tr>\n\
<tr class=\"separator:acc34f4a01f2089e40f7abc7e9d98bf15\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7d2049f64690ba3e467d5d2954d193d6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a7d2049f64690ba3e467d5d2954d193d6\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a7d2049f64690ba3e467d5d2954d193d6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9dd2d26f15a5f4fc59a12886034b26fa\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a9dd2d26f15a5f4fc59a12886034b26fa\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref)</td></tr>\n\
<tr class=\"separator:a9dd2d26f15a5f4fc59a12886034b26fa\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3947d19ac087ef2cd68c2409920339c4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3947d19ac087ef2cd68c2409920339c4\">Next</a> ()</td></tr>\n\
<tr class=\"separator:a3947d19ac087ef2cd68c2409920339c4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae384fae184351d939e46e46b4bb98ec9\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#ae384fae184351d939e46e46b4bb98ec9\">Reset</a> ()</td></tr>\n\
<tr class=\"separator:ae384fae184351d939e46e46b4bb98ec9\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab34e848afe148ec6d0dc6e109c038698\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#ab34e848afe148ec6d0dc6e109c038698\">GetRequestedChunkSize</a> () const </td></tr>\n\
<tr class=\"separator:ab34e848afe148ec6d0dc6e109c038698\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa5f1637b915b1e890b8ea0d4744482e3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#aa5f1637b915b1e890b8ea0d4744482e3\">GetRequestedHairCount</a> () const </td></tr>\n\
<tr class=\"separator:aa5f1637b915b1e890b8ea0d4744482e3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3198c4c0cd132b18bfff960314ca48e0\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3198c4c0cd132b18bfff960314ca48e0\">GetChunkHairCount</a> () const </td></tr>\n\
<tr class=\"separator:a3198c4c0cd132b18bfff960314ca48e0\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7442706a0e77adbc3e5e76bb084a3d20\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a7442706a0e77adbc3e5e76bb084a3d20\">GetVerticesCount</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> &amp;out_values) const </td></tr>\n\
<tr class=\"separator:a7442706a0e77adbc3e5e76bb084a3d20\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a028bc4e68caa2f7f9c21b0ec70ea7597\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a028bc4e68caa2f7f9c21b0ec70ea7597\">GetVertexPositions</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;out_values) const </td></tr>\n\
<tr class=\"separator:a028bc4e68caa2f7f9c21b0ec70ea7597\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a01c98399e0901caeda3bd364d1540377\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a01c98399e0901caeda3bd364d1540377\">GetVertexRadiusValues</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;out_values) const </td></tr>\n\
<tr class=\"separator:a01c98399e0901caeda3bd364d1540377\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a52ae6d979eacc001399e2fd591d4205a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a52ae6d979eacc001399e2fd591d4205a\">GetHairSurfaceNormalValues</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;out_values) const </td></tr>\n\
<tr class=\"separator:a52ae6d979eacc001399e2fd591d4205a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a21c21b71c80cea99ea81dd6ba22bc16d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a21c21b71c80cea99ea81dd6ba22bc16d\">GetUVCount</a> () const </td></tr>\n\
<tr class=\"separator:a21c21b71c80cea99ea81dd6ba22bc16d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a20d88f332af39a861a0054d1a46d51f6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a20d88f332af39a861a0054d1a46d51f6\">GetVertexColorCount</a> () const </td></tr>\n\
<tr class=\"separator:a20d88f332af39a861a0054d1a46d51f6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7d4d82cb17069902c9864ec000eace69\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">LONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a7d4d82cb17069902c9864ec000eace69\">GetWeightMapCount</a> () const </td></tr>\n\
<tr class=\"separator:a7d4d82cb17069902c9864ec000eace69\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac0efa7696ba121c3a1a6df2fcc084672\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#ac0efa7696ba121c3a1a6df2fcc084672\">GetUVName</a> (LONG in_nIdx) const </td></tr>\n\
<tr class=\"separator:ac0efa7696ba121c3a1a6df2fcc084672\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a66b3d62352f065a2b0878be52d14444b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a66b3d62352f065a2b0878be52d14444b\">GetVertexColorName</a> (LONG in_nIdx) const </td></tr>\n\
<tr class=\"separator:a66b3d62352f065a2b0878be52d14444b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afd750c2d0f0facc5c1f4fb09cdc20d77\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#afd750c2d0f0facc5c1f4fb09cdc20d77\">GetWeightMapName</a> (LONG in_nIdx) const </td></tr>\n\
<tr class=\"separator:afd750c2d0f0facc5c1f4fb09cdc20d77\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a01b6713dd7ff9f4662f911d8a8036660\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a01b6713dd7ff9f4662f911d8a8036660\">GetUVValues</a> (LONG in_nIdx, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;out_values) const </td></tr>\n\
<tr class=\"separator:a01b6713dd7ff9f4662f911d8a8036660\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a21c8510e8e188ba07750380a244fb261\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a21c8510e8e188ba07750380a244fb261\">GetVertexColorValues</a> (LONG in_nIdx, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;out_values) const </td></tr>\n\
<tr class=\"separator:a21c8510e8e188ba07750380a244fb261\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a46bc187e9c98c00a9fb153ccc9cd08b9\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a46bc187e9c98c00a9fb153ccc9cd08b9\">GetWeightMapValues</a> (LONG in_nIdx, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;out_values) const </td></tr>\n\
<tr class=\"separator:a46bc187e9c98c00a9fb153ccc9cd08b9\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1CBase\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1CBase\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></td></tr>\n\
<tr class=\"memitem:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a3878f3ab13413eb6d4811dca38b4fa73\">CBase</a> ()</td></tr>\n\
<tr class=\"separator:a3878f3ab13413eb6d4811dca38b4fa73 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a012a4573399b53f0720fcf4ff787c048\">~CBase</a> ()</td></tr>\n\
<tr class=\"separator:a012a4573399b53f0720fcf4ff787c048 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac347619969a79eb8afc0adf6ea9394ba\">GetClassIDName</a> () const </td></tr>\n\
<tr class=\"separator:ac347619969a79eb8afc0adf6ea9394ba inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac8759bb33eaf8bf83949277169a048e6\">IsA</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_ref) const </td></tr>\n\
<tr class=\"separator:ac8759bb33eaf8bf83949277169a048e6 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a458e6e03ea0b71cb2205a5fd9e1999c8\">SetObject</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;in_obj)</td></tr>\n\
<tr class=\"separator:a458e6e03ea0b71cb2205a5fd9e1999c8 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#afa8720abaf6972d6dac22a8cd1a67225\">IsValid</a> () const </td></tr>\n\
<tr class=\"separator:afa8720abaf6972d6dac22a8cd1a67225 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac5a79b5ac1759bc4e66e8f662b8bad49\">ResetObject</a> ()</td></tr>\n\
<tr class=\"separator:ac5a79b5ac1759bc4e66e8f662b8bad49 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a20250592358718fccc1dad9e949d3d28\">operator CRef &amp;</a> ()</td></tr>\n\
<tr class=\"separator:a20250592358718fccc1dad9e949d3d28 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#ac91cdd4cb81fac44686c538126a4b98a\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:ac91cdd4cb81fac44686c538126a4b98a inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a99049c404ae9b0ae189f80771dee0596\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a> &amp;in_obj) const </td></tr>\n\
<tr class=\"separator:a99049c404ae9b0ae189f80771dee0596 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#aac2a77c9ccdd6d0f9953ef784e2be5e9\">GetRef</a> () const </td></tr>\n\
<tr class=\"separator:aac2a77c9ccdd6d0f9953ef784e2be5e9 inherit pub_methods_classXSI_1_1CBase\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a8697f7320da63432ac6611c095bf3645\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a6f6c9f0b724e4f76d27f2790bd028645\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Default destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a84fb82eb4321055140ce415f75300321\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant reference object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9c7c906f84283bba95610139ad0a5ba2\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Copy constructor. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a6dd5a8a11eee55f434f151d1cd5d29d8\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool IsA </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a>&#160;</td>\n\
          <td class=\"paramname\"><em>in_ClassID</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns true if a given class type is compatible with this API class. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ClassID</td><td>class type. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if the class is compatible, false otherwise. </dd></dl>\n\
\n\
<p>Reimplemented from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a5a1833349ed14be553ae68b84ff60b8d\">CBase</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"acc34f4a01f2089e40f7abc7e9d98bf15\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the type of the API class. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The class type. </dd></dl>\n\
\n\
<p>Implements <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html#a4b1359dd080cedb25e5f53df23d264b5\">CBase</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7d2049f64690ba3e467d5d2954d193d6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_obj</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from another object. The newly created object is set to empty if the input object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_obj</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\" title=\"This class provides access to the render hair information exposed by the hair primitive. This information includes: the vertex positions of each generated render hair, the root/tip radius values, the UVW, weight map and vertex color values for each render hair root location. \">CRenderHairAccessor</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9dd2d26f15a5f4fc59a12886034b26fa\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\">CRenderHairAccessor</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_ref</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Creates an object from a reference object. The newly created object is set to empty if the input reference object is not compatible. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_ref</td><td>constant class object. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The new <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html\" title=\"This class provides access to the render hair information exposed by the hair primitive. This information includes: the vertex positions of each generated render hair, the root/tip radius values, the UVW, weight map and vertex color values for each render hair root location. \">CRenderHairAccessor</a> object. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3947d19ac087ef2cd68c2409920339c4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool Next </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the accessor to the next available chunk of render hair data for reading. The position of the next chunk is computed based on the chunk size used for initializing the accessor. When the accessor is first initialized, there is no data available and <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3947d19ac087ef2cd68c2409920339c4\">CRenderHairAccessor::Next</a> has to be called to receive the first chunk of data.</p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>True if there is data to read or false otherwise.</dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#ae384fae184351d939e46e46b4bb98ec9\">CRenderHairAccessor::Reset</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1HairPrimitive.html#ac608f08bfc3985aa231a8d8c92aa5879\">HairPrimitive::GetRenderHairAccessor</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#ab34e848afe148ec6d0dc6e109c038698\">CRenderHairAccessor::GetRequestedChunkSize</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ae384fae184351d939e46e46b4bb98ec9\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Reset </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Sets the accessor to the first chunk of render hair data for reading. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> Success. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3947d19ac087ef2cd68c2409920339c4\">CRenderHairAccessor::Next</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab34e848afe148ec6d0dc6e109c038698\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetRequestedChunkSize </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the requested size of each render hair chunk. This number is always larger than or equal to the value returned from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3198c4c0cd132b18bfff960314ca48e0\">CRenderHairAccessor::GetChunkHairCount()</a>.</p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>long Chunk size. Returns -1 if the function fails.</dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3947d19ac087ef2cd68c2409920339c4\">CRenderHairAccessor::Next</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1HairPrimitive.html#ac608f08bfc3985aa231a8d8c92aa5879\">HairPrimitive::GetRenderHairAccessor</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3198c4c0cd132b18bfff960314ca48e0\">CRenderHairAccessor::GetChunkHairCount</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa5f1637b915b1e890b8ea0d4744482e3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetRequestedHairCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the maximum number of render hairs to access. This value is specified when the accessor is first created and does not correspond to the maximum number of render hairs available on the primitive.</p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>LONG Requested number of render hairs. Returns -1 if the function fails. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1HairPrimitive.html#ac608f08bfc3985aa231a8d8c92aa5879\">HairPrimitive::GetRenderHairAccessor</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3198c4c0cd132b18bfff960314ca48e0\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetChunkHairCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the number of render hairs available for the current chunk. If hairs have been trimmed due to cut or density maps, this number can be less than the requested chunk size, even zero.</p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>LONG Number of render hairs for the current chunk. Returns -1 if the function fails. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CRenderHairAccessor.html#a3947d19ac087ef2cd68c2409920339c4\">CRenderHairAccessor::Next</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7442706a0e77adbc3e5e76bb084a3d20\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetVerticesCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_values</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array containing the number of vertices for each generated render hair. This array can be used to iterate over the array of vertices and radius values.</p>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_values</td><td>Array of vertex count. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> Success</dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetVertexPositions, GetRenderHairAccessor::GetVertexRadiusValues </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a028bc4e68caa2f7f9c21b0ec70ea7597\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetVertexPositions </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_values</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of vertex positions (XYZ) for each render hair in local space. The vertex points are packed sequentially, the first being the root location, the next one in the sequence being the next connected point, all the way to the tip of the hair. Use the array returned by GetRenderHairAccessor::GetVerticesCount to find the number of vertices for each render hair in order to iterate over the vertex positions.</p>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_values</td><td>XYZ values. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetVerticesCount </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a01c98399e0901caeda3bd364d1540377\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetVertexRadiusValues </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_values</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of radius values at each render hair vertex. The radius values are packed sequentially, the first being the radius of the root location, the next one in the sequence being the next connected point radius, all the way to the tip of the hair. Use the array returned by GetRenderHairAccessor::GetVerticesCount to find the number of vertices for each render hair in order to iterate over the vertex radius values.</p>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_values</td><td>Radius values for each vertex of a render hair. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetVerticesCount </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a52ae6d979eacc001399e2fd591d4205a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetHairSurfaceNormalValues </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_values</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the surface normal (XYZ) of the hair\'s emitter surface, from which each render hair is emitted. </p>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_values</td><td>Surface normal values for each render hair. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetVerticesCount </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a21c21b71c80cea99ea81dd6ba22bc16d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetUVCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the number of UV properties on the primitive. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>LONG Number of UV properties. Returns -1 if the function fails. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetUVName, GetRenderHairAccessor::GetUVValues </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a20d88f332af39a861a0054d1a46d51f6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetVertexColorCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the number of vertex color properties on the primitive. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>LONG Number of vertex color properties. Returns -1 if the function fails. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetVertexColorName, GetRenderHairAccessor::GetVertexColorValues </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7d4d82cb17069902c9864ec000eace69\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">LONG GetWeightMapCount </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the number of weight map properties on the primitive. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>LONG Number of weight map properties. Returns -1 if the function fails. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetWeightMapName, GetRenderHairAccessor::GetWeightMapValues </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ac0efa7696ba121c3a1a6df2fcc084672\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> GetUVName </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIdx</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the name of the UV property at a given index. The index refers to the position of the property on the primitive.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIdx</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\" title=\"The Property class represents the property of the following entities: \">Property</a> index. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\" title=\"Character strings in the Softimage SDK are represented with the CString class. CString consist of a v...\">CString</a> Name of the property. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetUVCount, GetRenderHairAccessor::GetUVValues </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a66b3d62352f065a2b0878be52d14444b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> GetVertexColorName </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIdx</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the name of the vertex color property at a given index. The index refers to the position of the property on the primitive.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIdx</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\" title=\"The Property class represents the property of the following entities: \">Property</a> index. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\" title=\"Character strings in the Softimage SDK are represented with the CString class. CString consist of a v...\">CString</a> Name of the property. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetVertexColorCount, GetRenderHairAccessor::GetVertexColorValues </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"afd750c2d0f0facc5c1f4fb09cdc20d77\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> GetWeightMapName </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIdx</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns the name of the weight map property at a given index. The index refers to the position of the property on the primitive.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIdx</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\" title=\"The Property class represents the property of the following entities: \">Property</a> index. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\" title=\"Character strings in the Softimage SDK are represented with the CString class. CString consist of a v...\">CString</a> Name of the property. </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetWeightMapCount, GetRenderHairAccessor::GetWeightMapValues </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a01b6713dd7ff9f4662f911d8a8036660\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetUVValues </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIdx</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_values</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of UVW values for the UV property at the specified index. The values match the render hair root locations on the primitive. The index refers to the position of the property on the primitive.</p>\n\
<p>In general, the size of the returned array is GetRenderHairAccessor::GetChunkHairCount() * 3. However, in the case where render hairs are generated in an area where they get cut due to a cut map or where the density decreases, the number of values returned is smaller.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIdx</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\" title=\"The Property class represents the property of the following entities: \">Property</a> index. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_values</td><td>UVW values. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetUVCount, GetRenderHairAccessor::GetUVName </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a21c8510e8e188ba07750380a244fb261\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetVertexColorValues </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIdx</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_values</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of vertex color values (RGBA) for the vertex color property at the specified index. The values match the render hair root locations on the primitive. The index refers to the position of the property on the primitive.</p>\n\
<p>In general, the size of the returned array is GetRenderHairAccessor::GetChunkHairCount() * 4. However, in the case where render hairs are generated in an area where they get cut due to a cut map or where the density decreases, the number of values returned is smaller.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIdx</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\" title=\"The Property class represents the property of the following entities: \">Property</a> index. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_values</td><td>RGBA color values ranging from 0.0 to 1.0. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetVertexColorCount, GetRenderHairAccessor::GetVertexColorName </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a46bc187e9c98c00a9fb153ccc9cd08b9\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetWeightMapValues </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">LONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_nIdx</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CFloatArray.html\">CFloatArray</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>out_values</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Returns an array of weight map values (W) for the weight map property at the specified index. The values match the render hair root locations on the primitive. The index refers to the position of the property on the primitive.</p>\n\
<p>In general, the size of the returned array is GetRenderHairAccessor::GetChunkHairCount(). However, in the case where render hairs are generated in an area where they get cut due to a cut map or where the density decreases, the number of values returned is smaller.</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_nIdx</td><td><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1Property.html\" title=\"The Property class represents the property of the following entities: \">Property</a> index. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"retval\"><dt>Return values</dt><dd>\n\
  <table class=\"retval\">\n\
    <tr><td class=\"paramname\">out_values</td><td>Weight map values. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> success </dd></dl>\n\
<dl class=\"section see\"><dt>See Also</dt><dd>GetRenderHairAccessor::GetWeightMapCount, GetRenderHairAccessor::GetWeightMapName </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__renderhairaccessor_8h_source.html\">xsi_renderhairaccessor.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";