var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>CICEAttributeDataArray&lt; T &gt; Class Template Reference</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'classXSI_1_1CICEAttributeDataArray.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CICEAttributeDataArray&lt; T &gt; Class Template Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"summary\">\n\
<a href=\"#pub-methods\">Public Member Functions</a>  </div>\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CICEAttributeDataArray&lt; T &gt; Class Template Reference</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\"><div class=\"OverviewLinksDiv\"><div id=\"dynsection-overview\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\"><img id=\"dynsection-overview-trigger\" src=\"closed.png\" alt=\"+\"> This reference page is linked to from the following overview topics: </div><div id=\"dynsection-overview-content\" class=\"dyncontent\" style=\"display:none;\"><a href=\"#!/url=./files/GUID-8C3CA328-5C39-44FC-A630-7D020541DB61.htm\">Softimage 2014</a>, <a href=\"#!/url=./files/GUID-177FE97B-99EB-4EF2-A33A-B17811915954.htm\">Softimage 2013</a>.</div></div><hr>\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__iceattributedataarray_8h_source.html\">xsi_iceattributedataarray.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><h3>template&lt;class T&gt;<br>\n\
class XSI::CICEAttributeDataArray&lt; T &gt;</h3>\n\
\n\
<p>This template class encapsulates <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ICEAttribute.html\" title=\"The ICEAttribute object represents an attribute data set (a collection of information used in the ICE...\">ICEAttribute</a> data as a 1D array. CICEAttributeDataArray objects are read-only and can be filled with the methods supplied with the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ICEAttribute.html\" title=\"The ICEAttribute object represents an attribute data set (a collection of information used in the ICE...\">ICEAttribute</a> class. CICEAttributeDataArray is zero-based and can be one of the following types: </p>\n\
<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayFloat\">CICEAttributeDataArrayFloat</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayLong\">CICEAttributeDataArrayLong</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayBool\">CICEAttributeDataArrayBool</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayVector2f\">CICEAttributeDataArrayVector2f</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayVector3f\">CICEAttributeDataArrayVector3f</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayVector4f\">CICEAttributeDataArrayVector4f</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayQuaternionf\">CICEAttributeDataArrayQuaternionf</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayRotationf\">CICEAttributeDataArrayRotationf</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayMatrix3f\">CICEAttributeDataArrayMatrix3f</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayMatrix4f\">CICEAttributeDataArrayMatrix4f</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayColor4f\">CICEAttributeDataArrayColor4f</a> </li>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html#CICEAttributeDataArrayShape\">CICEAttributeDataArrayShape</a></li>\n\
</ul>\n\
<p>All types are associated to specific <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ICEAttribute.html\" title=\"The ICEAttribute object represents an attribute data set (a collection of information used in the ICE...\">ICEAttribute</a> types. Therefore, you need to declare the right array object type that matches the <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ICEAttribute.html\" title=\"The ICEAttribute object represents an attribute data set (a collection of information used in the ICE...\">ICEAttribute</a> data type you want to access. Otherwise a runtime error will occur and the returned array will be empty.</p>\n\
<dl class=\"section see\"><dt>See Also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ICEAttribute.html#ad3dbef6ba77d93eb5f0711806de62736\">ICEAttribute::GetDataArray</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1ICEAttribute.html#ae67e0903cb5adcf96b72466bd1168a3e\">ICEAttribute::GetDataArrayChunk</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/CICEAttributeDataArrayTypedefs.html\">Type Definitions for CICEAttributeDataArray</a> </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>7.0</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd>This example demonstrates how to iterate over the PointPosition attribute data on a grid primitive. <div class=\"fragment\"><div class=\"line\"><span class=\"keyword\">using namespace </span>XSI;</div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> CreatePrim( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_presetobj, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_geometrytype, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_name, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_parent );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> grid = CreatePrim( L<span class=\"stringliteral\">&quot;Grid&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ICEAttribute.html\">ICEAttribute</a> attr = grid.GetActivePrimitive().GetGeometry().GetICEAttributeFromName( L<span class=\"stringliteral\">&quot;PointPosition&quot;</span> );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html\">CICEAttributeDataArrayVector3f</a> points;</div>\n\
<div class=\"line\">attr.GetDataArray( points );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> xsi;</div>\n\
<div class=\"line\"><span class=\"keywordflow\">for</span>( ULONG i=0; i&lt;points.GetCount( ); i++ )</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    xsi.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#a9b269de260f6a9fca710d9b9003bd1a3\">LogMessage</a>( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>( points[ i ] ) );</div>\n\
<div class=\"line\">}</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\"><span class=\"comment\">// Helper</span></div>\n\
<div class=\"line\"><a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> CreatePrim( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_presetobj, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_geometrytype, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_name, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_parent )</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> args(4);</div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> retval;</div>\n\
<div class=\"line\">    args[0]= in_presetobj;</div>\n\
<div class=\"line\">    args[1]= in_geometrytype;</div>\n\
<div class=\"line\">    args[2]= in_name;</div>\n\
<div class=\"line\">    args[3]= in_parent;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html\">Application</a> app;</div>\n\
<div class=\"line\">    app.<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Application.html#afc4c4950c4f26c6fdd977c8058cf000b\">ExecuteCommand</a>( L<span class=\"stringliteral\">&quot;CreatePrim&quot;</span>, args, retval );</div>\n\
<div class=\"line\">    <span class=\"keywordflow\">return</span> retval;</div>\n\
<div class=\"line\">}</div>\n\
</div><!-- fragment --> </dd></dl>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"closed.png\" alt=\"+\"> Inheritance diagram for CICEAttributeDataArray&lt; T &gt;:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"classXSI_1_1CICEAttributeDataArray.png\" usemap=\"#CICEAttributeDataArray&lt; T &gt;_map\" alt=\"\">\n\
  <map id=\"CICEAttributeDataArray&lt; T &gt;_map\" name=\"CICEAttributeDataArray&lt; T &gt;_map\">\n\
<area href=\"classXSI_1_1CBaseICEAttributeDataArray.html\" title=\"Base class CICEAttributeDataArray class for the CICEAttributeDataArray and CICEAttributeDataArray2D t...\" alt=\"CBaseICEAttributeDataArray\" shape=\"rect\" coords=\"0,0,178,24\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a0e2912c3594faff10abf19b6ad15976a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html#a0e2912c3594faff10abf19b6ad15976a\">CICEAttributeDataArray</a> ()</td></tr>\n\
<tr class=\"separator:a0e2912c3594faff10abf19b6ad15976a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9de68dc5c010e88efbad6012c7e8471a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html#a9de68dc5c010e88efbad6012c7e8471a\">~CICEAttributeDataArray</a> ()</td></tr>\n\
<tr class=\"separator:a9de68dc5c010e88efbad6012c7e8471a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5a864a5c6ed190c80f6795ae1454eb4c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const T &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html#a5a864a5c6ed190c80f6795ae1454eb4c\">operator[]</a> (ULONG in_index) const </td></tr>\n\
<tr class=\"separator:a5a864a5c6ed190c80f6795ae1454eb4c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a10cf7e63eb5180918f1255cbcfa0e387\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">T &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html#a10cf7e63eb5180918f1255cbcfa0e387\">operator[]</a> (ULONG in_index)</td></tr>\n\
<tr class=\"separator:a10cf7e63eb5180918f1255cbcfa0e387\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a03be0886bdcad0276269a48ade67c23e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html#a03be0886bdcad0276269a48ade67c23e\">SetData</a> (ULONG in_index, const T &amp;in_value)</td></tr>\n\
<tr class=\"separator:a03be0886bdcad0276269a48ade67c23e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abbaf61e3faf8cc94a638b7a12de82a9c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html#abbaf61e3faf8cc94a638b7a12de82a9c\">SetArray</a> (const T *in_pArray, ULONG in_count)</td></tr>\n\
<tr class=\"separator:abbaf61e3faf8cc94a638b7a12de82a9c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_classXSI_1_1CBaseICEAttributeDataArray\')\"><img src=\"closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBaseICEAttributeDataArray.html\">CBaseICEAttributeDataArray</a></td></tr>\n\
<tr class=\"memitem:aaf99ae62191d421f6b41f34092e683e2 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">ULONG&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBaseICEAttributeDataArray.html#aaf99ae62191d421f6b41f34092e683e2\">GetCount</a> () const </td></tr>\n\
<tr class=\"separator:aaf99ae62191d421f6b41f34092e683e2 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a03aafe48c441185a645a7b1055481a93 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBaseICEAttributeDataArray.html#a03aafe48c441185a645a7b1055481a93\">IsConstant</a> () const </td></tr>\n\
<tr class=\"separator:a03aafe48c441185a645a7b1055481a93 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa45d9784f08ca0d0b525db6bd863d6a1 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a307f67e56bb2121f6a8eb0a99929bb1a\">XSI::siICENodeDataType</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBaseICEAttributeDataArray.html#aa45d9784f08ca0d0b525db6bd863d6a1\">GetDataType</a> () const </td></tr>\n\
<tr class=\"separator:aa45d9784f08ca0d0b525db6bd863d6a1 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a925874a7a044415741ff83bd06e95821 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/namespaceXSI.html#a25edb7cb80d670db4441230cee17938d\">XSI::siICENodeStructureType</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CBaseICEAttributeDataArray.html#a925874a7a044415741ff83bd06e95821\">GetStructureType</a> () const </td></tr>\n\
<tr class=\"separator:a925874a7a044415741ff83bd06e95821 inherit pub_methods_classXSI_1_1CBaseICEAttributeDataArray\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a0e2912c3594faff10abf19b6ad15976a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html\">CICEAttributeDataArray</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Constructor. </p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9de68dc5c010e88efbad6012c7e8471a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CICEAttributeDataArray.html\">CICEAttributeDataArray</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Destructor. </p>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a5a864a5c6ed190c80f6795ae1454eb4c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">const T&amp; operator[] </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">ULONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_index</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Accessor to the encapsulated array. This operator is called when reading the data so the return value is read-only. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_index</td><td>Index in the array. The index must be smaller than the number of elements in the array, otherwise the results are unpredictable. If the array is constant, the function always return the first item\'s value. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A read-only reference to the indexed item. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a10cf7e63eb5180918f1255cbcfa0e387\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">T&amp; operator[] </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">ULONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_index</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
<p>Accessor to the encapsulated array. This operator is used for writing to the data array. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_index</td><td>Index in the array. The index must be smaller than the number of elements in the array, otherwise the results are unpredictable. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A reference to the indexed item. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>11.0 (2013) </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a03be0886bdcad0276269a48ade67c23e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetData </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">ULONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_index</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">const T &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>in_value</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Accessor to the encapsulated array for writing to the data array. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_index</td><td>Index in the array. The index must be smaller than the number of elements in the array, otherwise the results are unpredictable. </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> Success. </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281dad795f6709d0c6419c4fe31703e454e27\">CStatus::InvalidArgument</a> Index out of range. </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da60a075acd0b5e992180ec8ad7d794ea4\">CStatus::AccessDenied</a> Array is read-only. </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> Attribute is undefined or non-accessible </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>12.0 (2014) </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abbaf61e3faf8cc94a638b7a12de82a9c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetArray </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const T *&#160;</td>\n\
          <td class=\"paramname\"><em>in_pArray</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">ULONG&#160;</td>\n\
          <td class=\"paramname\"><em>in_count</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<p>Set the values in the array</p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramname\">in_pArray</td><td>Input data array. </td></tr>\n\
    <tr><td class=\"paramname\">in_count</td><td>Number of elements in the input array</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2bc49ec37d6a5715dd23e85f1ff5bb59\">CStatus::OK</a> Success. </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html#af31477bc48f67856bedb0fa8e5b5281da2c88d6b09611bebcfd079df624ae3bfe\">CStatus::Fail</a> Operation failed. </dd></dl>\n\
<dl class=\"section since\"><dt>Since</dt><dd>12.0 (2014)</dd></dl>\n\
<dl class=\"section user\"><dt>Example:</dt><dd>This example demonstrates how to set the whole array <div class=\"fragment\"><div class=\"line\">Application xsi;</div>\n\
<div class=\"line\">Model root = xsi.GetActiveSceneRoot();</div>\n\
<div class=\"line\">X3DObject cone( CreatePrim( L<span class=\"stringliteral\">&quot;cone&quot;</span>, L<span class=\"stringliteral\">&quot;MeshSurface&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>, L<span class=\"stringliteral\">&quot;&quot;</span>) );</div>\n\
<div class=\"line\">{</div>\n\
<div class=\"line\">    ICEAttribute attr = cone.GetActivePrimitive().GetGeometry().AddICEAttribute( <span class=\"stringliteral\">&quot;DataArrayLong&quot;</span>, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a307f67e56bb2121f6a8eb0a99929bb1aa24b13c08f1203ad441d325e036f95726\">XSI::siICENodeDataLong</a>, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a25edb7cb80d670db4441230cee17938dad27363313efc37ac55e9ecaf64f7e863\">XSI::siICENodeStructureSingle</a>, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a3868a5b6193c034d90a55089dc65c605aca70084d89c965af244e2cfda987d84e\">XSI::siICENodeContextComponent0D</a> );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    CString l_connSet(L<span class=\"stringliteral\">&quot;cone&quot;</span>);</div>\n\
<div class=\"line\">    ApplyOp( L<span class=\"stringliteral\">&quot;ICETree&quot;</span>, l_connSet, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ac6805fcc10be81bcc4f14d6a33447f2ca2598cf5c4d689ff7cc059ce14a7a0818\">siConstructionModeModeling</a> );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    AddICECompoundNode(<span class=\"stringliteral\">&quot;Set Data&quot;</span>, <span class=\"stringliteral\">&quot;cone.polymsh.ICETree&quot;</span>);</div>\n\
<div class=\"line\">    AddICENode(<span class=\"stringliteral\">&quot;$XSI_DSPRESETS\\\\ICENodes\\\\GetDataNode.Preset&quot;</span>, <span class=\"stringliteral\">&quot;cone.polymsh.ICETree&quot;</span>);</div>\n\
<div class=\"line\">    SetValue(<span class=\"stringliteral\">&quot;cone.polymsh.ICETree.SceneReferenceNode.reference&quot;</span>, <span class=\"stringliteral\">&quot;self.DataArrayLong&quot;</span>);</div>\n\
<div class=\"line\">    SetValue(<span class=\"stringliteral\">&quot;cone.polymsh.ICETree.Set_Data.Reference&quot;</span>, <span class=\"stringliteral\">&quot;self.foo&quot;</span>);</div>\n\
<div class=\"line\">    ConnectICENodes(<span class=\"stringliteral\">&quot;cone.polymsh.ICETree.Set_Data.Value&quot;</span>, <span class=\"stringliteral\">&quot;cone.polymsh.ICETree.SceneReferenceNode.value&quot;</span>);</div>\n\
<div class=\"line\">    ConnectICENodes(<span class=\"stringliteral\">&quot;cone.polymsh.ICETree.port1&quot;</span>, <span class=\"stringliteral\">&quot;cone.polymsh.ICETree.Set_Data.Execute&quot;</span>);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    DisplayPortValues(<span class=\"stringliteral\">&quot;cone.polymsh.ICETree.Set_Data.Value&quot;</span>, <span class=\"keyword\">true</span>, 0, <span class=\"keyword\">true</span>, <span class=\"stringliteral\">&quot;&quot;</span>, 0, 0, 0, 1, <span class=\"keyword\">false</span>, <span class=\"keyword\">true</span>, 0.62, 1, 0.62, 1, <span class=\"keyword\">false</span>, 0, 10000, 1, <span class=\"keyword\">false</span>, <span class=\"keyword\">false</span>, 0, 10, <span class=\"keyword\">false</span>, <span class=\"keyword\">true</span>, <span class=\"keyword\">false</span>, 100);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    CICEAttributeDataArray&lt; LONG &gt; data;</div>\n\
<div class=\"line\">    attr.GetDataArray( data );</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    CICEAttributeDataLogger&lt; LONG &gt;::Log( attr );   </div>\n\
<div class=\"line\">    ULONG l_nbElem = attr.GetElementCount();</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    {</div>\n\
<div class=\"line\">        CLongArray l_Values(l_nbElem);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">        <span class=\"keywordflow\">for</span> (ULONG i=0; i&lt;l_nbElem; i++)</div>\n\
<div class=\"line\">            l_Values[i] = (i%2==0) ? -1 : 1;</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">        data.SetArray(l_Values.GetArray(), l_nbElem);</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">        CICEAttributeDataLogger&lt;LONG&gt;::Log( attr );</div>\n\
<div class=\"line\">    }</div>\n\
<div class=\"line\"></div>\n\
<div class=\"line\">    data[0] = (LONG)5;</div>\n\
<div class=\"line\">    data[4] = (LONG)12;</div>\n\
<div class=\"line\">}</div>\n\
</div><!-- fragment --> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__iceattributedataarray_8h_source.html\">xsi_iceattributedataarray.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";