var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><meta name=\"robots\" content=\"noindex, follow\"><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>File Members</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'globals.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>File Members</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>File&#160;List</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow3\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/globals.html\"><span>All</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals_func.html\"><span>Functions</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals_enum.html\"><span>Enumerations</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals_eval.html\"><span>Enumerator</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals_defs.html\"><span>Macros</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow4\" class=\"tabs3\">\n\
    <ul class=\"tablist\">\n\
      <li class=\"current\"><a href=\"#index_x\"><span>x</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"contents\">\n\
<div class=\"textblock\">Here is a list of all documented file members with links to the documentation:</div>\n\
\n\
<h3><a class=\"anchor\" id=\"index_x\"></a>- x -</h3><ul>\n\
<li>XSIMR_ATTRIBUTE_SHADER_KEY\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__PointCloudDefines.html#gafb87c3492f7450d9d1871c80987965fe\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_CE_CONSTANT\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a0519a88ae3f69d3ec4d0f1102166ee26\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_CE_CYCLE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a2613bc80078e94e47a8ad05d9457ee5e\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_CE_CYCLE_RELATIVE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262aab0f04dfb72623afdebc42abc4b92d3e\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_CE_END_GRADIENT\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a1c39f68ebcab381da7d0201b4809b22f\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_LF_DIFFUSE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga5f53374200cb0cb558be21eb81955ce1a88629f6f8c6285fc5229428f7855f075\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_LF_SPECULAR\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga5f53374200cb0cb558be21eb81955ce1a3f5d0ebd0717da87b049195685103a5c\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_LIGHTDATA_LABEL\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__LightAttributes.html#gaa7c5c2ea9d4f79ee937a1b47f09d65ac\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_LIGHTILLUMDATA_KEY\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrLightIllumData.html#ga96ca522efc914f26b10203946ec97b50\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_POINTCLOUD_INDEX_LABEL\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__PointCloudDefines.html#ga39bf0d4e0b4f0064fd2699e10a7c6edf\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSIMR_RENDERMAPDATA_LABEL\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga31cf0f1115146a16e753c53bfb61b13f\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_BLOB\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad15482a4bacafaf18aa1ae1035c10bd2\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_BOOLEAN\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42aa1a2979f8a8a459cc40218f1f0e2619d\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_COLOR4\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a2aad9eb197b76788873beaaae1879707\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_INTEGER\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a7ff8576e08c96f6f80c728cee5ba37ea\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_MATRIX33\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a5061dc718be550578c5c2ac7b6ffdddb\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_MATRIX44\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a6d643961da9008783fbfe11d1a50250e\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_QUATERNION\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ac7e9f8c73c398e1f17c743f4f13d2cde\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_ROTATION\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a492ec724c9f2282dd64edf9c618ddc4b\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_SCALAR\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad8f590fdc09c88aab6755166ba10ba55\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_SHAPE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a0e1c20a5ccfe43e65afe1668999c2aef\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_VECTOR2\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a656881d1885262ca2c9f28ee1cea2eb2\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_VECTOR3\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a34293f159fe6f46a837dc90d224912e4\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrATTRIBUTE_VECTOR4\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ac222f452976806de0437fef7b8ee2686\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrAttributeType\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#ga9796e541f5ad6a01e5710ee18273ad42\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrCurveExtrapolation\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga3d95229a01455c436e2538ac71e24262\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrLightFlags\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__miuserdata__defs_8h.html#a5f53374200cb0cb558be21eb81955ce1\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrNB_SIMPLE_SHAPES\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da73c686f367dd89428e94ac90573f96cd\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrParticleShapeType\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga5eacb8159cad288ce64d9d22afed6b0d\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_BLOB\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da144fa1b1b1991b27180321b8236a5e8a\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_BOX\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da76f7b8e6f48b5bdd5913f2d1fe19199c\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_CAPSULE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0daa4fb94a29fae69350f60834290f16821\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_CONE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da55ffb198aa7a3189193588d09ef1b257\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_CYLINDER\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da15c2bf1905c4d56e21378c4b61ffb0e4\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_DISC\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dab846e2d29fa459b838c52ccda7a30c5f\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_INSTANCE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da0544492b3f2503189c93c9877ad043d6\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_POINT\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da451705febc2d406136c69083621efa7f\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_RECTANGLE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da1aba4a32bbd15f23c311ee1ef27ae68b\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_SEGMENT\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da50a14a123f1f3db0a1b28da00da17f3a\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>xsimrSHAPE_SPHERE\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dadf00806c3b99ed3270de66278bd542c0\">xsi_miuserdata_defs.h</a>\n\
</li>\n\
<li>XSISDK_VERSION\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/xsi__version_8h.html#a1929e1313403857d063d7d9247c9b086\">xsi_version.h</a>\n\
</li>\n\
<li>XSIVariantFromCValue()\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/sicppsdk__win32_8h.html#a89d5ea35baf496c1b7386e378fa73497\">sicppsdk_win32.h</a>\n\
</li>\n\
<li>XSIVariantToCValue()\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/sicppsdk__win32_8h.html#ab0f7898abe648c0d0e2bd013a889f103\">sicppsdk_win32.h</a>\n\
</li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";