var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><meta name=\"robots\" content=\"noindex, follow\"><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>Member List</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'unionXSI_1_1CValue_1_1ValueField-members.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>Member List</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CValue::ValueField Member List</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p>This is the complete list of members for <a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a>, including all inherited members.</p>\n\
<table class=\"directory\">\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#adfe3e838cacf55495efe351e132f753b\">bval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a69f9c906955fddecbf137d846ad56451\">cval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#acefc0ddbab467d8de90049105846767c\">dval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a89560ba498e3fe528d97a435d5f61054\">fval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a4c4632d3ace6ea28ce14bf6b463dfd8e\">llval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a256811f99366f9c047077f1a39150d3c\">lval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a941857ecf47a07d09f1e64c08070e21d\">paval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a7e4861aa2d5501c74a4dc1e0572d1fe9\">pblobval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#ab4d1ca3f6b7d47e6dbc8a81cafa2dab3\">pc4f</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a760f987771b124e9758d8d56bb84752c\">pfaval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a0042399b9c46361b9be692d04721027d\">plaval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a2a0fe89ff6a08192dee398b7033e5aee\">pm3f</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#adb81e573c7661831552f6f4315b8a74c\">pm4f</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#aecaca07c73e178e3cf93cb736fe6c3fa\">pqf</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a6efece79953e8274a8f83fe375727565\">prf</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a733d8ce04d8e59332a018da7c983ecc7\">pshp</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#ad1bcf2da0566f6e8ddd1393f50073894\">pstrarrayval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a77cc086d976a6ae075a70f5a01f73328\">pv2f</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a9a8a586e8106ee0935ccd1d420a86291\">pv3f</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#af7056e8eb665d87b54695af0b6da7ebe\">pv4f</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a403414386f90c7383d9aec51e5c56029\">pval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#ad61def09fbd0a94725db3d9819ad632a\">pwval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#ad13f9a030ae014e2099b4f717444c585\">sval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#ad3ea815c133e8b0d27657141d8b2a430\">ucval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#afd05a91e90a2ae6b069926582317305d\">ullval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#ab87d6f3617ae1fcb9f87fbee6524771d\">ulval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
  <tr class=\"even\"><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html#a85bf72ca755b72a90137d0ab64393d34\">usval</a></td><td class=\"entry\"><a class=\"el\" translate=\"no\" href=\"#!/url=./si_cpp/unionXSI_1_1CValue_1_1ValueField.html\">CValue::ValueField</a></td><td class=\"entry\"></td></tr>\n\
</table></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";