var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>xsi_hardwareshadercontext.h Source File</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'xsi__hardwareshadercontext_8h_source.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>xsi_hardwareshadercontext.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">xsi_hardwareshadercontext.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./si_cpp/xsi__hardwareshadercontext_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;<span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"preprocessor\">#if (_MSC_VER &gt; 1000) || defined(SGI_COMPILER)</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#pragma once</span></div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"preprocessor\">#ifndef __XSIHARDWARESHADERCONTEXT_H__</span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define __XSIHARDWARESHADERCONTEXT_H__</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__base_8h.html\">xsi_base.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__value_8h.html\">xsi_value.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__context_8h.html\">xsi_context.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__time_8h.html\">xsi_time.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__material_8h.html\">xsi_material.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__x3dobject_8h.html\">xsi_x3dobject.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00026\"></a><span class=\"lineno\">   26</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__hardwaresurface_8h.html\">xsi_hardwaresurface.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00027\"></a><span class=\"lineno\">   27</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__hardwareattribute_8h.html\">xsi_hardwareattribute.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00028\"></a><span class=\"lineno\">   28</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00029\"></a><span class=\"lineno\">   29</span>&#160;<span class=\"keyword\">namespace </span>XSI {</div>\n\
<div class=\"line\"><a name=\"l00030\"></a><span class=\"lineno\">   30</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00031\"></a><span class=\"lineno\">   31</span>&#160;<span class=\"keyword\">class </span>Shader;</div>\n\
<div class=\"line\"><a name=\"l00032\"></a><span class=\"lineno\">   32</span>&#160;<span class=\"keyword\">class </span>Camera;</div>\n\
<div class=\"line\"><a name=\"l00033\"></a><span class=\"lineno\">   33</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00034\"></a><span class=\"lineno\">   34</span>&#160;<span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00042\"></a><span class=\"lineno\">   42</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00043\"></a><span class=\"lineno\">   43</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00044\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">   44</a></span>&#160;<span class=\"keyword\">class </span>SICPPSDKDECL <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a> : <span class=\"keyword\">public</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">Context</a></div>\n\
<div class=\"line\"><a name=\"l00045\"></a><span class=\"lineno\">   45</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00046\"></a><span class=\"lineno\">   46</span>&#160;<span class=\"keyword\">public</span>:</div>\n\
<div class=\"line\"><a name=\"l00047\"></a><span class=\"lineno\">   47</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00049\"></a><span class=\"lineno\">   49</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>();</div>\n\
<div class=\"line\"><a name=\"l00050\"></a><span class=\"lineno\">   50</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00052\"></a><span class=\"lineno\">   52</span>&#160;    ~<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>();</div>\n\
<div class=\"line\"><a name=\"l00053\"></a><span class=\"lineno\">   53</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00057\"></a><span class=\"lineno\">   57</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&amp; in_ref);</div>\n\
<div class=\"line\"><a name=\"l00058\"></a><span class=\"lineno\">   58</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00062\"></a><span class=\"lineno\">   62</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>&amp; in_obj);</div>\n\
<div class=\"line\"><a name=\"l00063\"></a><span class=\"lineno\">   63</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00068\"></a><span class=\"lineno\">   68</span>&#160;    <span class=\"keywordtype\">bool</span> IsA( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00069\"></a><span class=\"lineno\">   69</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00073\"></a><span class=\"lineno\">   73</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00074\"></a><span class=\"lineno\">   74</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00079\"></a><span class=\"lineno\">   79</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>&amp; operator=(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>&amp; in_obj);</div>\n\
<div class=\"line\"><a name=\"l00080\"></a><span class=\"lineno\">   80</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00086\"></a><span class=\"lineno\">   86</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a>&amp; operator=(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&amp; in_ref);</div>\n\
<div class=\"line\"><a name=\"l00087\"></a><span class=\"lineno\">   87</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00091\"></a><span class=\"lineno\">   91</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Shader.html\">Shader</a> GetShader( );</div>\n\
<div class=\"line\"><a name=\"l00092\"></a><span class=\"lineno\">   92</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00098\"></a><span class=\"lineno\">   98</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Shader.html\">Shader</a> GetShaderForAnimation( );</div>\n\
<div class=\"line\"><a name=\"l00099\"></a><span class=\"lineno\">   99</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00104\"></a><span class=\"lineno\">  104</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Camera.html\">Camera</a> GetCamera( );</div>\n\
<div class=\"line\"><a name=\"l00105\"></a><span class=\"lineno\">  105</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00109\"></a><span class=\"lineno\">  109</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Material.html\">Material</a> GetMaterial( );</div>\n\
<div class=\"line\"><a name=\"l00110\"></a><span class=\"lineno\">  110</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00114\"></a><span class=\"lineno\">  114</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">X3DObject</a> GetX3DObject( );</div>\n\
<div class=\"line\"><a name=\"l00115\"></a><span class=\"lineno\">  115</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00119\"></a><span class=\"lineno\">  119</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> GetLights();</div>\n\
<div class=\"line\"><a name=\"l00120\"></a><span class=\"lineno\">  120</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00124\"></a><span class=\"lineno\">  124</span>&#160;    ULONG GetShaderUniqueID ();</div>\n\
<div class=\"line\"><a name=\"l00125\"></a><span class=\"lineno\">  125</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00130\"></a><span class=\"lineno\">  130</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">CTime</a> GetTime() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00131\"></a><span class=\"lineno\">  131</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00135\"></a><span class=\"lineno\">  135</span>&#160;    <span class=\"keywordtype\">void</span>* GetTriangleIndices();</div>\n\
<div class=\"line\"><a name=\"l00136\"></a><span class=\"lineno\">  136</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00140\"></a><span class=\"lineno\">  140</span>&#160;    UINT GetIndexWidth();</div>\n\
<div class=\"line\"><a name=\"l00141\"></a><span class=\"lineno\">  141</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00146\"></a><span class=\"lineno\">  146</span>&#160;    ULONG GetNbIndices();</div>\n\
<div class=\"line\"><a name=\"l00147\"></a><span class=\"lineno\">  147</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00150\"></a><span class=\"lineno\">  150</span>&#160;    ULONG GetBaseOffset();</div>\n\
<div class=\"line\"><a name=\"l00151\"></a><span class=\"lineno\">  151</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00155\"></a><span class=\"lineno\">  155</span>&#160;    ULONG GetNbVertices();</div>\n\
<div class=\"line\"><a name=\"l00156\"></a><span class=\"lineno\">  156</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00159\"></a><span class=\"lineno\">  159</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CHardwareAttributeArray.html\">CHardwareAttributeArray</a> GetHardwareAttributeArray();</div>\n\
<div class=\"line\"><a name=\"l00160\"></a><span class=\"lineno\">  160</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00164\"></a><span class=\"lineno\">  164</span>&#160;    <span class=\"keywordtype\">bool</span> IsGeometryDirty() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00165\"></a><span class=\"lineno\">  165</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00169\"></a><span class=\"lineno\">  169</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CTransformation.html\">MATH::CTransformation</a> GetTransform() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00170\"></a><span class=\"lineno\">  170</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00174\"></a><span class=\"lineno\">  174</span>&#160;    <span class=\"keywordtype\">void</span> DrawPrimitive( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#acdda91a5447107cf8225c3b220bf1bea\">siGraphicDriver</a> in_eDriver ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00175\"></a><span class=\"lineno\">  175</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00179\"></a><span class=\"lineno\">  179</span>&#160;    <span class=\"keywordtype\">void</span> DrawScreenAlignedQuad( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#acdda91a5447107cf8225c3b220bf1bea\">siGraphicDriver</a> in_eDriver ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00180\"></a><span class=\"lineno\">  180</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00185\"></a><span class=\"lineno\">  185</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareSurface.html\">HardwareSurface</a> CreateHardwareSurface( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareSurface_1_1Options.html\">HardwareSurface::Options</a>&amp; in_options );</div>\n\
<div class=\"line\"><a name=\"l00186\"></a><span class=\"lineno\">  186</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00191\"></a><span class=\"lineno\">  191</span>&#160;    <span class=\"keywordtype\">void</span> SetRenderTarget( UINT in_nDrawBufferIndex, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareSurface.html\">HardwareSurface</a>&amp; in_surface );</div>\n\
<div class=\"line\"><a name=\"l00192\"></a><span class=\"lineno\">  192</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00195\"></a><span class=\"lineno\">  195</span>&#160;    <span class=\"keywordtype\">void</span> SetRenderDepthStencilTarget( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareSurface.html\">HardwareSurface</a>&amp; in_surface );</div>\n\
<div class=\"line\"><a name=\"l00196\"></a><span class=\"lineno\">  196</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00200\"></a><span class=\"lineno\">  200</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> GetGraphicDriver() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00201\"></a><span class=\"lineno\">  201</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00213\"></a><span class=\"lineno\">  213</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> GetShadowSurfaces( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">XSI::CRefArray</a>&amp; out_lights ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00214\"></a><span class=\"lineno\">  214</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00221\"></a><span class=\"lineno\">  221</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CParameterRefArray.html\">CParameterRefArray</a> GetDirtyParameters() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00222\"></a><span class=\"lineno\">  222</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00223\"></a><span class=\"lineno\">  223</span>&#160;    <span class=\"keyword\">private</span>:</div>\n\
<div class=\"line\"><a name=\"l00224\"></a><span class=\"lineno\">  224</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a> * operator&amp;() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00225\"></a><span class=\"lineno\">  225</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">HardwareShaderContext</a> * operator&amp;();</div>\n\
<div class=\"line\"><a name=\"l00226\"></a><span class=\"lineno\">  226</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00227\"></a><span class=\"lineno\">  227</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00228\"></a><span class=\"lineno\">  228</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00229\"></a><span class=\"lineno\">  229</span>&#160;<span class=\"preprocessor\">#endif // __XSIRENDERERCONTEXT_H__</span></div>\n\
<div class=\"ttc\" id=\"xsi__hardwaresurface_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__hardwaresurface_8h.html\">xsi_hardwaresurface.h</a></div><div class=\"ttdoc\">HardwareSurface class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CRef_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">XSI::CRef</a></div><div class=\"ttdoc\">This class is used to reference Softimage objects. Each instance of an CRef maintains a link with onl...</div><div class=\"ttdef\"><b>Definition:</b> xsi_ref.h:142</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Material_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Material.html\">XSI::Material</a></div><div class=\"ttdoc\">The Material object represents a material property of a SceneItem object. </div><div class=\"ttdef\"><b>Definition:</b> xsi_material.h:64</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_acdda91a5447107cf8225c3b220bf1bea\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#acdda91a5447107cf8225c3b220bf1bea\">XSI::siGraphicDriver</a></div><div class=\"ttdeci\">siGraphicDriver</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:2887</div></div>\n\
<div class=\"ttc\" id=\"xsi__context_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__context_8h.html\">xsi_context.h</a></div><div class=\"ttdoc\">Context class declaration. </div></div>\n\
<div class=\"ttc\" id=\"xsi__hardwareattribute_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__hardwareattribute_8h.html\">xsi_hardwareattribute.h</a></div><div class=\"ttdoc\">CHardwareAttribute and CHardwareAttributeArray class declarations. </div></div>\n\
<div class=\"ttc\" id=\"xsi__value_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__value_8h.html\">xsi_value.h</a></div><div class=\"ttdoc\">CValue and CValueArray class declarations. </div></div>\n\
<div class=\"ttc\" id=\"xsi__material_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__material_8h.html\">xsi_material.h</a></div><div class=\"ttdoc\">Material class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1HardwareShaderContext_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1HardwareShaderContext.html\">XSI::HardwareShaderContext</a></div><div class=\"ttdoc\">This object is provided as the context object in the execution callback of a hardware shader...</div><div class=\"ttdef\"><b>Definition:</b> xsi_hardwareshadercontext.h:44</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CHardwareAttributeArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CHardwareAttributeArray.html\">XSI::CHardwareAttributeArray</a></div><div class=\"ttdoc\">The CHardwareAttributeArray is an uni-dimensional array of CHardwareAttribute. </div><div class=\"ttdef\"><b>Definition:</b> xsi_hardwareattribute.h:116</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Camera_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Camera.html\">XSI::Camera</a></div><div class=\"ttdoc\">The Camera object represents a Softimage camera in a scene. </div><div class=\"ttdef\"><b>Definition:</b> xsi_camera.h:57</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CRefArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">XSI::CRefArray</a></div><div class=\"ttdoc\">The CRefArray class holds generic CRef objects and acts as a base class for other specialized CRef ar...</div><div class=\"ttdef\"><b>Definition:</b> xsi_ref.h:333</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_ad483c77b3d997caca1f369db99c1e68b\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">XSI::siClassID</a></div><div class=\"ttdeci\">siClassID</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:1537</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1HardwareSurface_1_1Options_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1HardwareSurface_1_1Options.html\">XSI::HardwareSurface::Options</a></div><div class=\"ttdoc\">This class represents the options used for creating HardwareSurface objects. </div><div class=\"ttdef\"><b>Definition:</b> xsi_hardwaresurface.h:94</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Shader_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Shader.html\">XSI::Shader</a></div><div class=\"ttdoc\">The Shader object represents a node in the render tree of an object. </div><div class=\"ttdef\"><b>Definition:</b> xsi_shader.h:155</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1MATH_1_1CTransformation_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CTransformation.html\">XSI::MATH::CTransformation</a></div><div class=\"ttdoc\">This object represents a transformation which is the result of the combination of a Scaling...</div><div class=\"ttdef\"><b>Definition:</b> xsi_transformation.h:85</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Context_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">XSI::Context</a></div><div class=\"ttdoc\">This is a general, flexible Context object that is used for callbacks. Instances of this object are u...</div><div class=\"ttdef\"><b>Definition:</b> xsi_context.h:46</div></div>\n\
<div class=\"ttc\" id=\"xsi__time_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__time_8h.html\">xsi_time.h</a></div><div class=\"ttdoc\">CTime and CTimeArray class declarations. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CParameterRefArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CParameterRefArray.html\">XSI::CParameterRefArray</a></div><div class=\"ttdoc\">An array of Parameters. </div><div class=\"ttdef\"><b>Definition:</b> xsi_parameter.h:70</div></div>\n\
<div class=\"ttc\" id=\"xsi__x3dobject_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__x3dobject_8h.html\">xsi_x3dobject.h</a></div><div class=\"ttdoc\">X3DObject class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1X3DObject_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1X3DObject.html\">XSI::X3DObject</a></div><div class=\"ttdoc\">The X3DObject object represents a basic 3D object of a scene in Softimage. </div><div class=\"ttdef\"><b>Definition:</b> xsi_x3dobject.h:91</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1HardwareSurface_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1HardwareSurface.html\">XSI::HardwareSurface</a></div><div class=\"ttdoc\">HardwareSurface class used for encapsulating a 2D shader texture surface. </div><div class=\"ttdef\"><b>Definition:</b> xsi_hardwaresurface.h:34</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CTime_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CTime.html\">XSI::CTime</a></div><div class=\"ttdoc\">The CTime class is a utility class for manipulating time. </div><div class=\"ttdef\"><b>Definition:</b> xsi_time.h:49</div></div>\n\
<div class=\"ttc\" id=\"xsi__base_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__base_8h.html\">xsi_base.h</a></div><div class=\"ttdoc\">CBase class declaration. </div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";