var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>xsi_vertexcolor.h Source File</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'xsi__vertexcolor_8h_source.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>xsi_vertexcolor.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">xsi_vertexcolor.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./si_cpp/xsi__vertexcolor_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;<span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"preprocessor\">#if (_MSC_VER &gt; 1000) || defined(SGI_COMPILER)</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#pragma once</span></div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"preprocessor\">#ifndef __XSI_VERTEXCOLOR_H__</span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define __XSI_VERTEXCOLOR_H__</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"preprocessor\">#include &quot;sicppsdk.h&quot;</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;<span class=\"preprocessor\">#include &quot;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__status_8h.html\">xsi_status.h</a>&quot;</span></div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;<span class=\"keyword\">namespace </span>XSI {</div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;<span class=\"comment\">//*************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00033\"></a><span class=\"lineno\">   33</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00034\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">   34</a></span>&#160;<span class=\"keyword\">struct </span><a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">CVertexColor</a></div>\n\
<div class=\"line\"><a name=\"l00035\"></a><span class=\"lineno\">   35</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00036\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">   36</a></span>&#160;    <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">r</a>; </div>\n\
<div class=\"line\"><a name=\"l00037\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">   37</a></span>&#160;    <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">g</a>; </div>\n\
<div class=\"line\"><a name=\"l00038\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">   38</a></span>&#160;    <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">b</a>; </div>\n\
<div class=\"line\"><a name=\"l00039\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">   39</a></span>&#160;    <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">a</a>; </div>\n\
<div class=\"line\"><a name=\"l00042\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a2103548890bd9e5e2a05d2629de2574a\">   42</a></span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a2103548890bd9e5e2a05d2629de2574a\">CVertexColor</a>() : <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">r</a>(0),<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">g</a>(0),<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">b</a>(0),<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">a</a>(0) {}</div>\n\
<div class=\"line\"><a name=\"l00043\"></a><span class=\"lineno\">   43</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00047\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a49d995a032bf99cf029d8d2f32c52d5c\">   47</a></span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a49d995a032bf99cf029d8d2f32c52d5c\">CVertexColor</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">CVertexColor</a>&amp; in_color) : <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">r</a>(in_color.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">r</a>),</div>\n\
<div class=\"line\"><a name=\"l00048\"></a><span class=\"lineno\">   48</span>&#160;        <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">g</a>(in_color.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">g</a>), <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">b</a>(in_color.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">b</a>),<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">a</a>(in_color.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">a</a>) {}</div>\n\
<div class=\"line\"><a name=\"l00049\"></a><span class=\"lineno\">   49</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00056\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a63beb810c5c000ce54aa6e91fa504860\">   56</a></span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a63beb810c5c000ce54aa6e91fa504860\">CVertexColor</a>(<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> in_rc, <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> in_gc,</div>\n\
<div class=\"line\"><a name=\"l00057\"></a><span class=\"lineno\">   57</span>&#160;        <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> in_bc, <span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span> in_ac) : <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">r</a>(in_rc),<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">g</a>(in_gc),</div>\n\
<div class=\"line\"><a name=\"l00058\"></a><span class=\"lineno\">   58</span>&#160;            <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">b</a>(in_bc),<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">a</a>(in_ac) {}</div>\n\
<div class=\"line\"><a name=\"l00059\"></a><span class=\"lineno\">   59</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00064\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a7cc0b57041e2aa8cf44c9fd8e7e3499f\">   64</a></span>&#160;    <span class=\"keywordtype\">bool</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a7cc0b57041e2aa8cf44c9fd8e7e3499f\">operator==</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">CVertexColor</a>&amp; in_vertexcolor)<span class=\"keyword\">const</span></div>\n\
<div class=\"line\"><a name=\"l00065\"></a><span class=\"lineno\">   65</span>&#160;<span class=\"keyword\">    </span>{</div>\n\
<div class=\"line\"><a name=\"l00066\"></a><span class=\"lineno\">   66</span>&#160;        <span class=\"keywordflow\">return</span> (<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">r</a> == in_vertexcolor.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">r</a>) &amp;&amp; (<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">g</a> == in_vertexcolor.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">g</a>) &amp;&amp;</div>\n\
<div class=\"line\"><a name=\"l00067\"></a><span class=\"lineno\">   67</span>&#160;               (<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">b</a> == in_vertexcolor.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">b</a>) &amp;&amp; (<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">a</a> == in_vertexcolor.<a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">a</a>);</div>\n\
<div class=\"line\"><a name=\"l00068\"></a><span class=\"lineno\">   68</span>&#160;    }</div>\n\
<div class=\"line\"><a name=\"l00069\"></a><span class=\"lineno\">   69</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00074\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a2002edf78ae530ba45c18c08058fd61f\">   74</a></span>&#160;    <span class=\"keywordtype\">bool</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a2002edf78ae530ba45c18c08058fd61f\">operator!=</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">CVertexColor</a>&amp; in_vertexcolor)<span class=\"keyword\">const</span></div>\n\
<div class=\"line\"><a name=\"l00075\"></a><span class=\"lineno\">   75</span>&#160;<span class=\"keyword\">    </span>{</div>\n\
<div class=\"line\"><a name=\"l00076\"></a><span class=\"lineno\">   76</span>&#160;        <span class=\"keywordflow\">return</span> ! <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a7cc0b57041e2aa8cf44c9fd8e7e3499f\">operator==</a>(in_vertexcolor);</div>\n\
<div class=\"line\"><a name=\"l00077\"></a><span class=\"lineno\">   77</span>&#160;    }</div>\n\
<div class=\"line\"><a name=\"l00078\"></a><span class=\"lineno\">   78</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00079\"></a><span class=\"lineno\">   79</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00080\"></a><span class=\"lineno\">   80</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00081\"></a><span class=\"lineno\">   81</span>&#160;<span class=\"comment\">//*************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00091\"></a><span class=\"lineno\">   91</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00092\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">   92</a></span>&#160;<span class=\"keyword\">class </span>SICPPSDKDECL <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a></div>\n\
<div class=\"line\"><a name=\"l00093\"></a><span class=\"lineno\">   93</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00094\"></a><span class=\"lineno\">   94</span>&#160;<span class=\"keyword\">public</span>:</div>\n\
<div class=\"line\"><a name=\"l00098\"></a><span class=\"lineno\">   98</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>( LONG in_size=0);</div>\n\
<div class=\"line\"><a name=\"l00099\"></a><span class=\"lineno\">   99</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00103\"></a><span class=\"lineno\">  103</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>&amp; in_array );</div>\n\
<div class=\"line\"><a name=\"l00104\"></a><span class=\"lineno\">  104</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00106\"></a><span class=\"lineno\">  106</span>&#160;    ~<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>();</div>\n\
<div class=\"line\"><a name=\"l00107\"></a><span class=\"lineno\">  107</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00112\"></a><span class=\"lineno\">  112</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>&amp; operator=( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>&amp; in_array );</div>\n\
<div class=\"line\"><a name=\"l00113\"></a><span class=\"lineno\">  113</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00117\"></a><span class=\"lineno\">  117</span>&#160;    LONG GetCount() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00118\"></a><span class=\"lineno\">  118</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00123\"></a><span class=\"lineno\">  123</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Add( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">CVertexColor</a>&amp; in_item );</div>\n\
<div class=\"line\"><a name=\"l00124\"></a><span class=\"lineno\">  124</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00128\"></a><span class=\"lineno\">  128</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Clear();</div>\n\
<div class=\"line\"><a name=\"l00129\"></a><span class=\"lineno\">  129</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00135\"></a><span class=\"lineno\">  135</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Resize( LONG in_size);</div>\n\
<div class=\"line\"><a name=\"l00136\"></a><span class=\"lineno\">  136</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00143\"></a><span class=\"lineno\">  143</span>&#160;    <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">CVertexColor</a>&amp; operator[]( LONG in_index ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00144\"></a><span class=\"lineno\">  144</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00150\"></a><span class=\"lineno\">  150</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">CVertexColor</a>&amp; operator[](LONG in_index );</div>\n\
<div class=\"line\"><a name=\"l00151\"></a><span class=\"lineno\">  151</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00157\"></a><span class=\"lineno\">  157</span>&#160;    <span class=\"keywordtype\">bool</span> <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#af5ffad5b92da29b448799939bd42282c\">operator==</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>&amp; in_array) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00158\"></a><span class=\"lineno\">  158</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00164\"></a><span class=\"lineno\">  164</span>&#160;    <span class=\"keywordtype\">bool</span> <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad9d3fcb26eddd2e76772270276771406\">operator!=</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">CVertexColorArray</a>&amp; in_array) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00165\"></a><span class=\"lineno\">  165</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00166\"></a><span class=\"lineno\">  166</span>&#160;<span class=\"keyword\">private</span>:</div>\n\
<div class=\"line\"><a name=\"l00167\"></a><span class=\"lineno\">  167</span>&#160;    <span class=\"keywordtype\">void</span>* m_ptr;</div>\n\
<div class=\"line\"><a name=\"l00168\"></a><span class=\"lineno\">  168</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00169\"></a><span class=\"lineno\">  169</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00170\"></a><span class=\"lineno\">  170</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00171\"></a><span class=\"lineno\">  171</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00172\"></a><span class=\"lineno\">  172</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00173\"></a><span class=\"lineno\">  173</span>&#160;<span class=\"preprocessor\">#endif //__XSI_COLOR_H__</span></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a24420a9beaac7cee08b5e255a4c29db1\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a24420a9beaac7cee08b5e255a4c29db1\">XSI::CVertexColor::a</a></div><div class=\"ttdeci\">unsigned char a</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:39</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a2002edf78ae530ba45c18c08058fd61f\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a2002edf78ae530ba45c18c08058fd61f\">XSI::CVertexColor::operator!=</a></div><div class=\"ttdeci\">bool operator!=(const CVertexColor &amp;in_vertexcolor) const </div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:74</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a83576af39a9f289a28c1263d61073508\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a83576af39a9f289a28c1263d61073508\">XSI::CVertexColor::g</a></div><div class=\"ttdeci\">unsigned char g</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:37</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a41cede1b4c0d05cff170ad5761f70964\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a41cede1b4c0d05cff170ad5761f70964\">XSI::CVertexColor::b</a></div><div class=\"ttdeci\">unsigned char b</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:38</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a49d995a032bf99cf029d8d2f32c52d5c\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a49d995a032bf99cf029d8d2f32c52d5c\">XSI::CVertexColor::CVertexColor</a></div><div class=\"ttdeci\">CVertexColor(const CVertexColor &amp;in_color)</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:47</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_af5ffad5b92da29b448799939bd42282c\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#af5ffad5b92da29b448799939bd42282c\">XSI::operator==</a></div><div class=\"ttdeci\">bool operator==(CStatus::Code lhs, const CStatus &amp;rhs)</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a63beb810c5c000ce54aa6e91fa504860\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a63beb810c5c000ce54aa6e91fa504860\">XSI::CVertexColor::CVertexColor</a></div><div class=\"ttdeci\">CVertexColor(unsigned char in_rc, unsigned char in_gc, unsigned char in_bc, unsigned char in_ac)</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:56</div></div>\n\
<div class=\"ttc\" id=\"xsi__status_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__status_8h.html\">xsi_status.h</a></div><div class=\"ttdoc\">CStatus class declaration. </div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a2103548890bd9e5e2a05d2629de2574a\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a2103548890bd9e5e2a05d2629de2574a\">XSI::CVertexColor::CVertexColor</a></div><div class=\"ttdeci\">CVertexColor()</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:42</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_afd7b1ea9ff115205b65e0bffc92946ac\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#afd7b1ea9ff115205b65e0bffc92946ac\">XSI::CVertexColor::r</a></div><div class=\"ttdeci\">unsigned char r</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:36</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html\">XSI::CVertexColor</a></div><div class=\"ttdoc\">This structure represents a vertex RGBA color. Unlike CColor, each component value of CVertexColor is...</div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:34</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CStatus_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">XSI::CStatus</a></div><div class=\"ttdoc\">Encapsulates status data types for error handling purpose. The class also exposes methods to query an...</div><div class=\"ttdef\"><b>Definition:</b> xsi_status.h:36</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_ad9d3fcb26eddd2e76772270276771406\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#ad9d3fcb26eddd2e76772270276771406\">XSI::operator!=</a></div><div class=\"ttdeci\">bool operator!=(CStatus::Code lhs, const CStatus &amp;rhs)</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CVertexColorArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CVertexColorArray.html\">XSI::CVertexColorArray</a></div><div class=\"ttdoc\">The CVertexColorArray is an uni-dimensional array of CVertexColor objects. </div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:92</div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CVertexColor_html_a7cc0b57041e2aa8cf44c9fd8e7e3499f\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CVertexColor.html#a7cc0b57041e2aa8cf44c9fd8e7e3499f\">XSI::CVertexColor::operator==</a></div><div class=\"ttdeci\">bool operator==(const CVertexColor &amp;in_vertexcolor) const </div><div class=\"ttdef\"><b>Definition:</b> xsi_vertexcolor.h:64</div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";