var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>xsi_miuserdata_defs.h Source File</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'xsi__miuserdata__defs_8h_source.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>xsi_miuserdata_defs.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">xsi_miuserdata_defs.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./si_cpp/xsi__miuserdata__defs_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00008\"></a><span class=\"lineno\">    8</span>&#160;<span class=\"preprocessor\">#ifndef XSI_MIUSERDATA_DEFS_H</span></div>\n\
<div class=\"line\"><a name=\"l00009\"></a><span class=\"lineno\">    9</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define XSI_MIUSERDATA_DEFS_H</span></div>\n\
<div class=\"line\"><a name=\"l00010\"></a><span class=\"lineno\">   10</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"preprocessor\">#include &lt;shader.h&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"comment\">/* Transformation data ------------------------------------------*/</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"preprocessor\">#define XSIMR_INSTANCETRANSFORMDATA_LABEL   0x00004210</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define XSIMR_INSTANCETRANSFORMDATA_VERSION 0x00000003</span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"preprocessor\">#define XSIMR_SHADOWINSTANCE_LABEL          0xf6a209ca      // From random.org</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">enum</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;    E3DIF_Ignore        = 0,</div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;    E3DIF_Back          = 1,</div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;    E3DIF_Front         = 2,</div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;    E3DIF_Both          = 3</div>\n\
<div class=\"line\"><a name=\"l00026\"></a><span class=\"lineno\">   26</span>&#160;} xsimrInstanceFaceFlags;</div>\n\
<div class=\"line\"><a name=\"l00027\"></a><span class=\"lineno\">   27</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00028\"></a><span class=\"lineno\">   28</span>&#160;<span class=\"preprocessor\">#define miDONTCARE          (miCBoolean)2</span></div>\n\
<div class=\"line\"><a name=\"l00029\"></a><span class=\"lineno\">   29</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00030\"></a><span class=\"lineno\">   30</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00031\"></a><span class=\"lineno\">   31</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00032\"></a><span class=\"lineno\">   32</span>&#160;    miCBoolean              is_instance;</div>\n\
<div class=\"line\"><a name=\"l00033\"></a><span class=\"lineno\">   33</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00034\"></a><span class=\"lineno\">   34</span>&#160;    miCBoolean              primary_visible;</div>\n\
<div class=\"line\"><a name=\"l00035\"></a><span class=\"lineno\">   35</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00036\"></a><span class=\"lineno\">   36</span>&#160;    miCBoolean              transparent_receive;</div>\n\
<div class=\"line\"><a name=\"l00037\"></a><span class=\"lineno\">   37</span>&#160;    miCBoolean              transparent_cast;</div>\n\
<div class=\"line\"><a name=\"l00038\"></a><span class=\"lineno\">   38</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00039\"></a><span class=\"lineno\">   39</span>&#160;    miCBoolean              reflection_receive;</div>\n\
<div class=\"line\"><a name=\"l00040\"></a><span class=\"lineno\">   40</span>&#160;    miCBoolean              reflection_cast;</div>\n\
<div class=\"line\"><a name=\"l00041\"></a><span class=\"lineno\">   41</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00042\"></a><span class=\"lineno\">   42</span>&#160;    miCBoolean              refraction_receive;</div>\n\
<div class=\"line\"><a name=\"l00043\"></a><span class=\"lineno\">   43</span>&#160;    miCBoolean              refraction_cast;</div>\n\
<div class=\"line\"><a name=\"l00044\"></a><span class=\"lineno\">   44</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00045\"></a><span class=\"lineno\">   45</span>&#160;    miCBoolean              fg_receive;</div>\n\
<div class=\"line\"><a name=\"l00046\"></a><span class=\"lineno\">   46</span>&#160;    miCBoolean              fg_cast;</div>\n\
<div class=\"line\"><a name=\"l00047\"></a><span class=\"lineno\">   47</span>&#160;    miCBoolean              fg_visible;</div>\n\
<div class=\"line\"><a name=\"l00048\"></a><span class=\"lineno\">   48</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00049\"></a><span class=\"lineno\">   49</span>&#160;    miCBoolean              gi_receive;</div>\n\
<div class=\"line\"><a name=\"l00050\"></a><span class=\"lineno\">   50</span>&#160;    miCBoolean              gi_cast;</div>\n\
<div class=\"line\"><a name=\"l00051\"></a><span class=\"lineno\">   51</span>&#160;    miCBoolean              gi_visible;</div>\n\
<div class=\"line\"><a name=\"l00052\"></a><span class=\"lineno\">   52</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00053\"></a><span class=\"lineno\">   53</span>&#160;    miCBoolean              caustic_receive;</div>\n\
<div class=\"line\"><a name=\"l00054\"></a><span class=\"lineno\">   54</span>&#160;    miCBoolean              caustic_cast;</div>\n\
<div class=\"line\"><a name=\"l00055\"></a><span class=\"lineno\">   55</span>&#160;    miCBoolean              caustic_visible;</div>\n\
<div class=\"line\"><a name=\"l00056\"></a><span class=\"lineno\">   56</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00057\"></a><span class=\"lineno\">   57</span>&#160;    miCBoolean              shadow_receive;</div>\n\
<div class=\"line\"><a name=\"l00058\"></a><span class=\"lineno\">   58</span>&#160;    miCBoolean              shadow_cast;</div>\n\
<div class=\"line\"><a name=\"l00059\"></a><span class=\"lineno\">   59</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00060\"></a><span class=\"lineno\">   60</span>&#160;    xsimrInstanceFaceFlags  face;</div>\n\
<div class=\"line\"><a name=\"l00061\"></a><span class=\"lineno\">   61</span>&#160;} xsimrInstanceFlags;</div>\n\
<div class=\"line\"><a name=\"l00062\"></a><span class=\"lineno\">   62</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00063\"></a><span class=\"lineno\">   63</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00064\"></a><span class=\"lineno\">   64</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00065\"></a><span class=\"lineno\">   65</span>&#160;    miVector                scaling;</div>\n\
<div class=\"line\"><a name=\"l00066\"></a><span class=\"lineno\">   66</span>&#160;    miVector                translation;</div>\n\
<div class=\"line\"><a name=\"l00067\"></a><span class=\"lineno\">   67</span>&#160;    miQuaternion            rotation;</div>\n\
<div class=\"line\"><a name=\"l00068\"></a><span class=\"lineno\">   68</span>&#160;    miQuaternion            scale_orientation;</div>\n\
<div class=\"line\"><a name=\"l00069\"></a><span class=\"lineno\">   69</span>&#160;} xsimrInstanceTransform;</div>\n\
<div class=\"line\"><a name=\"l00070\"></a><span class=\"lineno\">   70</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00071\"></a><span class=\"lineno\">   71</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00072\"></a><span class=\"lineno\">   72</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00073\"></a><span class=\"lineno\">   73</span>&#160;    miUint4                 version;            <span class=\"comment\">// Version + Byteswap indicator</span></div>\n\
<div class=\"line\"><a name=\"l00074\"></a><span class=\"lineno\">   74</span>&#160;    miCBoolean              si_scaling;         <span class=\"comment\">// Perform SI scaling (as opposed to classical)</span></div>\n\
<div class=\"line\"><a name=\"l00075\"></a><span class=\"lineno\">   75</span>&#160;    miCBoolean              motionblur;         <span class=\"comment\">// Do motion blur</span></div>\n\
<div class=\"line\"><a name=\"l00076\"></a><span class=\"lineno\">   76</span>&#160;    xsimrInstanceFlags      flags;              <span class=\"comment\">// Instance&#39;s visibility flags</span></div>\n\
<div class=\"line\"><a name=\"l00077\"></a><span class=\"lineno\">   77</span>&#160;    xsimrInstanceTransform  open_transform;     <span class=\"comment\">// Instance&#39;s transform on shutter open</span></div>\n\
<div class=\"line\"><a name=\"l00078\"></a><span class=\"lineno\">   78</span>&#160;    xsimrInstanceTransform  close_transform;    <span class=\"comment\">// Instance&#39;s transform on shutter close (or if no motion blur)</span></div>\n\
<div class=\"line\"><a name=\"l00079\"></a><span class=\"lineno\">   79</span>&#160;} xsimrInstanceTransformData;</div>\n\
<div class=\"line\"><a name=\"l00080\"></a><span class=\"lineno\">   80</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00081\"></a><span class=\"lineno\">   81</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00082\"></a><span class=\"lineno\">   82</span>&#160;<span class=\"comment\">/* -----------------------------------------------------------*/</span></div>\n\
<div class=\"line\"><a name=\"l00105\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__LightAttributes.html#gaa7c5c2ea9d4f79ee937a1b47f09d65ac\">  105</a></span>&#160;<span class=\"preprocessor\">#define XSIMR_LIGHTDATA_LABEL       2860411             </span></div>\n\
<div class=\"line\"><a name=\"l00115\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga74650ad65c5a99135a0f10f4827f0b1a\">  115</a></span>&#160;<span class=\"preprocessor\">typedef enum</span></div>\n\
<div class=\"line\"><a name=\"l00116\"></a><span class=\"lineno\">  116</span>&#160;<span class=\"preprocessor\"></span>{</div>\n\
<div class=\"line\"><a name=\"l00117\"></a><span class=\"lineno\">  117</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga5f53374200cb0cb558be21eb81955ce1a88629f6f8c6285fc5229428f7855f075\">XSIMR_LF_DIFFUSE</a>            = 1 &lt;&lt; 0,               </div>\n\
<div class=\"line\"><a name=\"l00118\"></a><span class=\"lineno\">  118</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga5f53374200cb0cb558be21eb81955ce1a3f5d0ebd0717da87b049195685103a5c\">XSIMR_LF_SPECULAR</a>           = 1 &lt;&lt; 1                </div>\n\
<div class=\"line\"><a name=\"l00119\"></a><span class=\"lineno\">  119</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/xsi__miuserdata__defs_8h.html#a5f53374200cb0cb558be21eb81955ce1\">xsimrLightFlags</a>;</div>\n\
<div class=\"line\"><a name=\"l00127\"></a><span class=\"lineno\">  127</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00128\"></a><span class=\"lineno\">  128</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00129\"></a><span class=\"lineno\">  129</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/xsi__miuserdata__defs_8h.html#a5f53374200cb0cb558be21eb81955ce1\">xsimrLightFlags</a>             flags;   </div>\n\
<div class=\"line\"><a name=\"l00130\"></a><span class=\"lineno\">  130</span>&#160;} xsimrLightData;</div>\n\
<div class=\"line\"><a name=\"l00131\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrLightIllumData.html#ga96ca522efc914f26b10203946ec97b50\">  131</a></span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00132\"></a><span class=\"lineno\">  132</span>&#160;<span class=\"comment\">/* -----------------------------------------------------------*/</span></div>\n\
<div class=\"line\"><a name=\"l00145\"></a><span class=\"lineno\">  145</span>&#160;<span class=\"preprocessor\">#define XSIMR_LIGHTILLUMDATA_KEY        &quot;xsiLID&quot;        </span></div>\n\
<div class=\"line\"><a name=\"l00154\"></a><span class=\"lineno\">  154</span>&#160;<span class=\"preprocessor\">typedef struct</span></div>\n\
<div class=\"line\"><a name=\"l00155\"></a><span class=\"lineno\">  155</span>&#160;<span class=\"preprocessor\"></span>{</div>\n\
<div class=\"line\"><a name=\"l00156\"></a><span class=\"lineno\">  156</span>&#160;    miUint      struct_size;        </div>\n\
<div class=\"line\"><a name=\"l00158\"></a><span class=\"lineno\">  158</span>&#160;    miBoolean   set;                </div>\n\
<div class=\"line\"><a name=\"l00160\"></a><span class=\"lineno\">  160</span>&#160;    miScalar    diffuse;            </div>\n\
<div class=\"line\"><a name=\"l00161\"></a><span class=\"lineno\">  161</span>&#160;    miScalar    specular;           </div>\n\
<div class=\"line\"><a name=\"l00163\"></a><span class=\"lineno\">  163</span>&#160;    miColor     color;              </div>\n\
<div class=\"line\"><a name=\"l00164\"></a><span class=\"lineno\">  164</span>&#160;    miColor     shadow;             </div>\n\
<div class=\"line\"><a name=\"l00165\"></a><span class=\"lineno\">  165</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrLightIllumData.html\">xsimrLightIllumData</a>;</div>\n\
<div class=\"line\"><a name=\"l00166\"></a><span class=\"lineno\">  166</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00167\"></a><span class=\"lineno\">  167</span>&#160;<span class=\"comment\">/* -----------------------------------------------------------*/</span></div>\n\
<div class=\"line\"><a name=\"l00173\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a0519a88ae3f69d3ec4d0f1102166ee26\">  173</a></span>&#160;<span class=\"preprocessor\">#define XSIMR_RENDERMAPDATA_LABEL       0x2C1ACA        </span></div>\n\
<div class=\"line\"><a name=\"l00176\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262aab0f04dfb72623afdebc42abc4b92d3e\">  176</a></span>&#160;<span class=\"preprocessor\"></span><span class=\"comment\">/* Profile Curves ---------------------------------------------*/</span><span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00177\"></a><span class=\"lineno\">  177</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define XSIMR_PROFILECURVEDATA_LABEL        0x9FDDD497; // random.org</span></div>\n\
<div class=\"line\"><a name=\"l00178\"></a><span class=\"lineno\">  178</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00185\"></a><span class=\"lineno\">  185</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">enum</span></div>\n\
<div class=\"line\"><a name=\"l00186\"></a><span class=\"lineno\">  186</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00187\"></a><span class=\"lineno\">  187</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a0519a88ae3f69d3ec4d0f1102166ee26\">XSIMR_CE_CONSTANT</a>           = 1,    </div>\n\
<div class=\"line\"><a name=\"l00188\"></a><span class=\"lineno\">  188</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a1c39f68ebcab381da7d0201b4809b22f\">XSIMR_CE_END_GRADIENT</a>       = 2,    </div>\n\
<div class=\"line\"><a name=\"l00189\"></a><span class=\"lineno\">  189</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a2613bc80078e94e47a8ad05d9457ee5e\">XSIMR_CE_CYCLE</a>              = 3,    </div>\n\
<div class=\"line\"><a name=\"l00190\"></a><span class=\"lineno\">  190</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262aab0f04dfb72623afdebc42abc4b92d3e\">XSIMR_CE_CYCLE_RELATIVE</a>     = 4     </div>\n\
<div class=\"line\"><a name=\"l00192\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#gacd68013c12fb5d633bac0b75241d6206\">  192</a></span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga3d95229a01455c436e2538ac71e24262\">xsimrCurveExtrapolation</a>;</div>\n\
<div class=\"line\"><a name=\"l00193\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga97f1eeade9005dde161246c3aa875e14\">  193</a></span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00205\"></a><span class=\"lineno\">  205</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct </span>{</div>\n\
<div class=\"line\"><a name=\"l00206\"></a><span class=\"lineno\">  206</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga3d95229a01455c436e2538ac71e24262\">xsimrCurveExtrapolation</a> extrapolation_type;     </div>\n\
<div class=\"line\"><a name=\"l00207\"></a><span class=\"lineno\">  207</span>&#160;    miInteger               n_points;               </div>\n\
<div class=\"line\"><a name=\"l00208\"></a><span class=\"lineno\">  208</span>&#160;    miVector2d              points[ 1 ];            </div>\n\
<div class=\"line\"><a name=\"l00209\"></a><span class=\"lineno\">  209</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrProfileCurveData.html\">xsimrProfileCurveData</a>;</div>\n\
<div class=\"line\"><a name=\"l00210\"></a><span class=\"lineno\">  210</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00211\"></a><span class=\"lineno\">  211</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00212\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga5eacb8159cad288ce64d9d22afed6b0d\">  212</a></span>&#160;<span class=\"comment\">/* Particle Shape -----------------------------------------------------------*/</span></div>\n\
<div class=\"line\"><a name=\"l00213\"></a><span class=\"lineno\">  213</span>&#160;<span class=\"preprocessor\">#include &lt;shader.h&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00214\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da451705febc2d406136c69083621efa7f\">  214</a></span>&#160;<span class=\"preprocessor\">#include &lt;geoshader.h&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00215\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da50a14a123f1f3db0a1b28da00da17f3a\">  215</a></span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00216\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dab846e2d29fa459b838c52ccda7a30c5f\">  216</a></span>&#160;<span class=\"preprocessor\">#define XSIMR_POINTCLOUDDATA_LABEL          0x613EC66E      // random.org</span></div>\n\
<div class=\"line\"><a name=\"l00217\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da1aba4a32bbd15f23c311ee1ef27ae68b\">  217</a></span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00218\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dadf00806c3b99ed3270de66278bd542c0\">  218</a></span>&#160;<span class=\"preprocessor\">#define XSIMR_POINTCLOUDDATA_VERSION        0x020000        // 2.0</span></div>\n\
<div class=\"line\"><a name=\"l00219\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da76f7b8e6f48b5bdd5913f2d1fe19199c\">  219</a></span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00226\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da0544492b3f2503189c93c9877ad043d6\">  226</a></span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">enum</span></div>\n\
<div class=\"line\"><a name=\"l00227\"></a><span class=\"lineno\">  227</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00228\"></a><span class=\"lineno\">  228</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da451705febc2d406136c69083621efa7f\">xsimrSHAPE_POINT</a>,               </div>\n\
<div class=\"line\"><a name=\"l00229\"></a><span class=\"lineno\">  229</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da50a14a123f1f3db0a1b28da00da17f3a\">xsimrSHAPE_SEGMENT</a>,             </div>\n\
<div class=\"line\"><a name=\"l00230\"></a><span class=\"lineno\">  230</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dab846e2d29fa459b838c52ccda7a30c5f\">xsimrSHAPE_DISC</a>,                </div>\n\
<div class=\"line\"><a name=\"l00231\"></a><span class=\"lineno\">  231</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da1aba4a32bbd15f23c311ee1ef27ae68b\">xsimrSHAPE_RECTANGLE</a>,           </div>\n\
<div class=\"line\"><a name=\"l00232\"></a><span class=\"lineno\">  232</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dadf00806c3b99ed3270de66278bd542c0\">xsimrSHAPE_SPHERE</a>,              </div>\n\
<div class=\"line\"><a name=\"l00233\"></a><span class=\"lineno\">  233</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da76f7b8e6f48b5bdd5913f2d1fe19199c\">xsimrSHAPE_BOX</a>,                 </div>\n\
<div class=\"line\"><a name=\"l00234\"></a><span class=\"lineno\">  234</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da15c2bf1905c4d56e21378c4b61ffb0e4\">xsimrSHAPE_CYLINDER</a>,            </div>\n\
<div class=\"line\"><a name=\"l00235\"></a><span class=\"lineno\">  235</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0daa4fb94a29fae69350f60834290f16821\">xsimrSHAPE_CAPSULE</a>,             </div>\n\
<div class=\"line\"><a name=\"l00236\"></a><span class=\"lineno\">  236</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da55ffb198aa7a3189193588d09ef1b257\">xsimrSHAPE_CONE</a>,                </div>\n\
<div class=\"line\"><a name=\"l00237\"></a><span class=\"lineno\">  237</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da144fa1b1b1991b27180321b8236a5e8a\">xsimrSHAPE_BLOB</a>,                </div>\n\
<div class=\"line\"><a name=\"l00238\"></a><span class=\"lineno\">  238</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da73c686f367dd89428e94ac90573f96cd\">xsimrNB_SIMPLE_SHAPES</a>,          </div>\n\
<div class=\"line\"><a name=\"l00240\"></a><span class=\"lineno\">  240</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da0544492b3f2503189c93c9877ad043d6\">xsimrSHAPE_INSTANCE</a>     = 128,  </div>\n\
<div class=\"line\"><a name=\"l00241\"></a><span class=\"lineno\">  241</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga5eacb8159cad288ce64d9d22afed6b0d\">xsimrParticleShapeType</a>;</div>\n\
<div class=\"line\"><a name=\"l00348\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structxsimrParticleBlob.html\">  348</a></span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00349\"></a><span class=\"lineno\">  349</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00350\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#gaa9831b27d43e13316c674746b6efccb1\">  350</a></span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga5eacb8159cad288ce64d9d22afed6b0d\">xsimrParticleShapeType</a>      type;           </div>\n\
<div class=\"line\"><a name=\"l00351\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga7d958482ce00994394098552086a532b\">  351</a></span>&#160;    miInteger                   instance_id;    </div>\n\
<div class=\"line\"><a name=\"l00354\"></a><span class=\"lineno\">  354</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrParticleShape.html\">xsimrParticleShape</a>;</div>\n\
<div class=\"line\"><a name=\"l00355\"></a><span class=\"lineno\">  355</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00356\"></a><span class=\"lineno\">  356</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00362\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42aa1a2979f8a8a459cc40218f1f0e2619d\">  362</a></span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00363\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a7ff8576e08c96f6f80c728cee5ba37ea\">  363</a></span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00364\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad8f590fdc09c88aab6755166ba10ba55\">  364</a></span>&#160;    miUint                      size;       </div>\n\
<div class=\"line\"><a name=\"l00365\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a656881d1885262ca2c9f28ee1cea2eb2\">  365</a></span>&#160;    miUint                      offset;     </div>\n\
<div class=\"line\"><a name=\"l00366\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a34293f159fe6f46a837dc90d224912e4\">  366</a></span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrParticleBlob.html\">xsimrParticleBlob</a>;</div>\n\
<div class=\"line\"><a name=\"l00367\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ac222f452976806de0437fef7b8ee2686\">  367</a></span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00374\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad15482a4bacafaf18aa1ae1035c10bd2\">  374</a></span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">enum</span></div>\n\
<div class=\"line\"><a name=\"l00375\"></a><span class=\"lineno\">  375</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00376\"></a><span class=\"lineno\">  376</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42aa1a2979f8a8a459cc40218f1f0e2619d\">xsimrATTRIBUTE_BOOLEAN</a>,     </div>\n\
<div class=\"line\"><a name=\"l00377\"></a><span class=\"lineno\">  377</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a7ff8576e08c96f6f80c728cee5ba37ea\">xsimrATTRIBUTE_INTEGER</a>,     </div>\n\
<div class=\"line\"><a name=\"l00378\"></a><span class=\"lineno\">  378</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad8f590fdc09c88aab6755166ba10ba55\">xsimrATTRIBUTE_SCALAR</a>,      </div>\n\
<div class=\"line\"><a name=\"l00379\"></a><span class=\"lineno\">  379</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a656881d1885262ca2c9f28ee1cea2eb2\">xsimrATTRIBUTE_VECTOR2</a>,     </div>\n\
<div class=\"line\"><a name=\"l00380\"></a><span class=\"lineno\">  380</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a34293f159fe6f46a837dc90d224912e4\">xsimrATTRIBUTE_VECTOR3</a>,     </div>\n\
<div class=\"line\"><a name=\"l00381\"></a><span class=\"lineno\">  381</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ac222f452976806de0437fef7b8ee2686\">xsimrATTRIBUTE_VECTOR4</a>,     </div>\n\
<div class=\"line\"><a name=\"l00382\"></a><span class=\"lineno\">  382</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ac7e9f8c73c398e1f17c743f4f13d2cde\">xsimrATTRIBUTE_QUATERNION</a>,  </div>\n\
<div class=\"line\"><a name=\"l00383\"></a><span class=\"lineno\">  383</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a5061dc718be550578c5c2ac7b6ffdddb\">xsimrATTRIBUTE_MATRIX33</a>,    </div>\n\
<div class=\"line\"><a name=\"l00384\"></a><span class=\"lineno\">  384</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a6d643961da9008783fbfe11d1a50250e\">xsimrATTRIBUTE_MATRIX44</a>,    </div>\n\
<div class=\"line\"><a name=\"l00385\"></a><span class=\"lineno\">  385</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a2aad9eb197b76788873beaaae1879707\">xsimrATTRIBUTE_COLOR4</a>,      </div>\n\
<div class=\"line\"><a name=\"l00386\"></a><span class=\"lineno\">  386</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a492ec724c9f2282dd64edf9c618ddc4b\">xsimrATTRIBUTE_ROTATION</a>,    </div>\n\
<div class=\"line\"><a name=\"l00387\"></a><span class=\"lineno\">  387</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a0e1c20a5ccfe43e65afe1668999c2aef\">xsimrATTRIBUTE_SHAPE</a>,       </div>\n\
<div class=\"line\"><a name=\"l00388\"></a><span class=\"lineno\">  388</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad15482a4bacafaf18aa1ae1035c10bd2\">xsimrATTRIBUTE_BLOB</a>,        </div>\n\
<div class=\"line\"><a name=\"l00389\"></a><span class=\"lineno\">  389</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#ga9796e541f5ad6a01e5710ee18273ad42\">xsimrAttributeType</a>;</div>\n\
<div class=\"line\"><a name=\"l00427\"></a><span class=\"lineno\">  427</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00428\"></a><span class=\"lineno\">  428</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00431\"></a><span class=\"lineno\">  431</span>&#160;    miTag           name;           <span class=\"comment\">// The attribute&#39;s name</span></div>\n\
<div class=\"line\"><a name=\"l00432\"></a><span class=\"lineno\">  432</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00436\"></a><span class=\"lineno\">  436</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#ga9796e541f5ad6a01e5710ee18273ad42\">xsimrAttributeType</a>  type;   <span class=\"comment\">// The attribute&#39;s data type</span></div>\n\
<div class=\"line\"><a name=\"l00437\"></a><span class=\"lineno\">  437</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00447\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga83bdd9bbdce821b671e8097c6992f327\">  447</a></span>&#160;    miBoolean       constant;</div>\n\
<div class=\"line\"><a name=\"l00448\"></a><span class=\"lineno\">  448</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00452\"></a><span class=\"lineno\">  452</span>&#160;    miUint          size;</div>\n\
<div class=\"line\"><a name=\"l00453\"></a><span class=\"lineno\">  453</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00461\"></a><span class=\"lineno\">  461</span>&#160;    miTag           offsets;</div>\n\
<div class=\"line\"><a name=\"l00462\"></a><span class=\"lineno\">  462</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00468\"></a><span class=\"lineno\">  468</span>&#160;    miTag           data;           <span class=\"comment\">// The userdata tag for the data blob.</span></div>\n\
<div class=\"line\"><a name=\"l00469\"></a><span class=\"lineno\">  469</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00474\"></a><span class=\"lineno\">  474</span>&#160;    miTag           blob_type;</div>\n\
<div class=\"line\"><a name=\"l00475\"></a><span class=\"lineno\">  475</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrAttributeData.html\">xsimrAttributeData</a>;</div>\n\
<div class=\"line\"><a name=\"l00476\"></a><span class=\"lineno\">  476</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00477\"></a><span class=\"lineno\">  477</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00493\"></a><span class=\"lineno\">  493</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00494\"></a><span class=\"lineno\">  494</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00495\"></a><span class=\"lineno\">  495</span>&#160;    miUint          version;            </div>\n\
<div class=\"line\"><a name=\"l00496\"></a><span class=\"lineno\">  496</span>&#160;    miUint          nb_particles;       </div>\n\
<div class=\"line\"><a name=\"l00497\"></a><span class=\"lineno\">  497</span>&#160;    miTag           positions;          </div>\n\
<div class=\"line\"><a name=\"l00499\"></a><span class=\"lineno\">  499</span>&#160;    <span class=\"keywordtype\">int</span>             i_data;             </div>\n\
<div class=\"line\"><a name=\"l00500\"></a><span class=\"lineno\">  500</span>&#160;    <span class=\"keywordtype\">int</span>             n_data;             </div>\n\
<div class=\"line\"><a name=\"l00502\"></a><span class=\"lineno\">  502</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrAttributeData.html\">xsimrAttributeData</a> attributes[ 1 ]; </div>\n\
<div class=\"line\"><a name=\"l00503\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__PointCloudDefines.html#ga39bf0d4e0b4f0064fd2699e10a7c6edf\">  503</a></span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrPointCloudData.html\">xsimrPointCloudData</a>;</div>\n\
<div class=\"line\"><a name=\"l00504\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/group__PointCloudDefines.html#gafb87c3492f7450d9d1871c80987965fe\">  504</a></span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00505\"></a><span class=\"lineno\">  505</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00506\"></a><span class=\"lineno\">  506</span>&#160;<span class=\"comment\">// Instance Marker</span></div>\n\
<div class=\"line\"><a name=\"l00507\"></a><span class=\"lineno\">  507</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00517\"></a><span class=\"lineno\">  517</span>&#160;<span class=\"preprocessor\">#define XSIMR_POINTCLOUD_INDEX_LABEL        0x613EC66F      </span></div>\n\
<div class=\"line\"><a name=\"l00518\"></a><span class=\"lineno\">  518</span>&#160;<span class=\"preprocessor\">#define XSIMR_ATTRIBUTE_SHADER_KEY          &quot;xsiATTR&quot;       </span></div>\n\
<div class=\"line\"><a name=\"l00527\"></a><span class=\"lineno\">  527</span>&#160;<span class=\"preprocessor\">typedef struct</span></div>\n\
<div class=\"line\"><a name=\"l00528\"></a><span class=\"lineno\">  528</span>&#160;<span class=\"preprocessor\"></span>{</div>\n\
<div class=\"line\"><a name=\"l00529\"></a><span class=\"lineno\">  529</span>&#160;    miUint          pc_index;   </div>\n\
<div class=\"line\"><a name=\"l00530\"></a><span class=\"lineno\">  530</span>&#160;    miUint          st_index;   </div>\n\
<div class=\"line\"><a name=\"l00531\"></a><span class=\"lineno\">  531</span>&#160;} xsimrPointCloudIndex;</div>\n\
<div class=\"line\"><a name=\"l00535\"></a><span class=\"lineno\">  535</span>&#160;<span class=\"comment\">// Time mapping data for attribute time-controlled images</span></div>\n\
<div class=\"line\"><a name=\"l00543\"></a><span class=\"lineno\">  543</span>&#160;<span class=\"comment\"></span><span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00544\"></a><span class=\"lineno\">  544</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00545\"></a><span class=\"lineno\">  545</span>&#160;    miScalar            range_min;      </div>\n\
<div class=\"line\"><a name=\"l00546\"></a><span class=\"lineno\">  546</span>&#160;    miScalar            range_max;      </div>\n\
<div class=\"line\"><a name=\"l00547\"></a><span class=\"lineno\">  547</span>&#160;    miInteger           index;          </div>\n\
<div class=\"line\"><a name=\"l00548\"></a><span class=\"lineno\">  548</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrTimeMapValue.html\">xsimrTimeMapValue</a>;</div>\n\
<div class=\"line\"><a name=\"l00549\"></a><span class=\"lineno\">  549</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00557\"></a><span class=\"lineno\">  557</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00558\"></a><span class=\"lineno\">  558</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00559\"></a><span class=\"lineno\">  559</span>&#160;    miInteger           n_time_map;         </div>\n\
<div class=\"line\"><a name=\"l00560\"></a><span class=\"lineno\">  560</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrTimeMapValue.html\">xsimrTimeMapValue</a>   time_map[ 1 ];      </div>\n\
<div class=\"line\"><a name=\"l00561\"></a><span class=\"lineno\">  561</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrAttributeImageTimeMap.html\">xsimrAttributeImageTimeMap</a>;</div>\n\
<div class=\"line\"><a name=\"l00562\"></a><span class=\"lineno\">  562</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00564\"></a><span class=\"lineno\">  564</span>&#160;<span class=\"comment\">// Color Correction Look-up Table Definition</span></div>\n\
<div class=\"line\"><a name=\"l00565\"></a><span class=\"lineno\">  565</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00566\"></a><span class=\"lineno\">  566</span>&#160;<span class=\"preprocessor\">#define XSIMR_CCLUT_GAMMA_LABEL     0x0A63EC03  // random.org</span></div>\n\
<div class=\"line\"><a name=\"l00567\"></a><span class=\"lineno\">  567</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define XSIMR_CCLUT_1D_LABEL        0x0F2F2674  // random.org</span></div>\n\
<div class=\"line\"><a name=\"l00568\"></a><span class=\"lineno\">  568</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define XSIMR_CCLUT_3D_LABEL        0x088F67E5  // random.org</span></div>\n\
<div class=\"line\"><a name=\"l00569\"></a><span class=\"lineno\">  569</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00570\"></a><span class=\"lineno\">  570</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00571\"></a><span class=\"lineno\">  571</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00572\"></a><span class=\"lineno\">  572</span>&#160;    miScalar        r, g, b;</div>\n\
<div class=\"line\"><a name=\"l00573\"></a><span class=\"lineno\">  573</span>&#160;} xsimrColor3;</div>\n\
<div class=\"line\"><a name=\"l00574\"></a><span class=\"lineno\">  574</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00575\"></a><span class=\"lineno\">  575</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00576\"></a><span class=\"lineno\">  576</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00577\"></a><span class=\"lineno\">  577</span>&#160;    miScalar        red_gamma;</div>\n\
<div class=\"line\"><a name=\"l00578\"></a><span class=\"lineno\">  578</span>&#160;    miScalar        green_gamma;</div>\n\
<div class=\"line\"><a name=\"l00579\"></a><span class=\"lineno\">  579</span>&#160;    miScalar        blue_gamma;</div>\n\
<div class=\"line\"><a name=\"l00580\"></a><span class=\"lineno\">  580</span>&#160;} xsimrCCLUTGamma;</div>\n\
<div class=\"line\"><a name=\"l00581\"></a><span class=\"lineno\">  581</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00582\"></a><span class=\"lineno\">  582</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00583\"></a><span class=\"lineno\">  583</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00584\"></a><span class=\"lineno\">  584</span>&#160;    miScalar        from;</div>\n\
<div class=\"line\"><a name=\"l00585\"></a><span class=\"lineno\">  585</span>&#160;    miScalar        to;</div>\n\
<div class=\"line\"><a name=\"l00586\"></a><span class=\"lineno\">  586</span>&#160;} xsimrCCLUTMapTuple;</div>\n\
<div class=\"line\"><a name=\"l00587\"></a><span class=\"lineno\">  587</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00588\"></a><span class=\"lineno\">  588</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00589\"></a><span class=\"lineno\">  589</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00590\"></a><span class=\"lineno\">  590</span>&#160;    <span class=\"keywordtype\">int</span>             i_tuple;</div>\n\
<div class=\"line\"><a name=\"l00591\"></a><span class=\"lineno\">  591</span>&#160;    <span class=\"keywordtype\">int</span>             n_tuple;</div>\n\
<div class=\"line\"><a name=\"l00592\"></a><span class=\"lineno\">  592</span>&#160;    xsimrCCLUTMapTuple tuple[ 1 ];</div>\n\
<div class=\"line\"><a name=\"l00593\"></a><span class=\"lineno\">  593</span>&#160;} xsimrCCLUTRangeMap;</div>\n\
<div class=\"line\"><a name=\"l00594\"></a><span class=\"lineno\">  594</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00595\"></a><span class=\"lineno\">  595</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct </span></div>\n\
<div class=\"line\"><a name=\"l00596\"></a><span class=\"lineno\">  596</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00597\"></a><span class=\"lineno\">  597</span>&#160;    miTag           name;</div>\n\
<div class=\"line\"><a name=\"l00598\"></a><span class=\"lineno\">  598</span>&#160;    miTag           params;</div>\n\
<div class=\"line\"><a name=\"l00599\"></a><span class=\"lineno\">  599</span>&#160;} xsimrCCLUTPreTransform;</div>\n\
<div class=\"line\"><a name=\"l00600\"></a><span class=\"lineno\">  600</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00601\"></a><span class=\"lineno\">  601</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00602\"></a><span class=\"lineno\">  602</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00603\"></a><span class=\"lineno\">  603</span>&#160;    xsimrCCLUTRangeMap  red_range;</div>\n\
<div class=\"line\"><a name=\"l00604\"></a><span class=\"lineno\">  604</span>&#160;    xsimrCCLUTRangeMap  green_range;</div>\n\
<div class=\"line\"><a name=\"l00605\"></a><span class=\"lineno\">  605</span>&#160;    xsimrCCLUTRangeMap  blue_range;</div>\n\
<div class=\"line\"><a name=\"l00606\"></a><span class=\"lineno\">  606</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00607\"></a><span class=\"lineno\">  607</span>&#160;    <span class=\"keywordtype\">int</span>             i_lut;</div>\n\
<div class=\"line\"><a name=\"l00608\"></a><span class=\"lineno\">  608</span>&#160;    <span class=\"keywordtype\">int</span>             n_lut;</div>\n\
<div class=\"line\"><a name=\"l00609\"></a><span class=\"lineno\">  609</span>&#160;    xsimrColor3     lut[ 1 ];</div>\n\
<div class=\"line\"><a name=\"l00610\"></a><span class=\"lineno\">  610</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00611\"></a><span class=\"lineno\">  611</span>&#160;    xsimrCCLUTPreTransform pretransform;</div>\n\
<div class=\"line\"><a name=\"l00612\"></a><span class=\"lineno\">  612</span>&#160;} xsimrCCLUT1D;</div>\n\
<div class=\"line\"><a name=\"l00613\"></a><span class=\"lineno\">  613</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00614\"></a><span class=\"lineno\">  614</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00615\"></a><span class=\"lineno\">  615</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00616\"></a><span class=\"lineno\">  616</span>&#160;    xsimrCCLUTRangeMap  red_range;</div>\n\
<div class=\"line\"><a name=\"l00617\"></a><span class=\"lineno\">  617</span>&#160;    xsimrCCLUTRangeMap  green_range;</div>\n\
<div class=\"line\"><a name=\"l00618\"></a><span class=\"lineno\">  618</span>&#160;    xsimrCCLUTRangeMap  blue_range;</div>\n\
<div class=\"line\"><a name=\"l00619\"></a><span class=\"lineno\">  619</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00620\"></a><span class=\"lineno\">  620</span>&#160;    <span class=\"comment\">// red_size * green_size * blue_size == n_lut</span></div>\n\
<div class=\"line\"><a name=\"l00621\"></a><span class=\"lineno\">  621</span>&#160;    <span class=\"keywordtype\">int</span>             red_size;</div>\n\
<div class=\"line\"><a name=\"l00622\"></a><span class=\"lineno\">  622</span>&#160;    <span class=\"keywordtype\">int</span>             green_size;</div>\n\
<div class=\"line\"><a name=\"l00623\"></a><span class=\"lineno\">  623</span>&#160;    <span class=\"keywordtype\">int</span>             blue_size;</div>\n\
<div class=\"line\"><a name=\"l00624\"></a><span class=\"lineno\">  624</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00625\"></a><span class=\"lineno\">  625</span>&#160;    <span class=\"keywordtype\">int</span>             i_lut;</div>\n\
<div class=\"line\"><a name=\"l00626\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structxsimrMeshAttribute.html\">  626</a></span>&#160;    <span class=\"keywordtype\">int</span>             n_lut;</div>\n\
<div class=\"line\"><a name=\"l00627\"></a><span class=\"lineno\">  627</span>&#160;    xsimrColor3     lut[ 1 ];</div>\n\
<div class=\"line\"><a name=\"l00628\"></a><span class=\"lineno\">  628</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00629\"></a><span class=\"lineno\">  629</span>&#160;    xsimrCCLUTPreTransform pretransform;</div>\n\
<div class=\"line\"><a name=\"l00630\"></a><span class=\"lineno\">  630</span>&#160;} xsimrCCLUT3D;</div>\n\
<div class=\"line\"><a name=\"l00631\"></a><span class=\"lineno\">  631</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00632\"></a><span class=\"lineno\">  632</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00633\"></a><span class=\"lineno\">  633</span>&#160;<span class=\"preprocessor\">#define XSIMR_MESHDATA_LABEL            0x112A61FF      // random.org</span></div>\n\
<div class=\"line\"><a name=\"l00634\"></a><span class=\"lineno\">  634</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define XSIMR_MESHDATA_VERSION          0x010000        // 1.0</span></div>\n\
<div class=\"line\"><a name=\"l00635\"></a><span class=\"lineno\">  635</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00636\"></a><span class=\"lineno\">  636</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">enum</span></div>\n\
<div class=\"line\"><a name=\"l00637\"></a><span class=\"lineno\">  637</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00638\"></a><span class=\"lineno\">  638</span>&#160;    xsimrMESHATTRIBUTESTORAGE_CONSTANT, </div>\n\
<div class=\"line\"><a name=\"l00639\"></a><span class=\"lineno\">  639</span>&#160;    xsimrMESHATTRIBUTESTORAGE_TSPACE,</div>\n\
<div class=\"line\"><a name=\"l00640\"></a><span class=\"lineno\">  640</span>&#160;} xsimrMeshAttributeStorage;</div>\n\
<div class=\"line\"><a name=\"l00641\"></a><span class=\"lineno\">  641</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00647\"></a><span class=\"lineno\">  647</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00648\"></a><span class=\"lineno\">  648</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00649\"></a><span class=\"lineno\">  649</span>&#160;    <span class=\"keywordtype\">char</span>                        name[256];  <span class=\"comment\">// A string with the attribute name</span></div>\n\
<div class=\"line\"><a name=\"l00650\"></a><span class=\"lineno\">  650</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#ga9796e541f5ad6a01e5710ee18273ad42\">xsimrAttributeType</a>          type;       <span class=\"comment\">// The attribute type. For constant storage, constant_data contains the per mesh value.</span></div>\n\
<div class=\"line\"><a name=\"l00651\"></a><span class=\"lineno\">  651</span>&#160;    xsimrMeshAttributeStorage   storage;    <span class=\"comment\">// The attribute storage. Attributes can be defined as tspace, per vertex userdata or constant.</span></div>\n\
<div class=\"line\"><a name=\"l00652\"></a><span class=\"lineno\">  652</span>&#160;    miInteger                   id;         <span class=\"comment\">// The index for tspace or vertex user data storage.</span></div>\n\
<div class=\"line\"><a name=\"l00653\"></a><span class=\"lineno\">  653</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00654\"></a><span class=\"lineno\">  654</span>&#160;    <span class=\"comment\">// A union for the constant data.</span></div>\n\
<div class=\"line\"><a name=\"l00655\"></a><span class=\"lineno\">  655</span>&#160;    <span class=\"keyword\">union </span></div>\n\
<div class=\"line\"><a name=\"l00656\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/structxsimrMesh.html\">  656</a></span>&#160;    {</div>\n\
<div class=\"line\"><a name=\"l00657\"></a><span class=\"lineno\">  657</span>&#160;        miCBoolean      b;</div>\n\
<div class=\"line\"><a name=\"l00658\"></a><span class=\"lineno\">  658</span>&#160;        miInteger       i;</div>\n\
<div class=\"line\"><a name=\"l00659\"></a><span class=\"lineno\">  659</span>&#160;        miScalar        s;</div>\n\
<div class=\"line\"><a name=\"l00660\"></a><span class=\"lineno\">  660</span>&#160;        miVector2d      v2;</div>\n\
<div class=\"line\"><a name=\"l00661\"></a><span class=\"lineno\">  661</span>&#160;        miVector        v3;</div>\n\
<div class=\"line\"><a name=\"l00662\"></a><span class=\"lineno\">  662</span>&#160;        miQuaternion    v4;</div>\n\
<div class=\"line\"><a name=\"l00663\"></a><span class=\"lineno\">  663</span>&#160;        miVector        m33[3];</div>\n\
<div class=\"line\"><a name=\"l00664\"></a><span class=\"lineno\">  664</span>&#160;        miMatrix        m44;</div>\n\
<div class=\"line\"><a name=\"l00665\"></a><span class=\"lineno\">  665</span>&#160;        miColor         c;</div>\n\
<div class=\"line\"><a name=\"l00666\"></a><span class=\"lineno\">  666</span>&#160;    } constant_data;</div>\n\
<div class=\"line\"><a name=\"l00667\"></a><span class=\"lineno\">  667</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00668\"></a><span class=\"lineno\">  668</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrMeshAttribute.html\">xsimrMeshAttribute</a>;</div>\n\
<div class=\"line\"><a name=\"l00669\"></a><span class=\"lineno\">  669</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00677\"></a><span class=\"lineno\">  677</span>&#160;<span class=\"keyword\">typedef</span> <span class=\"keyword\">struct</span></div>\n\
<div class=\"line\"><a name=\"l00678\"></a><span class=\"lineno\">  678</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00679\"></a><span class=\"lineno\">  679</span>&#160;    <span class=\"comment\">// An array of xsimrMeshAttribute that represents the pushed attributes</span></div>\n\
<div class=\"line\"><a name=\"l00680\"></a><span class=\"lineno\">  680</span>&#160;    <span class=\"keywordtype\">int</span> i_attributes;</div>\n\
<div class=\"line\"><a name=\"l00681\"></a><span class=\"lineno\">  681</span>&#160;    <span class=\"keywordtype\">int</span> n_attributes;</div>\n\
<div class=\"line\"><a name=\"l00682\"></a><span class=\"lineno\">  682</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrMeshAttribute.html\">xsimrMeshAttribute</a> attributes[ 1 ];</div>\n\
<div class=\"line\"><a name=\"l00683\"></a><span class=\"lineno\">  683</span>&#160;} <a class=\"code\" href=\"#!/url=./si_cpp/structxsimrMesh.html\">xsimrMesh</a>;</div>\n\
<div class=\"line\"><a name=\"l00684\"></a><span class=\"lineno\">  684</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00685\"></a><span class=\"lineno\">  685</span>&#160;<span class=\"preprocessor\">#endif </span><span class=\"comment\">/* XSI_MIUSERDATA_DEFS_H */</span><span class=\"preprocessor\"></span></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0daa4fb94a29fae69350f60834290f16821\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0daa4fb94a29fae69350f60834290f16821\">xsimrSHAPE_CAPSULE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:221</div></div>\n\
<div class=\"ttc\" id=\"structxsimrLightIllumData_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrLightIllumData.html\">xsimrLightIllumData</a></div><div class=\"ttdoc\">If set by a shader, will be filled in by Softimage&#39;s light shaders to contain a separated light and s...</div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:140</div></div>\n\
<div class=\"ttc\" id=\"structxsimrPointCloudData_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrPointCloudData.html\">xsimrPointCloudData</a></div><div class=\"ttdoc\">The main particle data header. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:479</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da76f7b8e6f48b5bdd5913f2d1fe19199c\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da76f7b8e6f48b5bdd5913f2d1fe19199c\">xsimrSHAPE_BOX</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:219</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da0544492b3f2503189c93c9877ad043d6\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da0544492b3f2503189c93c9877ad043d6\">xsimrSHAPE_INSTANCE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:226</div></div>\n\
<div class=\"ttc\" id=\"structxsimrAttributeData_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrAttributeData.html\">xsimrAttributeData</a></div><div class=\"ttdoc\">A structure containing the information for a single attribute. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:413</div></div>\n\
<div class=\"ttc\" id=\"structxsimrMesh_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrMesh.html\">xsimrMesh</a></div><div class=\"ttdoc\">A user data applied on meshes. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:656</div></div>\n\
<div class=\"ttc\" id=\"xsi__miuserdata__defs_8h_html_a5f53374200cb0cb558be21eb81955ce1\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__miuserdata__defs_8h.html#a5f53374200cb0cb558be21eb81955ce1\">xsimrLightFlags</a></div><div class=\"ttdeci\">xsimrLightFlags</div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:107</div></div>\n\
<div class=\"ttc\" id=\"structxsimrParticleBlob_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrParticleBlob.html\">xsimrParticleBlob</a></div><div class=\"ttdoc\">Particle data blob structure. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:348</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da15c2bf1905c4d56e21378c4b61ffb0e4\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da15c2bf1905c4d56e21378c4b61ffb0e4\">xsimrSHAPE_CYLINDER</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:220</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga3d95229a01455c436e2538ac71e24262aab0f04dfb72623afdebc42abc4b92d3e\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262aab0f04dfb72623afdebc42abc4b92d3e\">XSIMR_CE_CYCLE_RELATIVE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:176</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga3d95229a01455c436e2538ac71e24262a0519a88ae3f69d3ec4d0f1102166ee26\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a0519a88ae3f69d3ec4d0f1102166ee26\">XSIMR_CE_CONSTANT</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:173</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da55ffb198aa7a3189193588d09ef1b257\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da55ffb198aa7a3189193588d09ef1b257\">xsimrSHAPE_CONE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:222</div></div>\n\
<div class=\"ttc\" id=\"structxsimrMeshAttribute_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrMeshAttribute.html\">xsimrMeshAttribute</a></div><div class=\"ttdoc\">A structure representing an ICE attribute on a mesh. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:626</div></div>\n\
<div class=\"ttc\" id=\"structxsimrTimeMapValue_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrTimeMapValue.html\">xsimrTimeMapValue</a></div><div class=\"ttdoc\">A single range to frame mapping entry. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:522</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da50a14a123f1f3db0a1b28da00da17f3a\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da50a14a123f1f3db0a1b28da00da17f3a\">xsimrSHAPE_SEGMENT</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:215</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a492ec724c9f2282dd64edf9c618ddc4b\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a492ec724c9f2282dd64edf9c618ddc4b\">xsimrATTRIBUTE_ROTATION</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:372</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_ga9796e541f5ad6a01e5710ee18273ad42\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#ga9796e541f5ad6a01e5710ee18273ad42\">xsimrAttributeType</a></div><div class=\"ttdeci\">xsimrAttributeType</div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:360</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42ad8f590fdc09c88aab6755166ba10ba55\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad8f590fdc09c88aab6755166ba10ba55\">xsimrATTRIBUTE_SCALAR</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:364</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a6d643961da9008783fbfe11d1a50250e\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a6d643961da9008783fbfe11d1a50250e\">xsimrATTRIBUTE_MATRIX44</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:370</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da1aba4a32bbd15f23c311ee1ef27ae68b\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da1aba4a32bbd15f23c311ee1ef27ae68b\">xsimrSHAPE_RECTANGLE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:217</div></div>\n\
<div class=\"ttc\" id=\"group__RenderMapDefine_html_ga5f53374200cb0cb558be21eb81955ce1a3f5d0ebd0717da87b049195685103a5c\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga5f53374200cb0cb558be21eb81955ce1a3f5d0ebd0717da87b049195685103a5c\">XSIMR_LF_SPECULAR</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:110</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42ac222f452976806de0437fef7b8ee2686\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ac222f452976806de0437fef7b8ee2686\">xsimrATTRIBUTE_VECTOR4</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:367</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42ad15482a4bacafaf18aa1ae1035c10bd2\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ad15482a4bacafaf18aa1ae1035c10bd2\">xsimrATTRIBUTE_BLOB</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:374</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a656881d1885262ca2c9f28ee1cea2eb2\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a656881d1885262ca2c9f28ee1cea2eb2\">xsimrATTRIBUTE_VECTOR2</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:365</div></div>\n\
<div class=\"ttc\" id=\"group__RenderMapDefine_html_ga5f53374200cb0cb558be21eb81955ce1a88629f6f8c6285fc5229428f7855f075\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__RenderMapDefine.html#ga5f53374200cb0cb558be21eb81955ce1a88629f6f8c6285fc5229428f7855f075\">XSIMR_LF_DIFFUSE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:109</div></div>\n\
<div class=\"ttc\" id=\"structxsimrProfileCurveData_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrProfileCurveData.html\">xsimrProfileCurveData</a></div><div class=\"ttdoc\">A profile curve data sampled into linear segments. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:191</div></div>\n\
<div class=\"ttc\" id=\"structxsimrAttributeImageTimeMap_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrAttributeImageTimeMap.html\">xsimrAttributeImageTimeMap</a></div><div class=\"ttdoc\">List of range to frame mapping values. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:536</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da73c686f367dd89428e94ac90573f96cd\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da73c686f367dd89428e94ac90573f96cd\">xsimrNB_SIMPLE_SHAPES</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:224</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a0e1c20a5ccfe43e65afe1668999c2aef\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a0e1c20a5ccfe43e65afe1668999c2aef\">xsimrATTRIBUTE_SHAPE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:373</div></div>\n\
<div class=\"ttc\" id=\"structxsimrParticleShape_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structxsimrParticleShape.html\">xsimrParticleShape</a></div><div class=\"ttdoc\">Particle shape structure. </div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:334</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga3d95229a01455c436e2538ac71e24262a2613bc80078e94e47a8ad05d9457ee5e\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a2613bc80078e94e47a8ad05d9457ee5e\">XSIMR_CE_CYCLE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:175</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a2aad9eb197b76788873beaaae1879707\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a2aad9eb197b76788873beaaae1879707\">xsimrATTRIBUTE_COLOR4</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:371</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da451705febc2d406136c69083621efa7f\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da451705febc2d406136c69083621efa7f\">xsimrSHAPE_POINT</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:214</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a5061dc718be550578c5c2ac7b6ffdddb\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a5061dc718be550578c5c2ac7b6ffdddb\">xsimrATTRIBUTE_MATRIX33</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:369</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0dab846e2d29fa459b838c52ccda7a30c5f\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dab846e2d29fa459b838c52ccda7a30c5f\">xsimrSHAPE_DISC</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:216</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a7ff8576e08c96f6f80c728cee5ba37ea\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a7ff8576e08c96f6f80c728cee5ba37ea\">xsimrATTRIBUTE_INTEGER</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:363</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga3d95229a01455c436e2538ac71e24262a1c39f68ebcab381da7d0201b4809b22f\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga3d95229a01455c436e2538ac71e24262a1c39f68ebcab381da7d0201b4809b22f\">XSIMR_CE_END_GRADIENT</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:174</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_ga5eacb8159cad288ce64d9d22afed6b0d\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga5eacb8159cad288ce64d9d22afed6b0d\">xsimrParticleShapeType</a></div><div class=\"ttdeci\">xsimrParticleShapeType</div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:212</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_ga3d95229a01455c436e2538ac71e24262\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#ga3d95229a01455c436e2538ac71e24262\">xsimrCurveExtrapolation</a></div><div class=\"ttdeci\">xsimrCurveExtrapolation</div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:171</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0dadf00806c3b99ed3270de66278bd542c0\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0dadf00806c3b99ed3270de66278bd542c0\">xsimrSHAPE_SPHERE</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:218</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42ac7e9f8c73c398e1f17c743f4f13d2cde\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42ac7e9f8c73c398e1f17c743f4f13d2cde\">xsimrATTRIBUTE_QUATERNION</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:368</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42a34293f159fe6f46a837dc90d224912e4\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42a34293f159fe6f46a837dc90d224912e4\">xsimrATTRIBUTE_VECTOR3</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:366</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrAttributeType_html_gga9796e541f5ad6a01e5710ee18273ad42aa1a2979f8a8a459cc40218f1f0e2619d\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrAttributeType.html#gga9796e541f5ad6a01e5710ee18273ad42aa1a2979f8a8a459cc40218f1f0e2619d\">xsimrATTRIBUTE_BOOLEAN</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:362</div></div>\n\
<div class=\"ttc\" id=\"group__xsimrCurveExtrapolation_html_gga5eacb8159cad288ce64d9d22afed6b0da144fa1b1b1991b27180321b8236a5e8a\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/group__xsimrCurveExtrapolation.html#gga5eacb8159cad288ce64d9d22afed6b0da144fa1b1b1991b27180321b8236a5e8a\">xsimrSHAPE_BLOB</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_miuserdata_defs.h:223</div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";