var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>xsi_toolcontext.h Source File</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'xsi__toolcontext_8h_source.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>xsi_toolcontext.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">xsi_toolcontext.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./si_cpp/xsi__toolcontext_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;<span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"preprocessor\">#if (_MSC_VER &gt; 1000) || defined(SGI_COMPILER)</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#pragma once</span></div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"preprocessor\">#ifndef __XSITOOLCONTEXT_H__</span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define __XSITOOLCONTEXT_H__</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__context_8h.html\">xsi_context.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__line_8h.html\">xsi_line.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__plane_8h.html\">xsi_plane.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__image_8h.html\">xsi_image.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__camera_8h.html\">xsi_camera.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__kinematicstate_8h.html\">xsi_kinematicstate.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00026\"></a><span class=\"lineno\">   26</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__pickbuffer_8h.html\">xsi_pickbuffer.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00027\"></a><span class=\"lineno\">   27</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00028\"></a><span class=\"lineno\">   28</span>&#160;<span class=\"keyword\">namespace </span>XSI {</div>\n\
<div class=\"line\"><a name=\"l00029\"></a><span class=\"lineno\">   29</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00030\"></a><span class=\"lineno\">   30</span>&#160;<span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00375\"></a><span class=\"lineno\">  375</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00376\"></a><span class=\"lineno\">  376</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00377\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">  377</a></span>&#160;<span class=\"keyword\">class </span>SICPPSDKDECL <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a> : <span class=\"keyword\">public</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">Context</a></div>\n\
<div class=\"line\"><a name=\"l00378\"></a><span class=\"lineno\">  378</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00379\"></a><span class=\"lineno\">  379</span>&#160;<span class=\"keyword\">public</span>:</div>\n\
<div class=\"line\"><a name=\"l00381\"></a><span class=\"lineno\">  381</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>();</div>\n\
<div class=\"line\"><a name=\"l00382\"></a><span class=\"lineno\">  382</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00384\"></a><span class=\"lineno\">  384</span>&#160;    ~<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>();</div>\n\
<div class=\"line\"><a name=\"l00385\"></a><span class=\"lineno\">  385</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00389\"></a><span class=\"lineno\">  389</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&amp; in_ref);</div>\n\
<div class=\"line\"><a name=\"l00390\"></a><span class=\"lineno\">  390</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00394\"></a><span class=\"lineno\">  394</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>&amp; in_obj);</div>\n\
<div class=\"line\"><a name=\"l00395\"></a><span class=\"lineno\">  395</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00400\"></a><span class=\"lineno\">  400</span>&#160;    <span class=\"keywordtype\">bool</span> IsA( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00401\"></a><span class=\"lineno\">  401</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00405\"></a><span class=\"lineno\">  405</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00406\"></a><span class=\"lineno\">  406</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00411\"></a><span class=\"lineno\">  411</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>&amp; operator=(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>&amp; in_obj);</div>\n\
<div class=\"line\"><a name=\"l00412\"></a><span class=\"lineno\">  412</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00418\"></a><span class=\"lineno\">  418</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a>&amp; operator=(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&amp; in_ref);</div>\n\
<div class=\"line\"><a name=\"l00419\"></a><span class=\"lineno\">  419</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00420\"></a><span class=\"lineno\">  420</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00424\"></a><span class=\"lineno\">  424</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l00431\"></a><span class=\"lineno\">  431</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetMousePosition( LONG &amp;x, LONG &amp;y ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00432\"></a><span class=\"lineno\">  432</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00435\"></a><span class=\"lineno\">  435</span>&#160;    <span class=\"keywordtype\">bool</span> IsLeftButtonDown() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00436\"></a><span class=\"lineno\">  436</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00439\"></a><span class=\"lineno\">  439</span>&#160;    <span class=\"keywordtype\">bool</span> IsMiddleButtonDown() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00440\"></a><span class=\"lineno\">  440</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00443\"></a><span class=\"lineno\">  443</span>&#160;    <span class=\"keywordtype\">bool</span> IsRightButtonDown() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00444\"></a><span class=\"lineno\">  444</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00447\"></a><span class=\"lineno\">  447</span>&#160;    <span class=\"keywordtype\">bool</span> IsDoubleClick() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00448\"></a><span class=\"lineno\">  448</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00451\"></a><span class=\"lineno\">  451</span>&#160;    <span class=\"keywordtype\">bool</span> IsShiftKeyDown() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00452\"></a><span class=\"lineno\">  452</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00455\"></a><span class=\"lineno\">  455</span>&#160;    <span class=\"keywordtype\">bool</span> IsControlKeyDown() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00456\"></a><span class=\"lineno\">  456</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00465\"></a><span class=\"lineno\">  465</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> RegisterShortcutKey( ULONG in_virtualKeycode, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_description, ULONG in_modifiers = 0, <span class=\"keywordtype\">bool</span> in_repeats = <span class=\"keyword\">false</span> );</div>\n\
<div class=\"line\"><a name=\"l00466\"></a><span class=\"lineno\">  466</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00473\"></a><span class=\"lineno\">  473</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> UnRegisterShortcutKey( ULONG in_virtualKeycode, ULONG in_modifiers = 0 );</div>\n\
<div class=\"line\"><a name=\"l00481\"></a><span class=\"lineno\">  481</span>&#160;    <span class=\"keywordtype\">bool</span> IsShortcutKeyDown( ULONG in_virtualKeycode, ULONG in_modifiers = 0 ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00482\"></a><span class=\"lineno\">  482</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00486\"></a><span class=\"lineno\">  486</span>&#160;    ULONG GetShortcutKey() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00487\"></a><span class=\"lineno\">  487</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00491\"></a><span class=\"lineno\">  491</span>&#160;    ULONG GetShortcutKeyModifiers() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00494\"></a><span class=\"lineno\">  494</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00498\"></a><span class=\"lineno\">  498</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l00505\"></a><span class=\"lineno\">  505</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetViewSize( LONG &amp;width, LONG &amp;height ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00506\"></a><span class=\"lineno\">  506</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00516\"></a><span class=\"lineno\">  516</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetViewport( LONG &amp;x, LONG &amp;y, LONG &amp;width, LONG &amp;height ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00517\"></a><span class=\"lineno\">  517</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00520\"></a><span class=\"lineno\">  520</span>&#160;    <span class=\"keywordtype\">bool</span> IsInteracting() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00521\"></a><span class=\"lineno\">  521</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00524\"></a><span class=\"lineno\">  524</span>&#160;    <span class=\"keywordtype\">bool</span> IsActiveView() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00525\"></a><span class=\"lineno\">  525</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00528\"></a><span class=\"lineno\">  528</span>&#160;    <span class=\"keywordtype\">bool</span> IsNavigating() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00529\"></a><span class=\"lineno\">  529</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00534\"></a><span class=\"lineno\">  534</span>&#160;    LONG GetViewIndex() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00535\"></a><span class=\"lineno\">  535</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00539\"></a><span class=\"lineno\">  539</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Camera.html\">Camera</a> GetCamera() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00540\"></a><span class=\"lineno\">  540</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00543\"></a><span class=\"lineno\">  543</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00547\"></a><span class=\"lineno\">  547</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l00553\"></a><span class=\"lineno\">  553</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetCursor( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#aca82bcedff0d7a8ac0717ee7b42d131e\">siToolCursor</a> in_cursorId );</div>\n\
<div class=\"line\"><a name=\"l00554\"></a><span class=\"lineno\">  554</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00560\"></a><span class=\"lineno\">  560</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetToolDescription( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_message );</div>\n\
<div class=\"line\"><a name=\"l00561\"></a><span class=\"lineno\">  561</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00567\"></a><span class=\"lineno\">  567</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EnableSnapping( <span class=\"keywordtype\">bool</span> in_enable );</div>\n\
<div class=\"line\"><a name=\"l00568\"></a><span class=\"lineno\">  568</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00574\"></a><span class=\"lineno\">  574</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetViewPlane( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CPlane.html\">MATH::CPlane</a> &amp;out_plane ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00575\"></a><span class=\"lineno\">  575</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00581\"></a><span class=\"lineno\">  581</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetGridPlane( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CPlane.html\">MATH::CPlane</a> &amp;out_plane ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00582\"></a><span class=\"lineno\">  582</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00588\"></a><span class=\"lineno\">  588</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetManipulationPlane( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CPlane.html\">MATH::CPlane</a> &amp;in_plane );</div>\n\
<div class=\"line\"><a name=\"l00589\"></a><span class=\"lineno\">  589</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00594\"></a><span class=\"lineno\">  594</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> ClearManipulationPlane();</div>\n\
<div class=\"line\"><a name=\"l00595\"></a><span class=\"lineno\">  595</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00598\"></a><span class=\"lineno\">  598</span>&#160;    <span class=\"keywordtype\">bool</span> WasAborted() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00599\"></a><span class=\"lineno\">  599</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00604\"></a><span class=\"lineno\">  604</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> ExitTool();</div>\n\
<div class=\"line\"><a name=\"l00605\"></a><span class=\"lineno\">  605</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00610\"></a><span class=\"lineno\">  610</span>&#160;    <span class=\"keywordtype\">bool</span> GetFlag( LONG in_flag ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00611\"></a><span class=\"lineno\">  611</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00619\"></a><span class=\"lineno\">  619</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetFlag( LONG in_flag, <span class=\"keywordtype\">bool</span> in_enable );</div>\n\
<div class=\"line\"><a name=\"l00625\"></a><span class=\"lineno\">  625</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00636\"></a><span class=\"lineno\">  636</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetWorldPosition( LONG x, LONG y, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_world ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00637\"></a><span class=\"lineno\">  637</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00648\"></a><span class=\"lineno\">  648</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetWorldRay( LONG x, LONG y, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CLine.html\">MATH::CLine</a> &amp;out_ray ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00649\"></a><span class=\"lineno\">  649</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00659\"></a><span class=\"lineno\">  659</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> WorldToView( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;in_world, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_view ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00660\"></a><span class=\"lineno\">  660</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00668\"></a><span class=\"lineno\">  668</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> ViewToWorld( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;in_view, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_world ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00669\"></a><span class=\"lineno\">  669</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00677\"></a><span class=\"lineno\">  677</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> WorldToCamera( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;in_world, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_camera ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00678\"></a><span class=\"lineno\">  678</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00686\"></a><span class=\"lineno\">  686</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> CameraToWorld( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;in_view, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_world ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00687\"></a><span class=\"lineno\">  687</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00693\"></a><span class=\"lineno\">  693</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetWorldToViewMatrix( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix4.html\">MATH::CMatrix4</a> &amp;out_worldToView ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00694\"></a><span class=\"lineno\">  694</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00700\"></a><span class=\"lineno\">  700</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetWorldToCameraMatrix( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix4.html\">MATH::CMatrix4</a> &amp;out_worldToCamera ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00706\"></a><span class=\"lineno\">  706</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00713\"></a><span class=\"lineno\">  713</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Redraw( <span class=\"keywordtype\">bool</span> in_allViews = <span class=\"keyword\">true</span> );</div>\n\
<div class=\"line\"><a name=\"l00714\"></a><span class=\"lineno\">  714</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00722\"></a><span class=\"lineno\">  722</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> DrawTextString( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_str, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afc\">siAlignment</a> in_hPos = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afca62e3d306866f8883704c2a5cada948b9\">siLeftAlign</a>, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afc\">siAlignment</a> in_vPos = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afca440c849a55aa91c5827da9ba83170b3d\">siBottomAlign</a> );</div>\n\
<div class=\"line\"><a name=\"l00723\"></a><span class=\"lineno\">  723</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00732\"></a><span class=\"lineno\">  732</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetTextSize( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_str, LONG &amp;out_width, LONG &amp;out_height, LONG &amp;out_descent ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00733\"></a><span class=\"lineno\">  733</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00744\"></a><span class=\"lineno\">  744</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EditTextString( <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;io_str, LONG x, LONG y, LONG width, LONG height );</div>\n\
<div class=\"line\"><a name=\"l00745\"></a><span class=\"lineno\">  745</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00750\"></a><span class=\"lineno\">  750</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> BeginViewDraw();</div>\n\
<div class=\"line\"><a name=\"l00751\"></a><span class=\"lineno\">  751</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00756\"></a><span class=\"lineno\">  756</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EndViewDraw();</div>\n\
<div class=\"line\"><a name=\"l00757\"></a><span class=\"lineno\">  757</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00760\"></a><span class=\"lineno\">  760</span>&#160;    <span class=\"keywordtype\">bool</span> IsViewDraw() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00761\"></a><span class=\"lineno\">  761</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00772\"></a><span class=\"lineno\">  772</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> BeginPickDraw( LONG x, LONG y, LONG width, LONG height);</div>\n\
<div class=\"line\"><a name=\"l00773\"></a><span class=\"lineno\">  773</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00778\"></a><span class=\"lineno\">  778</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EndPickDraw();</div>\n\
<div class=\"line\"><a name=\"l00779\"></a><span class=\"lineno\">  779</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00782\"></a><span class=\"lineno\">  782</span>&#160;    <span class=\"keywordtype\">bool</span> IsPickDraw() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00785\"></a><span class=\"lineno\">  785</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00789\"></a><span class=\"lineno\">  789</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l00797\"></a><span class=\"lineno\">  797</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> BeginParameterUpdate(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> &amp;in_param, <span class=\"keywordtype\">double</span> in_time = DBL_MAX);</div>\n\
<div class=\"line\"><a name=\"l00798\"></a><span class=\"lineno\">  798</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00807\"></a><span class=\"lineno\">  807</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> UpdateParameter(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> &amp;in_param, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> &amp;in_value);</div>\n\
<div class=\"line\"><a name=\"l00808\"></a><span class=\"lineno\">  808</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00816\"></a><span class=\"lineno\">  816</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EndParameterUpdate(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">Parameter</a> &amp;in_param);</div>\n\
<div class=\"line\"><a name=\"l00817\"></a><span class=\"lineno\">  817</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00826\"></a><span class=\"lineno\">  826</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> BeginKinematicStateUpdate(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1KinematicState.html\">KinematicState</a> &amp;in_kine, <span class=\"keywordtype\">double</span> in_time = DBL_MAX);</div>\n\
<div class=\"line\"><a name=\"l00827\"></a><span class=\"lineno\">  827</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00836\"></a><span class=\"lineno\">  836</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> UpdateKinematicState(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1KinematicState.html\">KinematicState</a> &amp;in_kine, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CTransformation.html\">MATH::CTransformation</a> &amp;in_value);</div>\n\
<div class=\"line\"><a name=\"l00837\"></a><span class=\"lineno\">  837</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00845\"></a><span class=\"lineno\">  845</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EndKinematicStateUpdate(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1KinematicState.html\">KinematicState</a> &amp;in_kine);</div>\n\
<div class=\"line\"><a name=\"l00846\"></a><span class=\"lineno\">  846</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00855\"></a><span class=\"lineno\">  855</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> BeginTransformUpdate(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_objects, <span class=\"keywordtype\">double</span> in_time = DBL_MAX);</div>\n\
<div class=\"line\"><a name=\"l00856\"></a><span class=\"lineno\">  856</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00872\"></a><span class=\"lineno\">  872</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> UpdateTransform(</div>\n\
<div class=\"line\"><a name=\"l00873\"></a><span class=\"lineno\">  873</span>&#160;        <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;               in_objects,</div>\n\
<div class=\"line\"><a name=\"l00874\"></a><span class=\"lineno\">  874</span>&#160;        <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CTransformation.html\">MATH::CTransformation</a> &amp;   in_value,</div>\n\
<div class=\"line\"><a name=\"l00875\"></a><span class=\"lineno\">  875</span>&#160;        <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a5ae5bf5c4b74a02e7e6a5c555bd5e35a\">siTransformFilter</a>               in_srt,</div>\n\
<div class=\"line\"><a name=\"l00876\"></a><span class=\"lineno\">  876</span>&#160;        <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a539acb83e0c918f371d33513e6ae5504\">siRefMode</a>                       in_refMode      = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a539acb83e0c918f371d33513e6ae5504aed3c561d9a0770df674bf90a839f5763\">siLocal</a>,</div>\n\
<div class=\"line\"><a name=\"l00877\"></a><span class=\"lineno\">  877</span>&#160;        <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a07b67fbcf6988d59376f7b32bc131937\">siDeltaMode</a>                     in_delta        = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a07b67fbcf6988d59376f7b32bc131937ad0c3996d04cea6ffc4a3b484f8f742f1\">siRelative</a>,</div>\n\
<div class=\"line\"><a name=\"l00878\"></a><span class=\"lineno\">  878</span>&#160;        <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ac0e6c9cd2704f81d19e70ee6d580e8e0\">siAxesFilter</a>                    in_axesFilter   = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ac0e6c9cd2704f81d19e70ee6d580e8e0a1449189556b3f1f4bc6e3fa5cef2e32e\">siXYZ</a>,</div>\n\
<div class=\"line\"><a name=\"l00879\"></a><span class=\"lineno\">  879</span>&#160;        <span class=\"keywordtype\">bool</span>                            in_usePivot     = <span class=\"keyword\">false</span>,</div>\n\
<div class=\"line\"><a name=\"l00880\"></a><span class=\"lineno\">  880</span>&#160;        <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;          in_pivot        = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a>(),</div>\n\
<div class=\"line\"><a name=\"l00881\"></a><span class=\"lineno\">  881</span>&#160;        <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CTransformation.html\">MATH::CTransformation</a> &amp;   in_reference    = <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CTransformation.html\">MATH::CTransformation</a>()</div>\n\
<div class=\"line\"><a name=\"l00882\"></a><span class=\"lineno\">  882</span>&#160;    );</div>\n\
<div class=\"line\"><a name=\"l00883\"></a><span class=\"lineno\">  883</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00891\"></a><span class=\"lineno\">  891</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EndTransformUpdate(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_objects);</div>\n\
<div class=\"line\"><a name=\"l00894\"></a><span class=\"lineno\">  894</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00898\"></a><span class=\"lineno\">  898</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l00904\"></a><span class=\"lineno\">  904</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#abe6319c9e0d46864ce1bec79ee6cb487\">siSnapType</a> GetSnapType() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00905\"></a><span class=\"lineno\">  905</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00911\"></a><span class=\"lineno\">  911</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> GetSnapObject() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00912\"></a><span class=\"lineno\">  912</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00918\"></a><span class=\"lineno\">  918</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a> GetSnapComponent() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00919\"></a><span class=\"lineno\">  919</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00948\"></a><span class=\"lineno\">  948</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Snap( LONG x, LONG y, LONG size, ULONG in_snaptype, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">CStringArray</a>&amp; in_families, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_objects, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">MATH::CVector3</a> &amp;out_world ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00951\"></a><span class=\"lineno\">  951</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00955\"></a><span class=\"lineno\">  955</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l01001\"></a><span class=\"lineno\"> 1001</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> Pick( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> &amp;in_points, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a2d7ba0a922dee8f004b70bf58b8b5135\">siPickMode</a> in_pickMode, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#afd23733729e9bd5e5fe10d2127235d54\">siPickType</a> in_pickType, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_filter, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_objects, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;out_picked ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l01002\"></a><span class=\"lineno\"> 1002</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l01034\"></a><span class=\"lineno\"> 1034</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1PickBuffer.html\">PickBuffer</a> GetPickBuffer( LONG x, LONG y, LONG width, LONG height, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_filter, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">CRefArray</a> &amp;in_objects, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a8ead823f5b2f370bbaf1f4636f4c3d06\">siViewMode</a> in_viewMode = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a8ead823f5b2f370bbaf1f4636f4c3d06a3b3e8914d240165d2ea4372b96e61d15\">siShaded</a> ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l01037\"></a><span class=\"lineno\"> 1037</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l01041\"></a><span class=\"lineno\"> 1041</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l01052\"></a><span class=\"lineno\"> 1052</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> ShowContextMenu( LONG x, LONG y, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afc\">siAlignment</a> in_hPos = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afca62e3d306866f8883704c2a5cada948b9\">siLeftAlign</a>, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afc\">siAlignment</a> in_vPos = <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afcad7c40ba247a07da45559d7385c621d37\">siTopAlign</a> );</div>\n\
<div class=\"line\"><a name=\"l01055\"></a><span class=\"lineno\"> 1055</span>&#160;    <span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l01059\"></a><span class=\"lineno\"> 1059</span>&#160;<span class=\"comment\"></span></div>\n\
<div class=\"line\"><a name=\"l01065\"></a><span class=\"lineno\"> 1065</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1Image.html\">Image</a> LoadImageFromFile( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_filename, <span class=\"keywordtype\">bool</span> in_relativePath = <span class=\"keyword\">true</span> );</div>\n\
<div class=\"line\"><a name=\"l01068\"></a><span class=\"lineno\"> 1068</span>&#160;<span class=\"keyword\">private</span>:</div>\n\
<div class=\"line\"><a name=\"l01069\"></a><span class=\"lineno\"> 1069</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a> * operator&amp;() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l01070\"></a><span class=\"lineno\"> 1070</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">ToolContext</a> * operator&amp;();</div>\n\
<div class=\"line\"><a name=\"l01071\"></a><span class=\"lineno\"> 1071</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l01072\"></a><span class=\"lineno\"> 1072</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l01073\"></a><span class=\"lineno\"> 1073</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l01074\"></a><span class=\"lineno\"> 1074</span>&#160;<span class=\"preprocessor\">#endif // __XSITOOLCONTEXT_H__</span></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_abe6319c9e0d46864ce1bec79ee6cb487\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#abe6319c9e0d46864ce1bec79ee6cb487\">XSI::siSnapType</a></div><div class=\"ttdeci\">siSnapType</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3228</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_ac0e6c9cd2704f81d19e70ee6d580e8e0a1449189556b3f1f4bc6e3fa5cef2e32e\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#ac0e6c9cd2704f81d19e70ee6d580e8e0a1449189556b3f1f4bc6e3fa5cef2e32e\">XSI::siXYZ</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:163</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Parameter_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Parameter.html\">XSI::Parameter</a></div><div class=\"ttdoc\">Represents a parameter value within the ProjectItem, for example, the angle parameter of the twist op...</div><div class=\"ttdef\"><b>Definition:</b> xsi_parameter.h:430</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CRef_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">XSI::CRef</a></div><div class=\"ttdoc\">This class is used to reference Softimage objects. Each instance of an CRef maintains a link with onl...</div><div class=\"ttdef\"><b>Definition:</b> xsi_ref.h:142</div></div>\n\
<div class=\"ttc\" id=\"xsi__context_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__context_8h.html\">xsi_context.h</a></div><div class=\"ttdoc\">Context class declaration. </div></div>\n\
<div class=\"ttc\" id=\"xsi__pickbuffer_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__pickbuffer_8h.html\">xsi_pickbuffer.h</a></div><div class=\"ttdoc\">PickBuffer class declaration. </div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a8ead823f5b2f370bbaf1f4636f4c3d06\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a8ead823f5b2f370bbaf1f4636f4c3d06\">XSI::siViewMode</a></div><div class=\"ttdeci\">siViewMode</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:1986</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1PickBuffer_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1PickBuffer.html\">XSI::PickBuffer</a></div><div class=\"ttdoc\">This class provides access to a picking buffer returned from ToolContent::GetPickBuffer. </div><div class=\"ttdef\"><b>Definition:</b> xsi_pickbuffer.h:31</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CValue_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">XSI::CValue</a></div><div class=\"ttdoc\">The CValue object provides the convenience of a loosely typed variable inside a strictly typed langua...</div><div class=\"ttdef\"><b>Definition:</b> xsi_value.h:159</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a5ae5bf5c4b74a02e7e6a5c555bd5e35a\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a5ae5bf5c4b74a02e7e6a5c555bd5e35a\">XSI::siTransformFilter</a></div><div class=\"ttdeci\">siTransformFilter</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:180</div></div>\n\
<div class=\"ttc\" id=\"xsi__plane_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__plane_8h.html\">xsi_plane.h</a></div><div class=\"ttdoc\">CPlane class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1MATH_1_1CMatrix4_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CMatrix4.html\">XSI::MATH::CMatrix4</a></div><div class=\"ttdoc\">This class represents a double precision floating point 4 by 4 matrix. </div><div class=\"ttdef\"><b>Definition:</b> xsi_matrix4.h:59</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_ac0e6c9cd2704f81d19e70ee6d580e8e0\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#ac0e6c9cd2704f81d19e70ee6d580e8e0\">XSI::siAxesFilter</a></div><div class=\"ttdeci\">siAxesFilter</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:154</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_afd23733729e9bd5e5fe10d2127235d54\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#afd23733729e9bd5e5fe10d2127235d54\">XSI::siPickType</a></div><div class=\"ttdeci\">siPickType</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3261</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a57d38d3e6a35376cc0c043ea4b5d6afca62e3d306866f8883704c2a5cada948b9\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afca62e3d306866f8883704c2a5cada948b9\">XSI::siLeftAlign</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3220</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Camera_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Camera.html\">XSI::Camera</a></div><div class=\"ttdoc\">The Camera object represents a Softimage camera in a scene. </div><div class=\"ttdef\"><b>Definition:</b> xsi_camera.h:57</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a8ead823f5b2f370bbaf1f4636f4c3d06a3b3e8914d240165d2ea4372b96e61d15\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a8ead823f5b2f370bbaf1f4636f4c3d06a3b3e8914d240165d2ea4372b96e61d15\">XSI::siShaded</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:1995</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CRefArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CRefArray.html\">XSI::CRefArray</a></div><div class=\"ttdoc\">The CRefArray class holds generic CRef objects and acts as a base class for other specialized CRef ar...</div><div class=\"ttdef\"><b>Definition:</b> xsi_ref.h:333</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a2d7ba0a922dee8f004b70bf58b8b5135\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a2d7ba0a922dee8f004b70bf58b8b5135\">XSI::siPickMode</a></div><div class=\"ttdeci\">siPickMode</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3251</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_aca82bcedff0d7a8ac0717ee7b42d131e\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#aca82bcedff0d7a8ac0717ee7b42d131e\">XSI::siToolCursor</a></div><div class=\"ttdeci\">siToolCursor</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3197</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_ad483c77b3d997caca1f369db99c1e68b\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">XSI::siClassID</a></div><div class=\"ttdeci\">siClassID</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:1537</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1MATH_1_1CPlane_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CPlane.html\">XSI::MATH::CPlane</a></div><div class=\"ttdoc\">A parametric 3D plane. </div><div class=\"ttdef\"><b>Definition:</b> xsi_plane.h:41</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CString_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">XSI::CString</a></div><div class=\"ttdoc\">Character strings in the Softimage SDK are represented with the CString class. CString consist of a v...</div><div class=\"ttdef\"><b>Definition:</b> xsi_string.h:76</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a57d38d3e6a35376cc0c043ea4b5d6afcad7c40ba247a07da45559d7385c621d37\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afcad7c40ba247a07da45559d7385c621d37\">XSI::siTopAlign</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3223</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1MATH_1_1CLine_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CLine.html\">XSI::MATH::CLine</a></div><div class=\"ttdoc\">A parametric 3D line. </div><div class=\"ttdef\"><b>Definition:</b> xsi_line.h:40</div></div>\n\
<div class=\"ttc\" id=\"xsi__camera_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__camera_8h.html\">xsi_camera.h</a></div><div class=\"ttdoc\">Camera class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1MATH_1_1CTransformation_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CTransformation.html\">XSI::MATH::CTransformation</a></div><div class=\"ttdoc\">This object represents a transformation which is the result of the combination of a Scaling...</div><div class=\"ttdef\"><b>Definition:</b> xsi_transformation.h:85</div></div>\n\
<div class=\"ttc\" id=\"xsi__image_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__image_8h.html\">xsi_image.h</a></div><div class=\"ttdoc\">Image class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Context_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Context.html\">XSI::Context</a></div><div class=\"ttdoc\">This is a general, flexible Context object that is used for callbacks. Instances of this object are u...</div><div class=\"ttdef\"><b>Definition:</b> xsi_context.h:46</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a539acb83e0c918f371d33513e6ae5504aed3c561d9a0770df674bf90a839f5763\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a539acb83e0c918f371d33513e6ae5504aed3c561d9a0770df674bf90a839f5763\">XSI::siLocal</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:112</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CStatus_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">XSI::CStatus</a></div><div class=\"ttdoc\">Encapsulates status data types for error handling purpose. The class also exposes methods to query an...</div><div class=\"ttdef\"><b>Definition:</b> xsi_status.h:36</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CStringArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CStringArray.html\">XSI::CStringArray</a></div><div class=\"ttdoc\">The CStringArray is an uni-dimensional array of CString objects. </div><div class=\"ttdef\"><b>Definition:</b> xsi_string.h:675</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a57d38d3e6a35376cc0c043ea4b5d6afc\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afc\">XSI::siAlignment</a></div><div class=\"ttdeci\">siAlignment</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3217</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a07b67fbcf6988d59376f7b32bc131937ad0c3996d04cea6ffc4a3b484f8f742f1\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a07b67fbcf6988d59376f7b32bc131937ad0c3996d04cea6ffc4a3b484f8f742f1\">XSI::siRelative</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:91</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a57d38d3e6a35376cc0c043ea4b5d6afca440c849a55aa91c5827da9ba83170b3d\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a57d38d3e6a35376cc0c043ea4b5d6afca440c849a55aa91c5827da9ba83170b3d\">XSI::siBottomAlign</a></div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3224</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1MATH_1_1CVector3_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1MATH_1_1CVector3.html\">XSI::MATH::CVector3</a></div><div class=\"ttdoc\">A 3-element vector that is represented by double precision floating point x,y,z coordinates. </div><div class=\"ttdef\"><b>Definition:</b> xsi_vector3.h:100</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1ToolContext_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1ToolContext.html\">XSI::ToolContext</a></div><div class=\"ttdoc\">ToolContext is used for accessing/handling tool data. Instances of this object can pass information t...</div><div class=\"ttdef\"><b>Definition:</b> xsi_toolcontext.h:377</div></div>\n\
<div class=\"ttc\" id=\"xsi__line_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__line_8h.html\">xsi_line.h</a></div><div class=\"ttdoc\">CLine class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1KinematicState_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1KinematicState.html\">XSI::KinematicState</a></div><div class=\"ttdoc\">The KinematicState represents the current pose of an X3DObject object whereas the base pose of an obj...</div><div class=\"ttdef\"><b>Definition:</b> xsi_kinematicstate.h:46</div></div>\n\
<div class=\"ttc\" id=\"xsi__kinematicstate_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__kinematicstate_8h.html\">xsi_kinematicstate.h</a></div><div class=\"ttdoc\">KinematicState class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1Image_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1Image.html\">XSI::Image</a></div><div class=\"ttdoc\">This class provides read-access to the representation of an image in memory. </div><div class=\"ttdef\"><b>Definition:</b> xsi_image.h:86</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a539acb83e0c918f371d33513e6ae5504\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a539acb83e0c918f371d33513e6ae5504\">XSI::siRefMode</a></div><div class=\"ttdeci\">siRefMode</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:108</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CLongArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">XSI::CLongArray</a></div><div class=\"ttdoc\">The CLongArray is an uni-dimensional array of LONG values. </div><div class=\"ttdef\"><b>Definition:</b> xsi_longarray.h:45</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a07b67fbcf6988d59376f7b32bc131937\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a07b67fbcf6988d59376f7b32bc131937\">XSI::siDeltaMode</a></div><div class=\"ttdeci\">siDeltaMode</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:87</div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";