var topic = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\
<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/lib/jquery-1.9.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>xsi_griddata.h Source File</title>\n\
   \n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"si_cpp/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/yepnope.1.5.4-min.js\"); });</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var weAreIn21 = $(\"div#main.view-active\").length;\n\
var prefix = \"\";\n\
if (weAreIn21)\n\
{ prefix = \"si_cpp/\"; }\n\
yepnope([{\n\
load:[prefix + \"jquery.js\", prefix + \"navtree.js\", prefix + \"resize.js\", prefix + \"dynsections.js\"],\n\
complete: function() {\n\
  dQuery = jQuery.noConflict(\'true\');\n\
  dQuery(window).load(resizeHeight);\n\
  dQuery(document).ready( function () {\n\
    setTimeout( function () {\n\
      initResizable();\n\
      initNavTree(\'xsi__griddata_8h_source.html\', prefix);\n\
      dQuery(window).trigger(\"load\");\n\
      }, 100);\n\
    }\n\
  );\n\
}\n\
}]\n\
)\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?siteData=y5CYlxTRD0znCzRLDwX0Wy7-g1EdC1XA4dSC-Y1LtaeScyli8_Ps5jPKqTr4xKxMI0OOUfkDplvX3uxN0JnPclebSYW8_J1HBzf4VLQEzQ8M4PsYXF_cMyp1Oumaetky&category=5297189e-446b-459e-ae1d-9d0360400781_tech&ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'position:absolute;right:20px;top:5px;z-index:100;color:white;background-color:#555555;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>xsi_griddata.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.6 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./si_cpp/files.html\"><span>Files</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./si_cpp/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./si_cpp/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">xsi_griddata.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./si_cpp/xsi__griddata_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;<span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"preprocessor\">#if (_MSC_VER &gt; 1000) || defined(SGI_COMPILER)</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#pragma once</span></div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"preprocessor\">#ifndef __XSIGRIDDATA_H__</span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"preprocessor\"></span><span class=\"preprocessor\">#define __XSIGRIDDATA_H__</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"preprocessor\"></span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__base_8h.html\">xsi_base.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__ppgitem_8h.html\">xsi_ppgitem.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__value_8h.html\">xsi_value.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./si_cpp/xsi__bitarray_8h.html\">xsi_bitarray.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;<span class=\"keyword\">namespace </span>XSI {</div>\n\
<div class=\"line\"><a name=\"l00026\"></a><span class=\"lineno\">   26</span>&#160;<span class=\"keyword\">struct </span>CColor ;</div>\n\
<div class=\"line\"><a name=\"l00027\"></a><span class=\"lineno\">   27</span>&#160;<span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00180\"></a><span class=\"lineno\">  180</span>&#160;<span class=\"comment\"></span><span class=\"comment\">//*****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00181\"></a><span class=\"lineno\">  181</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00182\"></a><span class=\"lineno\">  182</span>&#160;<span class=\"keyword\">class </span>GridWidget ;</div>\n\
<div class=\"line\"><a name=\"l00183\"></a><span class=\"lineno\">  183</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00184\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">  184</a></span>&#160;<span class=\"keyword\">class </span>SICPPSDKDECL <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a> : <span class=\"keyword\">public</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">CBase</a></div>\n\
<div class=\"line\"><a name=\"l00185\"></a><span class=\"lineno\">  185</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00186\"></a><span class=\"lineno\">  186</span>&#160;<span class=\"keyword\">public</span>:</div>\n\
<div class=\"line\"><a name=\"l00188\"></a><span class=\"lineno\">  188</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>();</div>\n\
<div class=\"line\"><a name=\"l00189\"></a><span class=\"lineno\">  189</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00191\"></a><span class=\"lineno\">  191</span>&#160;    ~<a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>();</div>\n\
<div class=\"line\"><a name=\"l00192\"></a><span class=\"lineno\">  192</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00196\"></a><span class=\"lineno\">  196</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&amp; in_ref);</div>\n\
<div class=\"line\"><a name=\"l00197\"></a><span class=\"lineno\">  197</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00201\"></a><span class=\"lineno\">  201</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>&amp; in_obj);</div>\n\
<div class=\"line\"><a name=\"l00202\"></a><span class=\"lineno\">  202</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00207\"></a><span class=\"lineno\">  207</span>&#160;    <span class=\"keywordtype\">bool</span> IsA( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> in_ClassID) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00208\"></a><span class=\"lineno\">  208</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00212\"></a><span class=\"lineno\">  212</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">siClassID</a> GetClassID() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00213\"></a><span class=\"lineno\">  213</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00218\"></a><span class=\"lineno\">  218</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>&amp; operator=(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>&amp; in_obj);</div>\n\
<div class=\"line\"><a name=\"l00219\"></a><span class=\"lineno\">  219</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00225\"></a><span class=\"lineno\">  225</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a>&amp; operator=(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">CRef</a>&amp; in_ref);</div>\n\
<div class=\"line\"><a name=\"l00226\"></a><span class=\"lineno\">  226</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00231\"></a><span class=\"lineno\">  231</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> GetData() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00232\"></a><span class=\"lineno\">  232</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00239\"></a><span class=\"lineno\">  239</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutData( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a>&amp; in_items ) ;</div>\n\
<div class=\"line\"><a name=\"l00240\"></a><span class=\"lineno\">  240</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00246\"></a><span class=\"lineno\">  246</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutColumnCount( LONG in_val );</div>\n\
<div class=\"line\"><a name=\"l00247\"></a><span class=\"lineno\">  247</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00251\"></a><span class=\"lineno\">  251</span>&#160;    LONG GetColumnCount() <span class=\"keyword\">const</span> ;</div>\n\
<div class=\"line\"><a name=\"l00252\"></a><span class=\"lineno\">  252</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00258\"></a><span class=\"lineno\">  258</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutRowCount( LONG in_val ) ;</div>\n\
<div class=\"line\"><a name=\"l00259\"></a><span class=\"lineno\">  259</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00263\"></a><span class=\"lineno\">  263</span>&#160;    LONG GetRowCount() <span class=\"keyword\">const</span> ;</div>\n\
<div class=\"line\"><a name=\"l00264\"></a><span class=\"lineno\">  264</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00272\"></a><span class=\"lineno\">  272</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutCell(LONG in_Column, LONG in_Row, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>&amp; in_CellValue);</div>\n\
<div class=\"line\"><a name=\"l00273\"></a><span class=\"lineno\">  273</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00282\"></a><span class=\"lineno\">  282</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutCell(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_ColumnLabel, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_RowLabel, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a>&amp; in_CellValue);</div>\n\
<div class=\"line\"><a name=\"l00283\"></a><span class=\"lineno\">  283</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00290\"></a><span class=\"lineno\">  290</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> GetCell(LONG in_Column, LONG in_Row) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00291\"></a><span class=\"lineno\">  291</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00301\"></a><span class=\"lineno\">  301</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">CValue</a> GetCell(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_ColumnLabel, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_RowLabel) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00307\"></a><span class=\"lineno\">  307</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutColumnValues( LONG in_Column, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> &amp; in_ColumnItems );</div>\n\
<div class=\"line\"><a name=\"l00313\"></a><span class=\"lineno\">  313</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutColumnValues( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_ColumnLabel, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> &amp; in_ColumnItems );</div>\n\
<div class=\"line\"><a name=\"l00314\"></a><span class=\"lineno\">  314</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00319\"></a><span class=\"lineno\">  319</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> GetColumnValues(LONG in_Column ) <span class=\"keyword\">const</span> ;</div>\n\
<div class=\"line\"><a name=\"l00320\"></a><span class=\"lineno\">  320</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00325\"></a><span class=\"lineno\">  325</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> GetColumnValues(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_ColumnLabel ) <span class=\"keyword\">const</span> ;</div>\n\
<div class=\"line\"><a name=\"l00326\"></a><span class=\"lineno\">  326</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00332\"></a><span class=\"lineno\">  332</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutRowValues( LONG in_Row, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> &amp; in_RowItems );</div>\n\
<div class=\"line\"><a name=\"l00333\"></a><span class=\"lineno\">  333</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00339\"></a><span class=\"lineno\">  339</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutRowValues( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_RowLabel, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> &amp; in_RowItems );</div>\n\
<div class=\"line\"><a name=\"l00340\"></a><span class=\"lineno\">  340</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00345\"></a><span class=\"lineno\">  345</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> GetRowValues(LONG in_Row ) <span class=\"keyword\">const</span> ;</div>\n\
<div class=\"line\"><a name=\"l00346\"></a><span class=\"lineno\">  346</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00351\"></a><span class=\"lineno\">  351</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> GetRowValues(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_RowLabel ) <span class=\"keyword\">const</span> ;</div>\n\
<div class=\"line\"><a name=\"l00352\"></a><span class=\"lineno\">  352</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00361\"></a><span class=\"lineno\">  361</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutRowLabel(LONG in_RowIndex, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_RowLabel );</div>\n\
<div class=\"line\"><a name=\"l00362\"></a><span class=\"lineno\">  362</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00368\"></a><span class=\"lineno\">  368</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> GetRowLabel(LONG in_RowIndex) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00369\"></a><span class=\"lineno\">  369</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00378\"></a><span class=\"lineno\">  378</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutColumnLabel(LONG in_ColumnIndex, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; in_ColumnLabel);</div>\n\
<div class=\"line\"><a name=\"l00379\"></a><span class=\"lineno\">  379</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00385\"></a><span class=\"lineno\">  385</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> GetColumnLabel(LONG in_ColumnIndex) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00386\"></a><span class=\"lineno\">  386</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00393\"></a><span class=\"lineno\">  393</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> BeginEdit();</div>\n\
<div class=\"line\"><a name=\"l00394\"></a><span class=\"lineno\">  394</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00400\"></a><span class=\"lineno\">  400</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> EndEdit();</div>\n\
<div class=\"line\"><a name=\"l00401\"></a><span class=\"lineno\">  401</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00409\"></a><span class=\"lineno\">  409</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutColumnType(LONG in_ColumnIndex, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#afadf9141376c7d94593391531aebaabc\">siGridWidgetColumnType</a> in_Type );</div>\n\
<div class=\"line\"><a name=\"l00410\"></a><span class=\"lineno\">  410</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00416\"></a><span class=\"lineno\">  416</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#afadf9141376c7d94593391531aebaabc\">siGridWidgetColumnType</a> GetColumnType( LONG in_ColumnIndex ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00417\"></a><span class=\"lineno\">  417</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00426\"></a><span class=\"lineno\">  426</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutColumnComboItems(LONG in_ColumnIndex, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a>&amp; in_Items);</div>\n\
<div class=\"line\"><a name=\"l00427\"></a><span class=\"lineno\">  427</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00433\"></a><span class=\"lineno\">  433</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">CValueArray</a> GetColumnComboItems(LONG in_ColumnIndex);</div>\n\
<div class=\"line\"><a name=\"l00434\"></a><span class=\"lineno\">  434</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00440\"></a><span class=\"lineno\">  440</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridWidget.html\">GridWidget</a> GetGridWidget() ;</div>\n\
<div class=\"line\"><a name=\"l00441\"></a><span class=\"lineno\">  441</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00449\"></a><span class=\"lineno\">  449</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetRowBackgroundColor( LONG in_Row, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CColor.html\">CColor</a> &amp;in_Color );</div>\n\
<div class=\"line\"><a name=\"l00450\"></a><span class=\"lineno\">  450</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00456\"></a><span class=\"lineno\">  456</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CColor.html\">CColor</a> GetRowBackgroundColor(LONG in_Row );</div>\n\
<div class=\"line\"><a name=\"l00457\"></a><span class=\"lineno\">  457</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00466\"></a><span class=\"lineno\">  466</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetIntColumnDef( LONG in_lColumnIndex, LONG in_lMin = INT_MIN, LONG in_lMax = INT_MAX, LONG in_lInc = 1 );</div>\n\
<div class=\"line\"><a name=\"l00467\"></a><span class=\"lineno\">  467</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00476\"></a><span class=\"lineno\">  476</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetIntColumnDef( LONG in_lColumnIndex, LONG &amp;out_lMin, LONG &amp;out_lMax, LONG &amp;out_lInc ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00477\"></a><span class=\"lineno\">  477</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00487\"></a><span class=\"lineno\">  487</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetFloatColumnDef( LONG in_lColumnIndex, <span class=\"keywordtype\">double</span> in_dMin = DBL_MIN, <span class=\"keywordtype\">double</span> in_dMax = DBL_MAX, <span class=\"keywordtype\">double</span> in_dInc = 1.0, <span class=\"keywordtype\">short</span> in_sDecimal = 2 ) ;</div>\n\
<div class=\"line\"><a name=\"l00488\"></a><span class=\"lineno\">  488</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00498\"></a><span class=\"lineno\">  498</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetFloatColumnDef( LONG in_lColumnIndex, <span class=\"keywordtype\">double</span> &amp;out_dMin, <span class=\"keywordtype\">double</span> &amp;out_dMax, <span class=\"keywordtype\">double</span> &amp;out_dInc, <span class=\"keywordtype\">short</span> &amp;out_sDecimal ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00499\"></a><span class=\"lineno\">  499</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00510\"></a><span class=\"lineno\">  510</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetVectorColumnDef( LONG in_lColumnIndex, <span class=\"keywordtype\">short</span> in_sVectorSize, <span class=\"keywordtype\">double</span> in_dMin = DBL_MIN, <span class=\"keywordtype\">double</span> in_dMax = DBL_MAX, <span class=\"keywordtype\">double</span> in_dInc = 1.0, <span class=\"keywordtype\">short</span> in_sDecimal = 2 ) ;</div>\n\
<div class=\"line\"><a name=\"l00511\"></a><span class=\"lineno\">  511</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00522\"></a><span class=\"lineno\">  522</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetVectorColumnDef( LONG in_lColumnIndex, <span class=\"keywordtype\">short</span> &amp;out_sVectorSize, <span class=\"keywordtype\">double</span> &amp;out_dMin, <span class=\"keywordtype\">double</span> &amp;out_dMax, <span class=\"keywordtype\">double</span> &amp;out_dInc, <span class=\"keywordtype\">short</span> &amp;out_sDecimal ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00523\"></a><span class=\"lineno\">  523</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00532\"></a><span class=\"lineno\">  532</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetFileColumnDef( LONG in_lColumnIndex, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_csBrowseType = <span class=\"stringliteral\">&quot;File&quot;</span>, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_csStartupPath = <span class=\"stringliteral\">&quot;/&quot;</span>, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a> &amp;in_csFilter = <span class=\"stringliteral\">&quot;.*&quot;</span> ) ;</div>\n\
<div class=\"line\"><a name=\"l00533\"></a><span class=\"lineno\">  533</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00542\"></a><span class=\"lineno\">  542</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetFileColumnDef( LONG in_lColumnIndex, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; out_csBrowseType, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; out_csStartupPath, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">CString</a>&amp; out_csFilter ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00543\"></a><span class=\"lineno\">  543</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00550\"></a><span class=\"lineno\">  550</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetShaderBallColumnDef( LONG in_lColumnIndex, LONG in_lThumbnailSize = 28 ) ;</div>\n\
<div class=\"line\"><a name=\"l00551\"></a><span class=\"lineno\">  551</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00558\"></a><span class=\"lineno\">  558</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetShaderBallColumnDef( LONG in_lColumnIndex, LONG &amp;out_lThumbnailSize ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00559\"></a><span class=\"lineno\">  559</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00565\"></a><span class=\"lineno\">  565</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetImageClipColumnDef( LONG in_lColumnIndex, LONG in_lThumbnailSize = 28 );</div>\n\
<div class=\"line\"><a name=\"l00566\"></a><span class=\"lineno\">  566</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00572\"></a><span class=\"lineno\">  572</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetImageClipColumnDef( LONG in_lColumnIndex, LONG &amp;out_lThumbnailSize ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00573\"></a><span class=\"lineno\">  573</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00579\"></a><span class=\"lineno\">  579</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> InsertRow( LONG in_lRowIndex ) ;</div>\n\
<div class=\"line\"><a name=\"l00580\"></a><span class=\"lineno\">  580</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00586\"></a><span class=\"lineno\">  586</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> RemoveRow( LONG in_lRowIndex ) ;</div>\n\
<div class=\"line\"><a name=\"l00587\"></a><span class=\"lineno\">  587</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00593\"></a><span class=\"lineno\">  593</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> InsertColumn( LONG in_lColumnIndex ) ;</div>\n\
<div class=\"line\"><a name=\"l00594\"></a><span class=\"lineno\">  594</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00600\"></a><span class=\"lineno\">  600</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> RemoveColumn( LONG in_lColumnIndex ) ;</div>\n\
<div class=\"line\"><a name=\"l00601\"></a><span class=\"lineno\">  601</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00609\"></a><span class=\"lineno\">  609</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetCellBackgroundColor( LONG in_lCol, LONG in_lRow, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CColor.html\">CColor</a> &amp;in_Color ) ;</div>\n\
<div class=\"line\"><a name=\"l00610\"></a><span class=\"lineno\">  610</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00617\"></a><span class=\"lineno\">  617</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/structXSI_1_1CColor.html\">CColor</a> GetCellBackgroundColor( LONG in_lCol, LONG in_lRow ) <span class=\"keyword\">const</span> ;</div>\n\
<div class=\"line\"><a name=\"l00618\"></a><span class=\"lineno\">  618</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00625\"></a><span class=\"lineno\">  625</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetColumnsVisibility( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> &amp;in_alCols, <span class=\"keywordtype\">bool</span> in_bVisible ) ;</div>\n\
<div class=\"line\"><a name=\"l00626\"></a><span class=\"lineno\">  626</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00633\"></a><span class=\"lineno\">  633</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetRowsVisibility( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> &amp;in_alRows, <span class=\"keywordtype\">bool</span> in_bVisible ) ;</div>\n\
<div class=\"line\"><a name=\"l00634\"></a><span class=\"lineno\">  634</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00641\"></a><span class=\"lineno\">  641</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> SetCellReadOnlyFlags( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> &amp;in_alCells, <span class=\"keywordtype\">bool</span> in_bROFlag ) ;</div>\n\
<div class=\"line\"><a name=\"l00642\"></a><span class=\"lineno\">  642</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00649\"></a><span class=\"lineno\">  649</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> GetCellReadOnlyFlags( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">CLongArray</a> &amp;in_alCells, <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CBitArray.html\">CBitArray</a> &amp;out_aROFlags ) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00650\"></a><span class=\"lineno\">  650</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00656\"></a><span class=\"lineno\">  656</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutMultiSelectionMode( <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a85684a2710994de1caf37a37f0df6488\">XSI::siGridDataMultiSelectionMode</a> in_eSelectionMode ) ;</div>\n\
<div class=\"line\"><a name=\"l00657\"></a><span class=\"lineno\">  657</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00662\"></a><span class=\"lineno\">  662</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#a85684a2710994de1caf37a37f0df6488\">XSI::siGridDataMultiSelectionMode</a> GetMultiSelectionMode() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00663\"></a><span class=\"lineno\">  663</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00669\"></a><span class=\"lineno\">  669</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutReadOnly( <span class=\"keywordtype\">bool</span> in_bROFlag ) ;</div>\n\
<div class=\"line\"><a name=\"l00670\"></a><span class=\"lineno\">  670</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00675\"></a><span class=\"lineno\">  675</span>&#160;    <span class=\"keywordtype\">bool</span> GetReadOnly() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00676\"></a><span class=\"lineno\">  676</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00685\"></a><span class=\"lineno\">  685</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">CStatus</a> PutColumnComboItemsSortType(LONG in_ColumnIndex, <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ab99e48e9df093987a8bb231758f3e99c\">siGridWidgetColumnComboItemsSort</a> in_type);</div>\n\
<div class=\"line\"><a name=\"l00686\"></a><span class=\"lineno\">  686</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00693\"></a><span class=\"lineno\">  693</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/namespaceXSI.html#ab99e48e9df093987a8bb231758f3e99c\">siGridWidgetColumnComboItemsSort</a> GetColumnComboItemsSortType(LONG in_ColumnIndex) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00694\"></a><span class=\"lineno\">  694</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00695\"></a><span class=\"lineno\">  695</span>&#160;<span class=\"keyword\">private</span>:</div>\n\
<div class=\"line\"><a name=\"l00696\"></a><span class=\"lineno\">  696</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00697\"></a><span class=\"lineno\">  697</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a> * operator&amp;() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00698\"></a><span class=\"lineno\">  698</span>&#160;    <a class=\"code\" href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">GridData</a> * operator&amp;();</div>\n\
<div class=\"line\"><a name=\"l00699\"></a><span class=\"lineno\">  699</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00700\"></a><span class=\"lineno\">  700</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00701\"></a><span class=\"lineno\">  701</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00702\"></a><span class=\"lineno\">  702</span>&#160;<span class=\"preprocessor\">#endif // __XSIGRIDDATA_H__</span></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CRef_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CRef.html\">XSI::CRef</a></div><div class=\"ttdoc\">This class is used to reference Softimage objects. Each instance of an CRef maintains a link with onl...</div><div class=\"ttdef\"><b>Definition:</b> xsi_ref.h:142</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CBitArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CBitArray.html\">XSI::CBitArray</a></div><div class=\"ttdoc\">This class encapsulates an array of binary values represented as booleans, where true indicates a bit...</div><div class=\"ttdef\"><b>Definition:</b> xsi_bitarray.h:57</div></div>\n\
<div class=\"ttc\" id=\"xsi__value_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__value_8h.html\">xsi_value.h</a></div><div class=\"ttdoc\">CValue and CValueArray class declarations. </div></div>\n\
<div class=\"ttc\" id=\"structXSI_1_1CColor_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/structXSI_1_1CColor.html\">XSI::CColor</a></div><div class=\"ttdoc\">This struct represents an RGBA color. </div><div class=\"ttdef\"><b>Definition:</b> xsi_color.h:56</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_ab99e48e9df093987a8bb231758f3e99c\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#ab99e48e9df093987a8bb231758f3e99c\">XSI::siGridWidgetColumnComboItemsSort</a></div><div class=\"ttdeci\">siGridWidgetColumnComboItemsSort</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:3317</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CValue_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CValue.html\">XSI::CValue</a></div><div class=\"ttdoc\">The CValue object provides the convenience of a loosely typed variable inside a strictly typed langua...</div><div class=\"ttdef\"><b>Definition:</b> xsi_value.h:159</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1GridData_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1GridData.html\">XSI::GridData</a></div><div class=\"ttdoc\">This object represents a 2-dimensional array of data. The word Grid refers to the visual presentation...</div><div class=\"ttdef\"><b>Definition:</b> xsi_griddata.h:184</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_afadf9141376c7d94593391531aebaabc\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#afadf9141376c7d94593391531aebaabc\">XSI::siGridWidgetColumnType</a></div><div class=\"ttdeci\">siGridWidgetColumnType</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:1833</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CBase_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CBase.html\">XSI::CBase</a></div><div class=\"ttdoc\">CBase is the base class of all API classes and provides access to Softimage objects through generic C...</div><div class=\"ttdef\"><b>Definition:</b> xsi_base.h:137</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_ad483c77b3d997caca1f369db99c1e68b\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#ad483c77b3d997caca1f369db99c1e68b\">XSI::siClassID</a></div><div class=\"ttdeci\">siClassID</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:1537</div></div>\n\
<div class=\"ttc\" id=\"xsi__ppgitem_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__ppgitem_8h.html\">xsi_ppgitem.h</a></div><div class=\"ttdoc\">PPGItem class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CString_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CString.html\">XSI::CString</a></div><div class=\"ttdoc\">Character strings in the Softimage SDK are represented with the CString class. CString consist of a v...</div><div class=\"ttdef\"><b>Definition:</b> xsi_string.h:76</div></div>\n\
<div class=\"ttc\" id=\"namespaceXSI_html_a85684a2710994de1caf37a37f0df6488\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/namespaceXSI.html#a85684a2710994de1caf37a37f0df6488\">XSI::siGridDataMultiSelectionMode</a></div><div class=\"ttdeci\">siGridDataMultiSelectionMode</div><div class=\"ttdef\"><b>Definition:</b> xsi_decl.h:1860</div></div>\n\
<div class=\"ttc\" id=\"xsi__bitarray_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__bitarray_8h.html\">xsi_bitarray.h</a></div><div class=\"ttdoc\">CBitArray class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CStatus_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CStatus.html\">XSI::CStatus</a></div><div class=\"ttdoc\">Encapsulates status data types for error handling purpose. The class also exposes methods to query an...</div><div class=\"ttdef\"><b>Definition:</b> xsi_status.h:36</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CValueArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CValueArray.html\">XSI::CValueArray</a></div><div class=\"ttdoc\">The CValueArray is an uni-dimensional array of CValue. </div><div class=\"ttdef\"><b>Definition:</b> xsi_value.h:1214</div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1GridWidget_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1GridWidget.html\">XSI::GridWidget</a></div><div class=\"ttdoc\">The GridWidget object represents the user interface control that shows a GridData object inside a Pro...</div><div class=\"ttdef\"><b>Definition:</b> xsi_gridwidget.h:46</div></div>\n\
<div class=\"ttc\" id=\"xsi__base_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/xsi__base_8h.html\">xsi_base.h</a></div><div class=\"ttdoc\">CBase class declaration. </div></div>\n\
<div class=\"ttc\" id=\"classXSI_1_1CLongArray_html\"><div class=\"ttname\"><a href=\"#!/url=./si_cpp/classXSI_1_1CLongArray.html\">XSI::CLongArray</a></div><div class=\"ttdoc\">The CLongArray is an uni-dimensional array of LONG values. </div><div class=\"ttdef\"><b>Definition:</b> xsi_longarray.h:45</div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";